### ISSUE TITLE
"url" issue on Lookup

### ISSUE THREAD

**Issue by marcoferre** [twintproject/twint#1003]
- [x] Python version is 3.6;
- [x] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
```
for t in tweet_list:
  b = twint.Config()
  b.Username = t['username']
  b.Store_object = True

  twint.run.Lookup(b)

  user = twint.output.users_list[-1]
  t.update(user.__dict__)

  print(t)
  time.sleep(1)
```
>It runs 3 times than this exception
```
CRITICAL:root:twint.get:User:'url'
ERROR:root:twint.run:Twint:Lookup:Unexpected exception occurred.
Traceback (most recent call last):
  File "/content/src/twint/twint/run.py", line 307, in Lookup
    await get.User(self.config.Username, self.config, db.Conn(self.config.Database))
  File "/content/src/twint/twint/get.py", line 228, in User
    await Users(j_r, config, conn)
  File "/content/src/twint/twint/output.py", line 177, in Users
    user = User(u)
  File "/content/src/twint/twint/user.py", line 31, in User
    _usr.url = ur['data']['user']['legacy']['url']
KeyError: 'url'
```
--------------------

### Environment Details
Google Colab, Win

**Comment by aabid0193** [comment]
same issue here

**Comment by seonake** [comment]
It is not 'url' problem... it is 'data', but may be related

CRITICAL:root:twint.get:User:'data'
ERROR:root:twint.run:Twint:Lookup:Unexpected exception occurred.
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/twint/run.py", line 307, in Lookup
    await get.User(self.config.Username, self.config, db.Conn(self.config.Database))
  File "/root/.local/lib/python3.6/site-packages/twint/get.py", line 228, in User
    await Users(j_r, config, conn)
  File "/root/.local/lib/python3.6/site-packages/twint/output.py", line 177, in Users
    user = User(u)
  File "/root/.local/lib/python3.6/site-packages/twint/user.py", line 21, in User
    if 'data' not in ur and 'user' not in ur['data']:
KeyError: 'data'
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-2-d451df497d75> in <module>()
     31     c.Username = cuenta
     32 
---> 33     twint.run.Lookup(c)
     34     df = twint.storage.panda.User_df
     35 

11 frames
/root/.local/lib/python3.6/site-packages/twint/user.py in User(ur)
     19 def User(ur):
     20     logme.debug(__name__ + ':User')
---> 21     if 'data' not in ur and 'user' not in ur['data']:
     22         msg = 'malformed json! cannot be parsed to get user data'
     23         logme.fatal(msg)

KeyError: 'data'

**Comment by seonake** [comment]
It is not 'url' problem... it is 'data', but may be related.

CRITICAL:root:twint.get:User:'data'
ERROR:root:twint.run:Twint:Lookup:Unexpected exception occurred.
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/twint/run.py", line 307, in Lookup
    await get.User(self.config.Username, self.config, db.Conn(self.config.Database))
  File "/root/.local/lib/python3.6/site-packages/twint/get.py", line 228, in User
    await Users(j_r, config, conn)
  File "/root/.local/lib/python3.6/site-packages/twint/output.py", line 177, in Users
    user = User(u)
  File "/root/.local/lib/python3.6/site-packages/twint/user.py", line 21, in User
    if 'data' not in ur and 'user' not in ur['data']:
KeyError: 'data'


---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-2-d451df497d75> in <module>()
     31     c.Username = cuenta
     32 
---> 33     twint.run.Lookup(c)
     34     df = twint.storage.panda.User_df
     35 

11 frames
/root/.local/lib/python3.6/site-packages/twint/user.py in User(ur)
     19 def User(ur):
     20     logme.debug(__name__ + ':User')
---> 21     if 'data' not in ur and 'user' not in ur['data']:
     22         msg = 'malformed json! cannot be parsed to get user data'
     23         logme.fatal(msg)

KeyError: 'data'

**Comment by MrNullPoint** [comment]
I think it because json parse error, sometimes when we query a user such as `@jack`, twitter return something like `.... user is suspend...` (a json can be parsed), so I changed `twint/user.py` some code, add `try...except...`, after reinstall twint, this problem is solved.
some code here:

``` 
    try:
        _usr.name = ur['data']['user']['legacy']['name']
    except:
        _usr.name = ''
    try:
        _usr.username = ur['data']['user']['legacy']['screen_name']
    except:
        _usr.username = ''
    try:
        _usr.bio = ur['data']['user']['legacy']['description']
    except:
        _usr.bio = ''
    try:
        _usr.location = ur['data']['user']['legacy']['location']
    except:
        _usr.location = ''
    try: 
        _usr.url = ur['data']['user']['legacy']['url']
    except:
        _usr.url = ''
` ``

**Comment by himanshudabas** [comment]
@MrNullPoint this has already been fixed [here](https://github.com/himanshudabas/twint/commit/a062eb5843a2ab8dd0a11384cbcc95f10d151e6a).
Also try except won't be the desired solution for this, because if something breaks, we should be able to diagnose that issue, what try except would do is simply suppress the issue, which would be much worse, as it would the final scraded dataset in an insonsistent state.

**Comment by micaelamaria** [comment]
@himanshudabas  --  I keep getting the error when I run twint -u USERNAME --user-full (i musing last kubuntu)

CRITICAL:root:twint.get:User:'url'
ERROR:root:twint.run:Twint:Lookup:Unexpected exception occurred.
Traceback (most recent call last):
  File "/home/mik/src/twint/twint/run.py", line 307, in Lookup
    await get.User(self.config.Username, self.config, db.Conn(self.config.Database))
  File "/home/mik/src/twint/twint/get.py", line 228, in User
    await Users(j_r, config, conn)
  File "/home/mik/src/twint/twint/output.py", line 177, in Users
    user = User(u)
  File "/home/mik/src/twint/twint/user.py", line 31, in User
    _usr.url = ur['data']['user']['legacy']['url']
KeyError: 'url'
Traceback (most recent call last):
  File "/home/mik/.local/bin/twint", line 11, in <module>
    load_entry_point('twint', 'console_scripts', 'twint')()
  File "/home/mik/src/twint/twint/cli.py", line 339, in run_as_command
    main()
  File "/home/mik/src/twint/twint/cli.py", line 326, in main
    run.Lookup(c)
  File "/home/mik/src/twint/twint/run.py", line 386, in Lookup
    run(config)
  File "/home/mik/src/twint/twint/run.py", line 329, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/mik/src/twint/twint/run.py", line 235, in main
    await task
  File "/home/mik/src/twint/twint/run.py", line 270, in run
    await self.Lookup()
  File "/home/mik/src/twint/twint/run.py", line 307, in Lookup
    await get.User(self.config.Username, self.config, db.Conn(self.config.Database))
  File "/home/mik/src/twint/twint/get.py", line 228, in User
    await Users(j_r, config, conn)
  File "/home/mik/src/twint/twint/output.py", line 177, in Users
    user = User(u)
  File "/home/mik/src/twint/twint/user.py", line 31, in User
    _usr.url = ur['data']['user']['legacy']['url']
KeyError: 'url'

**Comment by himanshudabas** [comment]
@micaelamaria 
My patch hasn't been merged to the master yet.
If you need to use twint urgently, you can install directly from [my branch](https://github.com/himanshudabas/twint/tree/fix-parser).
Although I must warn you that there will be some other issues in this branch.
If you do experience some other issue in the above branch, try installing from [this branch](https://github.com/himanshudabas/twint/tree/twint-fixes). This branch is still a work in progress, but it'll be much more stable.

**Comment by micaelamaria** [comment]
@himanshudabas  - how do I install the package from your branch using the command line? I tried infinite options, and none seems to be working :(

**Comment by himanshudabas** [comment]
@micaelamaria 

Try this :
```
pip3 install --user --upgrade git+https://github.com/himanshudabas/twint.git@origin/twint-fixes#egg=twint
```

**Comment by PinchOfData** [comment]
Hi guys, I think @@MrNullPoint is right to point out that the problem exists for other keys, too. Perhaps apply @himanshudabas solution to all keys?

**Comment by JesusCoyotzi** [comment]
Same issue from CLI:

twint -u jack --user-full
CRITICAL:root:twint.get:User:'url'
ERROR:root:twint.run:Twint:Lookup:Unexpected exception occurred.
Traceback (most recent call last):
  File "/home/jesus/.local/lib/python3.6/site-packages/twint/run.py", line 307, in Lookup
    await get.User(self.config.Username, self.config, db.Conn(self.config.Database))
  File "/home/jesus/.local/lib/python3.6/site-packages/twint/get.py", line 228, in User
    await Users(j_r, config, conn)
  File "/home/jesus/.local/lib/python3.6/site-packages/twint/output.py", line 177, in Users
    user = User(u)
  File "/home/jesus/.local/lib/python3.6/site-packages/twint/user.py", line 31, in User
    _usr.url = ur['data']['user']['legacy']['url']
KeyError: 'url'
Traceback (most recent call last):
  File "/home/jesus/.local/bin/twint", line 8, in <module>
    sys.exit(run_as_command())
  File "/home/jesus/.local/lib/python3.6/site-packages/twint/cli.py", line 339, in run_as_command
    main()
  File "/home/jesus/.local/lib/python3.6/site-packages/twint/cli.py", line 326, in main
    run.Lookup(c)
  File "/home/jesus/.local/lib/python3.6/site-packages/twint/run.py", line 386, in Lookup
    run(config)
  File "/home/jesus/.local/lib/python3.6/site-packages/twint/run.py", line 329, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/jesus/.local/lib/python3.6/site-packages/twint/run.py", line 235, in main
    await task
  File "/home/jesus/.local/lib/python3.6/site-packages/twint/run.py", line 270, in run
    await self.Lookup()
  File "/home/jesus/.local/lib/python3.6/site-packages/twint/run.py", line 307, in Lookup
    await get.User(self.config.Username, self.config, db.Conn(self.config.Database))
  File "/home/jesus/.local/lib/python3.6/site-packages/twint/get.py", line 228, in User
    await Users(j_r, config, conn)
  File "/home/jesus/.local/lib/python3.6/site-packages/twint/output.py", line 177, in Users
    user = User(u)
  File "/home/jesus/.local/lib/python3.6/site-packages/twint/user.py", line 31, in User
    _usr.url = ur['data']['user']['legacy']['url']
KeyError: 'url'

**Comment by edmangog** [comment]
Thank you, @himanshudabas ! I have installed twint from you [branch](https://github.com/himanshudabas/twint/tree/twint-fixes) which are able to scrape user's profile. However, when I execute the profile scraping in a loop around more than thousand times, there's a connection error freezes the loop(but not break out of the loop), which seems like the tor connection had been disrupted. I wonder how could we fix this? 

Error:

> Exception in thread RecvLoop_95.216.:
> Traceback (most recent call last):
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\torpy\circuit.py", line 233, in run
>     callback(key.fileobj, mask)
>   File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\torpy\circuit.py", line 220, in _do_recv
>     for cell in self._tor_socket.recv_cell_async():
>   File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\torpy\cell_socket.py", line 104, in recv_cell_async
>     more_data = self._socket.recv(TorCellSocket.RECV_BUFF_SIZE)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1226, in recv
>     return self.read(buflen)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1101, in read
>     return self._sslobj.read(len)
> ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

Here's my code: (Same Issues happens in using threading or not)
```
df = pd.read_csv('file.csv', index_col=0, header=0, encoding='utf-8-sig')
users= df['screen_name'].to_list()

def get_user_info(user):
    try:
        query = twint.Config()
        query.Username = user
        query.Output = user+".csv"
        query.Store_csv = True
        twint.run.Lookup(query)
    except:
        pass

ThreadPool().map(get_user_info, users)
```

**Comment by druskus20** [comment]
Same problem here.

**Comment by Kayden-lolasery** [comment]
still facing the issue

**Comment by Natata** [comment]
Thanks @vassef, this PR can fix the issue
https://github.com/twintproject/twint/pull/1255

**Comment by Ovid** [comment]
I'm also getting this issue,  Is anyone working on it? I see that https://github.com/twintproject/twint/pull/1255 fixes the issue, but at the cost of silently ignoring the error.

I might add that my examples uses `jack`, but I've other usernames (not sharing due to privacy—how ironic) that hit this issue too.

```
$ twint -u jack --user-full
CRITICAL:root:twint.get:User:'url'
ERROR:root:twint.run:Twint:Lookup:Unexpected exception occurred.
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/twint/run.py", line 307, in Lookup
    await get.User(self.config.Username, self.config, db.Conn(self.config.Database))
  File "/opt/homebrew/lib/python3.9/site-packages/twint/get.py", line 228, in User
    await Users(j_r, config, conn)
  File "/opt/homebrew/lib/python3.9/site-packages/twint/output.py", line 177, in Users
    user = User(u)
  File "/opt/homebrew/lib/python3.9/site-packages/twint/user.py", line 31, in User
    _usr.url = ur['data']['user']['legacy']['url']
KeyError: 'url'
Traceback (most recent call last):
  File "/opt/homebrew/bin/twint", line 8, in <module>
    sys.exit(run_as_command())
  File "/opt/homebrew/lib/python3.9/site-packages/twint/cli.py", line 339, in run_as_command
    main()
  File "/opt/homebrew/lib/python3.9/site-packages/twint/cli.py", line 326, in main
    run.Lookup(c)
  File "/opt/homebrew/lib/python3.9/site-packages/twint/run.py", line 386, in Lookup
    run(config)
  File "/opt/homebrew/lib/python3.9/site-packages/twint/run.py", line 329, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/homebrew/lib/python3.9/site-packages/twint/run.py", line 235, in main
    await task
  File "/opt/homebrew/lib/python3.9/site-packages/twint/run.py", line 270, in run
    await self.Lookup()
  File "/opt/homebrew/lib/python3.9/site-packages/twint/run.py", line 307, in Lookup
    await get.User(self.config.Username, self.config, db.Conn(self.config.Database))
  File "/opt/homebrew/lib/python3.9/site-packages/twint/get.py", line 228, in User
    await Users(j_r, config, conn)
  File "/opt/homebrew/lib/python3.9/site-packages/twint/output.py", line 177, in Users
    user = User(u)
  File "/opt/homebrew/lib/python3.9/site-packages/twint/user.py", line 31, in User
    _usr.url = ur['data']['user']['legacy']['url']
```
