### ISSUE TITLE
wierd error ** On entry to DGEBAL parameter number  3 had an illegal value  ** On entry to DGEHRD  parameter number  2 had an illegal value  ** On entry to DORGHR DORGQR parameter number  2 had an illegal value  ** On entry to DHSEQR parameter number  4 had an illegal value

### ISSUE THREAD

**Issue by pierrevalette** [twintproject/twint#1030]
Hi, so i have a weird issue running on windows with the cmd. i 'm new to twint and i have to use it for a social sciences paper for school. 
i install it with:

```
git clone --depth=1 https://github.com/twintproject/twint.git
cd twint
pip3 install . -r requirements.txt
```

the same occurs in both python 3.6 and 3.9. (double checked) and still got the exact same message.

i did Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;

I ran (checked different usernames possibilities)
twint -u username 

and i get :
```
C:\Users\Pierre\twint>twint u- pierre45167
 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
Traceback (most recent call last):
  File "C:\Users\Pierre\AppData\Local\Programs\Python\Python39\Scripts\twint-script.py", line 33, in <module>
    sys.exit(load_entry_point('twint==2.1.21', 'console_scripts', 'twint')())
  File "C:\Users\Pierre\AppData\Local\Programs\Python\Python39\Scripts\twint-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "c:\users\pierre\appdata\local\programs\python\python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "c:\users\pierre\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\users\pierre\twint\src\twint\twint\__init__.py", line 14, in <module>
    from . import run
  File "c:\users\pierre\twint\src\twint\twint\run.py", line 4, in <module>
    from . import datelock, feed, get, output, verbose, storage
  File "c:\users\pierre\twint\src\twint\twint\get.py", line 16, in <module>
    from .output import Tweets, Users
  File "c:\users\pierre\twint\src\twint\twint\output.py", line 6, in <module>
    from .storage import db, elasticsearch, write, panda
  File "c:\users\pierre\twint\src\twint\twint\storage\elasticsearch.py", line 2, in <module>
    from elasticsearch import Elasticsearch, helpers
  File "c:\users\pierre\appdata\local\programs\python\python39\lib\site-packages\elasticsearch\__init__.py", line 36, in <module>
    from .client import Elasticsearch
  File "c:\users\pierre\appdata\local\programs\python\python39\lib\site-packages\elasticsearch\client\__init__.py", line 22, in <module>
    from ..transport import Transport, TransportError
  File "c:\users\pierre\appdata\local\programs\python\python39\lib\site-packages\elasticsearch\transport.py", line 23, in <module>
    from .serializer import JSONSerializer, Deserializer, DEFAULT_SERIALIZERS
  File "c:\users\pierre\appdata\local\programs\python\python39\lib\site-packages\elasticsearch\serializer.py", line 35, in <module>
    import numpy as np
  File "c:\users\pierre\appdata\local\programs\python\python39\lib\site-packages\numpy\__init__.py", line 305, in <module>
    _win_os_check()
  File "c:\users\pierre\appdata\local\programs\python\python39\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
    raise RuntimeError(msg.format(__file__)) from None
RuntimeError: The current Numpy installation ('c:\\users\\pierre\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
```
If any of you had the issue or had ideas...
(i checked if there was other issues but nothing came out)

**Comment by himanshudabas** [comment]
this isn't actually a twint issue, it's related to numpy.
numpy1.19.4 has this bug on windows.
first uninstall the current numpy installation using:
```
pip uninstall numpy
```

Then install the previous version using:
```
pip install numpy==1.19.3
```

**Comment by pierrevalette** [comment]
> 
> 
> this isn't actually a twint issue, it's related to numpy.
> numpy1.19.4 has this bug on windows.
> first uninstall the current numpy installation using:
> 
> ```
> pip uninstall numpy
> ```
> 
> Then install the previous version using:
> 
> ```
> pip install numpy==1.19.3
> ```

**Comment by pierrevalette** [comment]
> 
> 
> this isn't actually a twint issue, it's related to numpy.
> numpy1.19.4 has this bug on windows.
> first uninstall the current numpy installation using:
> 
> ```
> pip uninstall numpy
> ```
> 
> Then install the previous version using:
> 
> ```
> pip install numpy==1.19.3
> ```

thank you so much !! Hope i didn't bother you too much you saved me on this one, i don't know i would have done otherwise.

**Comment by radler64** [comment]
Thanks a lot, helped me as well!

**Comment by qkrtlsan4218** [comment]
Thank you! you save my project!

**Comment by CloudOverTheHill** [comment]
thank you so much! Finaly find the solution here

**Comment by Baymaxly** [comment]
Thank you so much！

**Comment by DouglasAzevedo** [comment]
Muito Obrigado! @himanshudabas

**Comment by KaleidoscopeIM** [comment]
Thank you. It worked. 👍 :)

**Comment by Imangali2002** [comment]
Good thank u

**Comment by naveenchavala1234** [comment]
Thank you, it works!!

**Comment by kvalli** [comment]
thankyou it works

**Comment by adityakarante** [comment]
Thanks

**Comment by IsabellLehmann** [comment]
Thanks!

**Comment by IsabellLehmann** [comment]
We need at highest Python version 3.8.5. With Python 3.9, there is a problem using numpy 1.19.3.

**Comment by KacimiBadr** [comment]
Run into the same problem today, trying to use numpy and maxpluspy, this helped me. Thank you.

**Comment by HARSH-nith** [comment]
Thanks It really 💯% working

**Comment by Domonskuy** [comment]
Thank you it works!!

**Comment by mujeebishaque** [comment]
You don't have to manually uninstall the previous installation. `pip install numpy=1.19.3` would automatically uninstall the previous installation. just to save your 2 seconds.

**Comment by martinoywa** [comment]
Thank you!!!

**Comment by marreddysainikhilreddy** [comment]
Thank you helped a lot!!

**Comment by AlexisLoya** [comment]
grande

**Comment by petrkucerak** [comment]
Gracias!

**Comment by argv1** [comment]
> > this isn't actually a twint issue, it's related to numpy.
> > numpy1.19.4 has this bug on windows.
> > first uninstall the current numpy installation using:
> > ```
> > pip uninstall numpy
> > ```
> > 
> > 
> > Then install the previous version using:
> > ```
> > pip install numpy==1.19.3
> > ```
> 
> thank you so much !! Hope i didn't bother you too much you saved me on this one, i don't know i would have done otherwise.

holy smoke that helped, my script not even use numpy (only pandas) but was not able to run before downgrading to .19.3

**Comment by sammed-sankonatti** [comment]
Thank you sooooooooooooo much it helped

**Comment by aadegokemuideen** [comment]
Thanks a lot. It saves me a lot of time

**Comment by 9Syncopation** [comment]
thanks a lot!! you saved the day.

**Comment by bBenu** [comment]
Thank you, it works for me also..

**Comment by SamiaKaleem** [comment]
Hi,
I was facing the same error! A simple & perfect solution. Thanks!!

**Comment by henry-glitch** [comment]
thankyou this has helped me a lot

**Comment by aguaviva** [comment]
And yet another thank you!
