### ISSUE TITLE
database isn't working

### ISSUE THREAD

**Issue by Qriist** [twintproject/twint#1043]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [x] Python version is 3.6;
- [x] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

### Description of Issue
>Please use **as much detail as possible.**

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

Hello, inserting into the db is no longer working, regardless of if the db previously exists or not. Here's what I get.

`twint -u jack --database jack.db
[+] Inserting into Database: jack.db
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\Scripts\twint-script.py", line 11, in <module>
    load_entry_point('twint', 'console_scripts', 'twint')()
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\twint\cli.py", line 339, in run_as_command
    main()
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\twint\cli.py", line 330, in main
    run.Search(c)
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\twint\run.py", line 410, in Search
    run(config, callback)
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\twint\run.py", line 329, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "c:\users\user\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\twint\run.py", line 235, in main
    await task
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\twint\run.py", line 286, in run
    await self.tweets()
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\twint\run.py", line 226, in tweets
    await output.Tweets(tweet, self.config, self.conn)
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\twint\output.py", line 166, in Tweets
    await checkData(tweets, config, conn)
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\twint\output.py", line 140, in checkData
    db.tweets(conn, tweet, config)
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\twint\storage\db.py", line 293, in tweets
    cursor.execute(query, (Tweet.id, int(reply['user_id']), reply['username']))
KeyError: 'user_id'`

**Comment by rachmadaniHaryono** [comment]
i create a patch on this on #1301 and set it it to 0 when no user_id.

reply username may also missing and i replace that with empty string
