### ISSUE TITLE
Some error messages when running Twint - can anyone help?

### ISSUE THREAD

**Issue by hudmb** [twintproject/twint#1050]
Hi,

I just ran a simple 'twint -s pineapple' (see below). But I get error messages that I can't figure out. Can anyone help? Running on a macbook pro.

```
MY-MACBOOK:twint myusername$ twint -s pineapple
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/twint", line 5, in <module>
    from twint.cli import run_as_command
  File "/Users/myusername/Library/Python/3.8/lib/python/site-packages/twint/__init__.py", line 14, in <module>
    from . import run
  File "/Users/myusername/Library/Python/3.8/lib/python/site-packages/twint/run.py", line 4, in <module>
    from . import datelock, feed, get, output, verbose, storage
  File "/Users/myusername/Library/Python/3.8/lib/python/site-packages/twint/get.py", line 16, in <module>
    from .output import Tweets, Users
  File "/Users/myusername/Library/Python/3.8/lib/python/site-packages/twint/output.py", line 6, in <module>
    from .storage import db, elasticsearch, write, panda
  File "/Users/myusername/Library/Python/3.8/lib/python/site-packages/twint/storage/elasticsearch.py", line 2, in <module>
    from elasticsearch import Elasticsearch, helpers
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/elasticsearch/__init__.py", line 36, in <module>
    from .client import Elasticsearch
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 22, in <module>
    from ..transport import Transport, TransportError
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/elasticsearch/transport.py", line 23, in <module>
    from .serializer import JSONSerializer, Deserializer, DEFAULT_SERIALIZERS
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/elasticsearch/serializer.py", line 59, in <module>
    import pandas as pd
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/__init__.py", line 32, in <module>
    from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/_libs/__init__.py", line 3, in <module>
    from .tslibs import (
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/_libs/tslibs/__init__.py", line 3, in <module>
    from .conversion import localize_pydatetime, normalize_date
  File "__init__.pxd", line 918, in init pandas._libs.tslibs.conversion
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```

**Comment by hudmb** [comment]
Upgraded numpy, seems OK now
