### ISSUE TITLE
When using userlist I get KeyError: 'profile_banner_url'

### ISSUE THREAD

**Issue by hudmb** [twintproject/twint#1051]
Hi,

Running a simple: twint --userlist inputlist --user-full

(the userlist.txt file is in the same directory)

I get the following output: -

MY-MACKBOOK:~ myusername$ twint --userlist inputlist --user-full
CRITICAL:root:twint.get:User:'profile_banner_url'
ERROR:root:twint.run:Twint:Lookup:Unexpected exception occurred.
Traceback (most recent call last):
  File "/Users/myusername/Library/Python/3.8/lib/python/site-packages/twint/run.py", line 307, in Lookup
    await get.User(self.config.Username, self.config, db.Conn(self.config.Database))
  File "/Users/myusername/Library/Python/3.8/lib/python/site-packages/twint/get.py", line 228, in User
    await Users(j_r, config, conn)
  File "/Users/myusername/Library/Python/3.8/lib/python/site-packages/twint/output.py", line 177, in Users
    user = User(u)
  File "/Users/myusername/Library/Python/3.8/lib/python/site-packages/twint/user.py", line 49, in User
    _usr.background_image = ur['data']['user']['legacy']['profile_banner_url']
KeyError: 'profile_banner_url'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/twint", line 8, in <module>
    sys.exit(run_as_command())
  File "/Users/myusername/Library/Python/3.8/lib/python/site-packages/twint/cli.py", line 339, in run_as_command
    main()
  File "/Users/myusername/Library/Python/3.8/lib/python/site-packages/twint/cli.py", line 324, in main
    run.Lookup(c)
  File "/Users/myusername/Library/Python/3.8/lib/python/site-packages/twint/run.py", line 386, in Lookup
    run(config)
  File "/Users/davidbarrowcliff/Library/Python/3.8/lib/python/site-packages/twint/run.py", line 329, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/myusername/Library/Python/3.8/lib/python/site-packages/twint/run.py", line 235, in main
    await task
  File "/Users/myusername/Library/Python/3.8/lib/python/site-packages/twint/run.py", line 270, in run
    await self.Lookup()
  File "/Users/myusername/Library/Python/3.8/lib/python/site-packages/twint/run.py", line 307, in Lookup
    await get.User(self.config.Username, self.config, db.Conn(self.config.Database))
  File "/Users/myusername/Library/Python/3.8/lib/python/site-packages/twint/get.py", line 228, in User
    await Users(j_r, config, conn)
  File "/Users/myusername/Library/Python/3.8/lib/python/site-packages/twint/output.py", line 177, in Users
    user = User(u)
  File "/Users/myusername/Library/Python/3.8/lib/python/site-packages/twint/user.py", line 49, in User
    _usr.background_image = ur['data']['user']['legacy']['profile_banner_url']
KeyError: 'profile_banner_url'

**Comment by hudmb** [comment]
All sorted - I saw the fix posted.
