### ISSUE TITLE
aise BulkIndexError("%i document(s) failed to index." % len(errors), errors)

### ISSUE THREAD

**Issue by Parshuram2** [twintproject/twint#1058]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.
running from CLI doesn't give any error . Only when Indexing to elasticsearch, it fails to index.

### Description of Issue
Indexing to Elasticsearch @ http://localhost:9200
.............Traceback (most recent call last):
  File "rocky.py", line 8, in <module>
    twint.run.Search(c)
  File "/home/DeathStar/.local/lib/python3.8/site-packages/twint/run.py", line 410, in Search
    run(config, callback)
  File "/home/DeathStar/.local/lib/python3.8/site-packages/twint/run.py", line 329, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/DeathStar/.local/lib/python3.8/site-packages/twint/run.py", line 235, in main
    await task
  File "/home/DeathStar/.local/lib/python3.8/site-packages/twint/run.py", line 286, in run
    await self.tweets()
  File "/home/DeathStar/.local/lib/python3.8/site-packages/twint/run.py", line 226, in tweets
    await output.Tweets(tweet, self.config, self.conn)
  File "/home/DeathStar/.local/lib/python3.8/site-packages/twint/output.py", line 166, in Tweets
    await checkData(tweets, config, conn)
  File "/home/DeathStar/.local/lib/python3.8/site-packages/twint/output.py", line 152, in checkData
    elasticsearch.Tweet(tweet, config)
  File "/home/DeathStar/.local/lib/python3.8/site-packages/twint/storage/elasticsearch.py", line 293, in Tweet
    helpers.bulk(es, actions, chunk_size=2000, request_timeout=200)
  File "/home/DeathStar/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 390, in bulk
    for ok, item in streaming_bulk(client, actions, *args, **kwargs):
  File "/home/DeathStar/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 311, in streaming_bulk
    for data, (ok, info) in zip(
  File "/home/DeathStar/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 247, in _process_bulk_chunk
    for item in gen:
  File "/home/DeathStar/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 188, in _process_bulk_chunk_success
    raise BulkIndexError("%i document(s) failed to index." % len(errors), errors)
elasticsearch.helpers.errors.BulkIndexError: ('1 document(s) failed to index.', [{'index': {'_index': 'twinttweets', '_type': '_doc', '_id': '1334439827744284672_raw_', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': "failed to parse field [mentions] of type [keyword] in document with id '1334439827744284672_raw_'. Preview of field's value: '{screen_name=anubhavsinha, name=Anubhav Sinha, id=57947582}'", 'caused_by': {'type': 'illegal_state_exception', 'reason': "Can't get text on a START_OBJECT at 1:743"}}, 'data': {'id': '1334439827744284672', 'conversation_id': '1334439827744284672', 'created_at': '2020-12-03 05:10:22 EST', 'date': '2020-12-03 05:10:22', 'timezone': '-0500', 'place': '', 'tweet': 'And both stood their ground till the end for the dignity! And both had some kickass dialogues 😉 @anubhavsinha 🤗', 'language': 'en', 'hashtags': [], 'cashtags': [], 'user_id_str': '132992534', 'username': 'taapsee', 'name': 'taapsee pannu', 'day': 3, 'hour': 5, 'link': 'https://twitter.com/taapsee/status/1334439827744284672', 'retweet': False, 'essid': '', 'nlikes': 1720, 'nreplies': 32, 'nretweets': 34, 'quote_url': 'https://twitter.com/BenarasM/status/1334410052384378881', 'video': 0, 'search': 'None', 'near': None, 'user_rt_id': '', 'user_rt': '', 'retweet_id': '', 'retweet_date': '', 'mentions': [{'screen_name': 'anubhavsinha', 'name': 'Anubhav Sinha', 'id': '57947582'}]}}}])

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal? Kali Linux 2020.4

**Comment by Parshuram2** [comment]
I removed the verified field from the Config. However, I get the same error. Removed the Since as well. Still the same error.
```
 raise BulkIndexError("%i document(s) failed to index." % len(errors), errors)
elasticsearch.helpers.errors.BulkIndexError: ('1 document(s) failed to index.', [{'index': {'_index': 'twinttweets', '_type': '_doc', '_id': '1335837341957550083_raw_', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': "failed to parse field [mentions] of type [keyword] in document with id '1335837341957550083_raw_'. Preview of field's value: '{screen_name=NanhiKali, name=nanhikali, id=20121945}'", 'caused_by': {'type': 'illegal_state_exception', 'reason': "Can't get text on a START_OBJECT at 1:981"}}, 'data': {'id': '1335837341957550083', 'conversation_id': '1335837341957550083', 'created_at': '2020-12-07 01:43:35 EST', 'date': '2020-12-07 01:43:35', 'timezone': '-0500', 'place': '', 'tweet': 'Do you want to go on a virtual date with me this Christmas? Just log on to  https://t.co/b82EwPowEB &amp; donate now!Your donation will help @NanhiKali educate underprivileged girls in India, and get you a chance to virtually spend Christmas with me! So enter now! | @FankindOfficial  https://t.co/ETOTBtT5xu', 'language': 'en', 'hashtags': [], 'cashtags': [], 'user_id_str': '132992534', 'username': 'taapsee', 'name': 'taapsee pannu', 'day': 0, 'hour': 1, 'link': 'https://twitter.com/taapsee/status/1335837341957550083', 'retweet': False, 'essid': '', 'nlikes': 486, 'nreplies': 24, 'nretweets': 21, 'quote_url': '', 'video': 1, 'search': 'None', 'near': None, 'user_rt_id': '', 'user_rt': '', 'retweet_id': '', 'retweet_date': '', 'thumbnail': 'https://pbs.twimg.com/ext_tw_video_thumb/1335837056354816001/pu/img/80XW0I6Pf-dhtJVs.jpg', 'mentions': [{'screen_name': 'NanhiKali', 'name': 'nanhikali', 'id': '20121945'}, {'screen_name': 'FankindOfficial', 'name': 'fankindofficial', 'id': '1055485378755325953'}], 'urls': ['http://fankind.org/Taapsee']}}}])

```

**Comment by estebanpdl** [comment]
Hi, everyone. Is there a solution for this? This is happening also when searching for terms, not only users. It seems elasticsearch > 6.0.0 does not support multiple mapping types in one index.

**Comment by noah40povis** [comment]
I am dealing with the same issue.

**Comment by shouse** [comment]
To add to @estebanpdl comment, here's a link referencing that: https://discuss.elastic.co/t/resolved-failed-to-index-by-helpers-bulk/197296

**Comment by shouse** [comment]
After looking a bit longer I was able to get past the issue by following the `curl` commands here.  I didn't have to worry about deleting because I had nothing stored already. https://github.com/twintproject/twint/issues/1040#issuecomment-737359393

**Comment by juanvelascogomez** [comment]
> After looking a bit longer I was able to get past the issue by following the `curl` commands here. I didn't have to worry about deleting because I had nothing stored already. [#1040 (comment)](https://github.com/twintproject/twint/issues/1040#issuecomment-737359393)

Thanks, worked! :)

**Comment by Parshuram2** [comment]
> After looking a bit longer I was able to get past the issue by following the `curl` commands here. I didn't have to worry about deleting because I had nothing stored already. [#1040 (comment)](https://github.com/twintproject/twint/issues/1040#issuecomment-737359393)

What is this? I couldn't  make head or tails of it. Put DELETE,PUT PUT..in command line I get it. How does it work for searching for users or terms?

**Comment by parth647** [comment]
> After looking a bit longer I was able to get past the issue by following the `curl` commands here. I didn't have to worry about deleting because I had nothing stored already. [#1040 (comment)](https://github.com/twintproject/twint/issues/1040#issuecomment-737359393)

A few questions : 

- Are you running these command on windows cmd?
Because I tried to do the same but curl gave me the following error:
```
{
  "error" : "Content-Type header [application/x-www-form-urlencoded] is not supported",
  "status" : 406
}
```
I used the following command : 
`curl -d "{"settings":{"analysis":{"normalizer":{"hashtag_normalizer":{"filter":["lowercase","asciifolding"],"type":"custom","char_filter":[]}}}}}" -X PUT -H 'Content-Type:application/json'  "localhost:9200/twinttweets?pretty"`

**Comment by arranredsmart** [comment]
I'm having this issue and really need to use twint in a python script. Are there any work arounds?

**Comment by gerickt** [comment]
Same here... big problem
