### ISSUE TITLE
timeout error

### ISSUE THREAD

**Issue by charujing** [twintproject/twint#1067]
Dear,
I am trying tweet in Ubuntu, but it echos errors:
Thanks.

Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Ubuntu16.04LTS
(base) crj@crj:~$ twint -g="48.880048,2.385939,1km" -o file.csv --csv
Traceback (most recent call last):
  File "/media/crj/206E3F586E3F2646/anaconda3/lib/python3.8/site-packages/twint/get.py", line 148, in Response
    async with session.get(url, ssl=True, params=params, proxy=httpproxy) as response:
  File "/media/crj/206E3F586E3F2646/anaconda3/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/media/crj/206E3F586E3F2646/anaconda3/lib/python3.8/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/media/crj/206E3F586E3F2646/anaconda3/lib/python3.8/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/media/crj/206E3F586E3F2646/anaconda3/lib/python3.8/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/media/crj/206E3F586E3F2646/anaconda3/lib/python3.8/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/media/crj/206E3F586E3F2646/anaconda3/lib/python3.8/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/media/crj/206E3F586E3F2646/anaconda3/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/media/crj/206E3F586E3F2646/anaconda3/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/crj/206E3F586E3F2646/anaconda3/bin/twint", line 8, in <module>
    sys.exit(run_as_command())
  File "/media/crj/206E3F586E3F2646/anaconda3/lib/python3.8/site-packages/twint/cli.py", line 305, in run_as_command
    main()
  File "/media/crj/206E3F586E3F2646/anaconda3/lib/python3.8/site-packages/twint/cli.py", line 297, in main
    run.Search(c)
  File "/media/crj/206E3F586E3F2646/anaconda3/lib/python3.8/site-packages/twint/run.py", line 327, in Search
    run(config, callback)
  File "/media/crj/206E3F586E3F2646/anaconda3/lib/python3.8/site-packages/twint/run.py", line 226, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "/media/crj/206E3F586E3F2646/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/media/crj/206E3F586E3F2646/anaconda3/lib/python3.8/site-packages/twint/run.py", line 154, in main
    await task
  File "/media/crj/206E3F586E3F2646/anaconda3/lib/python3.8/site-packages/twint/run.py", line 199, in run
    await self.tweets()
  File "/media/crj/206E3F586E3F2646/anaconda3/lib/python3.8/site-packages/twint/run.py", line 137, in tweets
    await self.Feed()
  File "/media/crj/206E3F586E3F2646/anaconda3/lib/python3.8/site-packages/twint/run.py", line 45, in Feed
    response = await get.RequestUrl(self.config, self.init, headers=[("User-Agent", self.user_agent)])
  File "/media/crj/206E3F586E3F2646/anaconda3/lib/python3.8/site-packages/twint/get.py", line 119, in RequestUrl
    response = await Request(_url, params=params, connector=_connector, headers=headers)
  File "/media/crj/206E3F586E3F2646/anaconda3/lib/python3.8/site-packages/twint/get.py", line 143, in Request
    return await Response(session, url, params)
  File "/media/crj/206E3F586E3F2646/anaconda3/lib/python3.8/site-packages/twint/get.py", line 149, in Response
    return await response.text()
  File "/media/crj/206E3F586E3F2646/anaconda3/lib/python3.8/site-packages/async_timeout/__init__.py", line 45, in __exit__
    self._do_exit(exc_type)
  File "/media/crj/206E3F586E3F2646/anaconda3/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

**Comment by himanshudabas** [comment]
Related to #958

Instead of using anaconda, try using system-wide python or virtual environment instead.

**Comment by charujing** [comment]
> system-wide python or virtual environment instead

Thanks for your reply. Could you give me more details about the system-wide python or virtual environment?

**Comment by himanshudabas** [comment]
please go through the above mentioned issue once.

If you are still unable to fix the issue then let me know.

**Comment by charujing** [comment]
> please go through the above mentioned issue once.
> 
> If you are still unable to fix the issue then let me know.

Hi,
Thanks for your help. I install the python3.6.9 in ubuntu18.04_amd64, and it echo other errors:
====
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import twint
>>> c = twint.Config()
>>> c.Username = "realDonaldTrump"
>>> c.Search = "great"
>>> twint.run.Search(c)
WARNING:root:Error retrieving https://twitter.com/: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f792b409cf8>: Failed to establish a new connection: [Errno 111] Connection refused',))",),), retrying
WARNING:root:Error retrieving https://twitter.com/: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f792b409f98>: Failed to establish a new connection: [Errno 111] Connection refused',))",),), retrying
WARNING:root:Error retrieving https://twitter.com/: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f792b3a9278>: Failed to establish a new connection: [Errno 111] Connection refused',))",),), retrying
WARNING:root:Error retrieving https://twitter.com/: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f792b3a9518>: Failed to establish a new connection: [Errno 111] Connection refused',))",),), retrying
WARNING:root:Error retrieving https://twitter.com/: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f792b3a97b8>: Failed to establish a new connection: [Errno 111] Connection refused',))",),), retrying
ERROR:root:Error retrieving https://twitter.com/: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f792b409e80>: Failed to establish a new connection: [Errno 111] Connection refused',))",),)
CRITICAL:root:6 requests to https://twitter.com failed, giving up.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/charujing/.local/lib/python3.6/site-packages/twint/run.py", line 410, in Search
    run(config, callback)
  File "/home/charujing/.local/lib/python3.6/site-packages/twint/run.py", line 329, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "/home/charujing/.local/lib/python3.6/site-packages/twint/run.py", line 36, in __init__
    self.token.refresh()
  File "/home/charujing/.local/lib/python3.6/site-packages/twint/token.py", line 61, in refresh
    res = self._request()
  File "/home/charujing/.local/lib/python3.6/site-packages/twint/token.py", line 57, in _request
    raise RefreshTokenException(msg)
twint.token.RefreshTokenException: 6 requests to https://twitter.com failed, giving up.
===

**Comment by Akshay-shiva** [comment]
CRITICAL:root:twint.get:User:
Traceback (most recent call last):
  File "/home/shivakrishna/.local/lib/python3.9/site-packages/twint/get.py", line 167, in Response
    async with session.get(_url, ssl=True, params=params, proxy=httpproxy) as response:
  File "/home/shivakrishna/.local/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/home/shivakrishna/.local/lib/python3.9/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/home/shivakrishna/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/shivakrishna/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/shivakrishna/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/shivakrishna/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shivakrishna/.local/bin/twint", line 8, in <module>
    sys.exit(run_as_command())
  File "/home/shivakrishna/.local/lib/python3.9/site-packages/twint/cli.py", line 339, in run_as_command
    main()
  File "/home/shivakrishna/.local/lib/python3.9/site-packages/twint/cli.py", line 308, in main
    run.Followers(c)
  File "/home/shivakrishna/.local/lib/python3.9/site-packages/twint/run.py", line 351, in Followers
    run(config)
  File "/home/shivakrishna/.local/lib/python3.9/site-packages/twint/run.py", line 329, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/shivakrishna/.local/lib/python3.9/site-packages/twint/run.py", line 235, in main
    await task
  File "/home/shivakrishna/.local/lib/python3.9/site-packages/twint/run.py", line 251, in run
    self.config.User_id = await get.User(self.config.Username, self.config, self.conn, True)
  File "/home/shivakrishna/.local/lib/python3.9/site-packages/twint/get.py", line 219, in User
    response = await Request(_url, headers=_headers)
  File "/home/shivakrishna/.local/lib/python3.9/site-packages/twint/get.py", line 161, in Request
    return await Response(session, _url, params)
  File "/home/shivakrishna/.local/lib/python3.9/site-packages/twint/get.py", line 171, in Response
    return resp
  File "/home/shivakrishna/.local/lib/python3.9/site-packages/async_timeout/__init__.py", line 45, in __exit__
    self._do_exit(exc_type)
  File "/home/shivakrishna/.local/lib/python3.9/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

**Comment by Akshay-shiva** [comment]
Still getting timeout error
@himanshudabas @charujing My system Ubuntu 21, Python 3.9.5

wint -u realDonalTrump
WARNING:root:Error retrieving https://twitter.com/: ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9400dac970>, 'Connection to twitter.com timed out. (connect timeout=10)'))")), retrying
WARNING:root:Error retrieving https://twitter.com/: ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9400d6d1c0>, 'Connection to twitter.com timed out. (connect timeout=10)'))")), retrying

**Comment by Akshay-shiva** [comment]
@himanshudabas @charujing Ubuntu 21, Python  3.9.5
