### ISSUE TITLE
[TOR SESSION] Creating new TOR Session. Please give it a couple of seconds...

### ISSUE THREAD

**Issue by micaelamaria** [twintproject/twint#1092]
Whenever I try to run a line with twint (e.g. twint -u username --following) I get the same error: 

> [TOR SESSION] Creating new TOR Session. Please give it a couple of seconds...

This happend using OS Catalina and Ubuntu 20.04 on the terminal.

**Comment by eunbee31** [comment]
I have same issue.
What branch did you use @micaelamaria? As for me, I used this one: git+https://github.com/himanshudabas/twint.git@twint-fixes#egg=twint

**Comment by bo-tadpol** [comment]
If you are using this fork of twint - [https://github.com/himanshudabas/twint/tree/twint-fixes](url).

You need to change line 51 in **token.py** to the following.

```twitter_request = Request('GET', self.url, headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0'}).prepare()```

**Comment by himanshudabas** [comment]
Hi,
I'll be pushing the fix for that branch soon. So you all can pull changes from my branch and it will start working again,
I apologise for the delay in pushing the changes, I've been a little busy lately.

**Comment by bo-tadpol** [comment]
@himanshudabas I just merged the change into **twint-fixes**, should be good to go now.

**Comment by micaelamaria** [comment]
@himanshudabas  how can we forge that branch?

**Comment by eunbee31** [comment]
Hi, I updated this fork: https://github.com/himanshudabas/twint/tree/twint-fixe and it works in local, thanks. But is it normal that I still have the same issue on Google Cloud Platform?

**Comment by micaelamaria** [comment]
@himanshudabas  do you have te line to the right branch?

**Comment by micaelamaria** [comment]
@bo-tadpol - I don't have the file token.py in twint...! would you please share it: i ll add it.

**Comment by micaelamaria** [comment]
@himanshudabas I still receive the same "TRO SESSION..." when I run any commando with twint -- do you know about a quick fix?

**Comment by bo-tadpol** [comment]
@micaelamaria are you using the latest version of this branch of twint?

git+https://github.com/himanshudabas/twint.git@twint-fixes#egg=twint

**Comment by Manoj15** [comment]
Hi @himanshudabas ,

I am getting this error with TOR session : 
"ERROR:torpy.cell_socket:timed out
ERROR:torpy.utils:[ignored] torpy.cell_socket.TorSocketConnectError: timed out
WARNING:torpy.utils:Retry with another guard...
ERROR:torpy.cell_socket:timed out
ERROR:torpy.utils:[ignored] torpy.cell_socket.TorSocketConnectError: timed out
WARNING:torpy.utils:Retry with another guard...
ERROR:torpy.cell_socket:timed out
ERROR:root:[ignored]
Traceback (most recent call last):
  File "/home/jupyter/libraries/nb_env/lib64/python3.6/site-packages/torpy/cell_socket.py", line 63, in connect
    self._socket.connect((self._router.ip, self._router.or_port))
  File "/usr/lib64/python3.6/ssl.py", line 1109, in connect
    self._real_connect(addr, False)
  File "/usr/lib64/python3.6/ssl.py", line 1096, in _real_connect
    socket.connect(self, addr)
socket.timeout: timed out"

But I do get the results, just wanted to check what can I do to remove this problem.

Thanks in advance man, you are doing an awesome job in keeping this project alive :) Kudos !!!

**Comment by himanshudabas** [comment]
@Manoj15 
Hi,
This error you are getting Is actually a warning.
Tor is a bit unreliable, so whenever *torpy* is unable to create a session, it tries to recreate a fresh connection, and outputs the warning/error.
What you can do to supress this warning is explicitly supress the logging of *torpy* in your .py script.

You can google how this can be done, I remember doing this some time ago but I am unable to recollect it at present.

**Comment by micaelamaria** [comment]
@bo-tadpol @himanshudabas  I update to git+https://github.com/himanshudabas/twint.git@twint-fixes#egg=twint but I still get the same error "TOR SESSION..."  -- Any hint?

**Comment by Manoj15** [comment]
@himanshudabas ,

I tried using this : 
import warnings
warnings.filterwarnings('ignore')

But, still I am getting the above warning. Can you please check if you have that code as this creates a lot of exceptions on running.

Thanks,
Manoj Kumar

**Comment by lfrym** [comment]
Still having similar issues using the git+https://github.com/himanshudabas/twint.git@origin/twint-fixes#egg=twint branch as of July 2021. Initially it seemed to only start happening after searching for 1000 users, but now it happens immediately. It also seems to hang occasionally, giving a timeout error as per @Manoj15 above. 

Any updates or workarounds on this yet? Unfortunately the reconnection process slows down the scraping process by an order of magnitude.
