### ISSUE TITLE
'_GeneratorContextManager' object has no attribute 'close'

### ISSUE THREAD

**Issue by dcbacarro** [twintproject/twint#1096]
### Initial Check
> I am using twint for some time now, but suddenly I am getting this error. Please help.

>Make sure you've checked the following:

- [x] Python version is 3.6;
- [x] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>twint -s pineapple

### Description of Issue
>[TOR SESSION] Creating new TOR Session. Please give it a couple of seconds...
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/twint", line 8, in <module>
    sys.exit(run_as_command())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/twint/cli.py", line 344, in run_as_command
    main()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/twint/cli.py", line 335, in main
    run.Search(c)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/twint/run.py", line 419, in Search
    run(config, callback)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/twint/run.py", line 315, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/twint/run.py", line 36, in __init__
    self.token.refresh()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/twint/token.py", line 92, in refresh
    if not self._request():
  File "/home/ubuntu/.local/lib/python3.8/site-packages/twint/token.py", line 77, in _request
    self._get_new_session('tor')
  File "/home/ubuntu/.local/lib/python3.8/site-packages/twint/token.py", line 31, in _get_new_session
    self._session.close()
AttributeError: '_GeneratorContextManager' object has no attribute 'close'

### Environment Details
>Linux ip-172-31-38-200 5.4.0-1022-aws #22-Ubuntu SMP Wed Aug 12 13:50:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dcbacarro** [comment]
Thanks @bo-tadpol, it's working now.
