### ISSUE TITLE
Response payload is not completed

### ISSUE THREAD

**Issue by Vildnex** [twintproject/twint#1099]
### Command Ran
```
from datetime import datetime
import twint
import nest_asyncio

output_file = "tweets_output.csv"

nest_asyncio.apply()
config = twint.Config()
config.Search = "bitcoin OR btc OR bitcoinpump OR #bitcoin OR #btc OR #bitcoinpump "
config.Lang = "en"
config.Resume = output_file
# config.Limit = 200
config.Since = str(datetime(2009, 1, 3))
config.Until = str(datetime(2021, 1, 3))
config.Store_csv = True
config.Output = output_file
twint.run.Search(config)
```

### Description of Issue
After I'm running the script for over a period of time which could be between 1-2h until 5-6h I'm getting the fallowing error:
```
Traceback (most recent call last):
  File "/run/media/vlad/Common/Facultate/ICA-2/Semestru_1/Aplicatii_ale_lingvisticii_computationale/FinalProject/twitter/twitter_scapper.py", line 71, in <module>
    twint.run.Search(config)
  File "/run/media/vlad/Common/Facultate/ICA-2/Semestru_1/Aplicatii_ale_lingvisticii_computationale/FinalProject/venv/src/twint/twint/run.py", line 410, in Search
    run(config, callback)
  File "/run/media/vlad/Common/Facultate/ICA-2/Semestru_1/Aplicatii_ale_lingvisticii_computationale/FinalProject/venv/src/twint/twint/run.py", line 329, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "/run/media/vlad/Common/Facultate/ICA-2/Semestru_1/Aplicatii_ale_lingvisticii_computationale/FinalProject/venv/lib/python3.8/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
  File "/usr/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/lib/python3.8/asyncio/tasks.py", line 282, in __step
    result = coro.throw(exc)
  File "/run/media/vlad/Common/Facultate/ICA-2/Semestru_1/Aplicatii_ale_lingvisticii_computationale/FinalProject/venv/src/twint/twint/run.py", line 235, in main
    await task
  File "/usr/lib/python3.8/asyncio/futures.py", line 260, in __await__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.8/asyncio/tasks.py", line 349, in __wakeup
    future.result()
  File "/usr/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/run/media/vlad/Common/Facultate/ICA-2/Semestru_1/Aplicatii_ale_lingvisticii_computationale/FinalProject/venv/src/twint/twint/run.py", line 262, in run
    await self.tweets()
  File "/run/media/vlad/Common/Facultate/ICA-2/Semestru_1/Aplicatii_ale_lingvisticii_computationale/FinalProject/venv/src/twint/twint/run.py", line 217, in tweets
    await self.Feed()
  File "/run/media/vlad/Common/Facultate/ICA-2/Semestru_1/Aplicatii_ale_lingvisticii_computationale/FinalProject/venv/src/twint/twint/run.py", line 62, in Feed
    response = await get.RequestUrl(self.config, self.init)
  File "/run/media/vlad/Common/Facultate/ICA-2/Semestru_1/Aplicatii_ale_lingvisticii_computationale/FinalProject/venv/src/twint/twint/get.py", line 135, in RequestUrl
    response = await Request(_url, params=params, connector=_connector, headers=_headers)
  File "/run/media/vlad/Common/Facultate/ICA-2/Semestru_1/Aplicatii_ale_lingvisticii_computationale/FinalProject/venv/src/twint/twint/get.py", line 161, in Request
    return await Response(session, _url, params)
  File "/run/media/vlad/Common/Facultate/ICA-2/Semestru_1/Aplicatii_ale_lingvisticii_computationale/FinalProject/venv/src/twint/twint/get.py", line 168, in Response
    resp = await response.text()
  File "/run/media/vlad/Common/Facultate/ICA-2/Semestru_1/Aplicatii_ale_lingvisticii_computationale/FinalProject/venv/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1076, in text
    await self.read()
  File "/run/media/vlad/Common/Facultate/ICA-2/Semestru_1/Aplicatii_ale_lingvisticii_computationale/FinalProject/venv/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1032, in read
    self._body = await self.content.read()
  File "/run/media/vlad/Common/Facultate/ICA-2/Semestru_1/Aplicatii_ale_lingvisticii_computationale/FinalProject/venv/lib/python3.8/site-packages/aiohttp/streams.py", line 370, in read
    block = await self.readany()
  File "/run/media/vlad/Common/Facultate/ICA-2/Semestru_1/Aplicatii_ale_lingvisticii_computationale/FinalProject/venv/lib/python3.8/site-packages/aiohttp/streams.py", line 392, in readany
    await self._wait("readany")
  File "/run/media/vlad/Common/Facultate/ICA-2/Semestru_1/Aplicatii_ale_lingvisticii_computationale/FinalProject/venv/lib/python3.8/site-packages/aiohttp/streams.py", line 306, in _wait
    await waiter
  File "/usr/lib/python3.8/asyncio/futures.py", line 260, in __await__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.8/asyncio/tasks.py", line 349, in __wakeup
    future.result()
  File "/usr/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed

Process finished with exit code 1
```

### Environment Details
**My system:** 

**Python:** 3.8
**OS:** Manjaro 20.2
**IDE:** Pycharm
**Virtualenv:** 20.2.2 
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

**Comment by innocentius** [comment]
Yea, this looks like a very rare occuring, but still exist. Happened to me yesterday when i wan't observing.

**Comment by Vildnex** [comment]
And do you have and idea how can I fix it? Or any workaround?

**Comment by innocentius** [comment]
Well, you could always just catch the exception. It is a rare occuring (1/10000) so probably just need to run the query again. Alternatively, you could try to add in a catch & repeat system in the code of twint. We have an example already in the code (remember when you wait for 1.0, 8.0, 27.0 sec to try again? that one).

**Comment by Vildnex** [comment]
Could you tell me where I can find this example?

**Comment by innocentius** [comment]
https://github.com/twintproject/twint/blob/4b30fa33991ccdf89c77471382daad3d3bc8c988/twint/run.py#L123

From here. You will have to make any request async, which is a pain in the ass. I'm doing it with my branch for token retrival.

**Comment by Vildnex** [comment]
Well... I've just checked and debug it already for almost one entire day. I'm still getting that error over and over again, every single time, is not like a rare occurring, at least not for me. Also, I'm still not sure how can I catch it, I mean I've checked that code you told me about and I've tried to increase Retries_count and delay time, but I guess the problem is not there because nothings changed. So far... I think this is not a solvable issue, right? The problem is that I would like to run twint for over a long period of time, like few days, or maybe even more, like 1 2 weeks, I can't do that if I will get this error over and over again every single time.

**Comment by innocentius** [comment]
So you are scrapping a ton of data I guess. You are running twint for a long period of time, a few days, a month maybe. But, you are not calling twint only once aren't you? You are calling twint for billions of time to scrap different data from users. In this case, what if one twint call fails, what damage could it cost? As long as you don't let the exception break the whole program then it would be well, try somehting like this:

```python
try:
    twint()
except Exception as e:
    repeat the last twint call

**Comment by Vildnex** [comment]
Ok mate, thx :D. Now I understand how should I solve my issue and if I will encounter any new errors regarding what you said I will contact you again. Thank you so much :)
