### ISSUE TITLE
[QUESTION] Syntax Error in twint/output.py

### ISSUE THREAD

**Issue by saching6** [twintproject/twint#158]
There seems to be a syntax error in output.py 

I dont understand the "<<<<<<< HEAD" and ">>>>>>> dev " statements
import twint
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sachin/anaconda3/lib/python3.6/site-packages/twint/__init__.py", line 11, in <module>
    from . import run
  File "/home/sachin/anaconda3/lib/python3.6/site-packages/twint/run.py", line 1, in <module>
    from . import datelock, feed, get, output, verbose
  File "/home/sachin/anaconda3/lib/python3.6/site-packages/twint/get.py", line 2, in <module>
    from .output import Tweets, Users
  File "/home/sachin/anaconda3/lib/python3.6/site-packages/twint/output.py", line 1
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax

Linux Anaconda Python 3.6.4

**Comment by tiwaryshailesh** [comment]
I am getting the same error

**Comment by haccer** [comment]
Thanks, I made a mistake while attempting to merge from the dev branch to the master
