### ISSUE TITLE
Breaks while fetching large follower lists.

### ISSUE THREAD

**Issue by tiwaryshailesh** [twintproject/twint#159]
### Command Ran
python3 Twint.py -u xxxxxxxxx --followers -o follower.txt

### Description of Issue
After fetching about 7-8k followers, the code throws exception. This issue is not because of connectivity problems as I ran this test umpteen number of times.

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/connector.py", line 813, in _create_direct_connection
    hosts = yield from self._resolve_host(req.url.raw_host, req.port)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/connector.py", line 727, in _resolve_host
    loop=self._loop)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/resolver.py", line 31, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Twint.py", line 222, in <module>
    main()
  File "Twint.py", line 208, in main
    twint.run.Followers(c)
  File "/root/twint/twint/run.py", line 17, in Followers
    run(follow.Follow(config).main())
  File "/root/twint/twint/run.py", line 5, in run
    get_event_loop().run_until_complete(x)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/root/twint/twint/follow.py", line 36, in main
    await self.follow()
  File "/root/twint/twint/follow.py", line 21, in follow
    await self.Feed()
  File "/root/twint/twint/follow.py", line 13, in Feed
    response = await get.RequestUrl(self.config, self.init)
  File "/root/twint/twint/get.py", line 27, in RequestUrl
    response = await MobileRequest(_url)
  File "/root/twint/twint/get.py", line 35, in MobileRequest
    return await Response(session, url)
  File "/root/twint/twint/get.py", line 44, in Response
    async with session.get(url) as response:
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client.py", line 690, in __aenter__
    self._resp = yield from self._coro
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client.py", line 267, in _request
    conn = yield from self._connector.connect(req)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/connector.py", line 402, in connect
    proto = yield from self._create_connection(req)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/connector.py", line 749, in _create_connection
    _, proto = yield from self._create_direct_connection(req)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/connector.py", line 817, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host mobile.twitter.com:443 ssl:True [Name or service not known]

### Environment Details
Linux  4.14.0-kali3-amd64 #1 SMP Debian 4.14.12-2kali2 (2018-01-11) x86_64 GNU/Linux

**Comment by haccer** [comment]
>After fetching about 7-8k followers, the code throws exception. This issue is not because of connectivity problems as I ran this test umpteen number of times.


I'm going to have to rule this as a connectivity problem sorry lol

I'm not experiencing any issues like what you've described, and was able to collect more than 7-8k followers after a few minutes of run time. 

```
➜  twint git:(master) ✗ wc -l followers.txt
    8860 followers.txt
➜  twint git:(master) ✗ wc -l followers.txt
    9760 followers.txt
➜  twint git:(master) ✗ wc -l followers.txt
   13940 followers.txt
➜  twint git:(master) ✗
```

### Command Ran
`python3 Twint.py -u verified --followers -o followers.txt`

### Remediation Recommendations
- Update to the latest version of Twint
-
