### ISSUE TITLE
[Question]  Twint.Storage not found, possible problem with build

### ISSUE THREAD

**Issue by saching6** [twintproject/twint#163]
- [x] Python version is 3.6.4.
- [X] Using the latest version of Twint.
- [X] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>import twint
### Description of Issue
>>> import twint
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/saching/anaconda3/envs/py3/lib/python3.6/site-packages/twint/__init__.py", line 11, in <module>
    from . import run
  File "/home/saching/anaconda3/envs/py3/lib/python3.6/site-packages/twint/run.py", line 1, in <module>
    from . import datelock, feed, get, output, verbose
  File "/home/saching/anaconda3/envs/py3/lib/python3.6/site-packages/twint/get.py", line 2, in <module>
    from .output import Tweets, Users
  File "/home/saching/anaconda3/envs/py3/lib/python3.6/site-packages/twint/output.py", line 5, in <module>
    from .storage import db, elasticsearch, write, panda
ModuleNotFoundError: No module named 'twint.storage'
### Environment Details
>Anaconda on Linux (Linux subsystem of windows 10)

**Comment by haccer** [comment]
Needed to update [setup.py](https://github.com/twintproject/twint/commit/62a3e099689645534a0d5202d0a50e0c4e381828)

Should work now if you want to reinstall with setup.py or pip
