### ISSUE TITLE
Error with username lookup by user_id

### ISSUE THREAD

**Issue by jemather** [twintproject/twint#178]
I ran into an error when using the find/scrape tweets from a user when looking them up by user_id:

```python
  File "scrape_tweets_sample_userids.py", line 47, in <module>
    twint.run.Profile(c)
  File "/home/jemather/vicshame/tscrape/lib/python3.6/site-packages/twint/run.py", line 133, in Profile
    run(config)
  File "/home/jemather/vicshame/tscrape/lib/python3.6/site-packages/twint/run.py", line 117, in run
    get_event_loop().run_until_complete(Twint(config).main())
  File "/home/jemather/opt/python-3.6.6/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/home/jemather/vicshame/tscrape/lib/python3.6/site-packages/twint/run.py", line 80, in main
    self.config.Username = await get.Username(self.config.User_id)
  File "/home/jemather/vicshame/tscrape/lib/python3.6/site-packages/twint/get.py", line 53, in Username
    soup = BeautifulSoup(r, "html.parser")
  File "/home/jemather/vicshame/tscrape/lib/python3.6/site-packages/bs4/__init__.py", line 192, in __init__
    elif len(markup) <= 256 and (
TypeError: object of type 'coroutine' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scrape_tweets_sample_userids.py", line 50, in <module>
    time.sleep(10)
KeyboardInterrupt
sys:1: RuntimeWarning: coroutine 'Request' was never awaited
```

I was able to resolve the issue for my application by changing the `Username` function in `twint/get.py` (line 52) from:

`r = Request(url)`
to
`r = await Request(url)`

**Comment by rpanai** [comment]
If that is consistent with other request calls you might consider do a PR.

**Comment by jemather** [comment]
Hopefully I did that correctly - first time for an issue or for a pull request here.
