### ISSUE TITLE
Anyone else getting a ModuleNotFoundError?

### ISSUE THREAD

**Issue by bassreaves** [twintproject/twint#239]
### Command Ran
>python Twint.py -u username

### Description of Issue
>I ran the command from the terminal and got back a ModuleNotFoundError

Traceback (most recent call last):
  File "Twint.py", line 14, in <module>
    import twint
  File "C:\Users\Bass Reaves\Documents\GitHub\twint\twint\__init__.py", line 11, in <module>
    from . import run
  File "C:\Users\Bass Reaves\Documents\GitHub\twint\twint\run.py", line 1, in <module>
    from . import datelock, feed, get, output, verbose, storage
  File "C:\Users\Bass Reaves\Documents\GitHub\twint\twint\feed.py", line 1, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

### Environment Details
>Windows 10. running in cmd terminal

**Comment by bassreaves** [comment]
Fixed it. Needed to install the modules.
