### ISSUE TITLE
[BUG] AttributeError: 'tweet' object has no attribute 'user_rt'

### ISSUE THREAD

**Issue by wardnath** [twintproject/twint#283]
When I try to use Pandas I get an error with an unexpected attribute

Twint Version:
twint==1.2.0.0

### Command Ran
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import twint
>>> c = twint.Config()
>>> query= 'bar'
>>> c.Search = query
>>> c.Pandas = True
>>> twint.run.Search(c)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.6/site-packages/twint/run.py", line 201, in Search
    run(config)
  File ".../lib/python3.6/site-packages/twint/run.py", line 153, in run
    get_event_loop().run_until_complete(Twint(config).main())
  File ".../lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File ".../lib/python3.6/site-packages/twint/run.py", line 140, in main
    await self.tweets()
  File ".../lib/python3.6/site-packages/twint/run.py", line 103, in tweets
    await output.Tweets(tweet, "", self.config, self.conn)
  File ".../lib/python3.6/site-packages/twint/output.py", line 161, in Tweets
    await checkData(tweets, location, config, conn)
  File ".../lib/python3.6/site-packages/twint/output.py", line 142, in checkData
    panda.update(tweet, config)
  File ".../lib/python3.6/site-packages/twint/storage/panda.py", line 61, in update
    "user_rt": object.user_rt,
AttributeError: 'tweet' object has no attribute 'user_rt'
>>> 

### Description of Issue
AttributeError: 'tweet' object has no attribute 'user_rt'

### Environment Details
Mac OSX anaconda

**Comment by prof18** [comment]
Has this fix been included in the latest release? With version 1.2.0.0 still happening.

**Comment by pielco11** [comment]
The error is fixed, try updating with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`
