### ISSUE TITLE
Error saving tweet stats to file

### ISSUE THREAD

**Issue by ColinMcAuliffe** [twintproject/twint#314]
- [] Python version is 3.6; Yes
- [] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`; Yes
- [] I have searched the issues and there are no duplicates of this issue/question/request. Yes

Running on ubuntu 16.04 from the terminal

I attached a script which uses the twint module to store tweets collected from a given username. If I request stats like replies, retweets or likes with csv output, no csv file is produced. If I request the same using json output, it throws an error (see below). Everything works as expected if I don't request any stats though.

Any ideas?

script:

```
import twint 
usernames = ["twitter", "jack"]

fields = ["tweet","id","date","time","username","replies","retweets","Likes"]

for u in usernames:
    c = twint.Config()
    c.Username = u
    c.Since = "2018-01-01"
    c.Store_json= True
    c.Custom["tweet"] = fields
    c.Output = u

    # Run
    twint.run.Search(c)
```

error:
colin@colin-HP-Spectre-x360-Convertible-13-ae0xx:~/Desktop/DFP/twint/forSean$ python3.6 test.py 
783214 | Twitter | @Twitter | Private: 0 | Verified: 1 | Bio: What’s happening?! | Location: Everywhere | Url: https://about.twitter.com/ | Joined: 20 Feb 2007 6:35 AM | Tweets: 8408 | Following: 140 | Followers: 55747481 | Likes: 5571 | Media: 1887 | Avatar: https://pbs.twimg.com/profile_images/1013798240683266048/zRim1x6M_400x400.jpg
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    twint.run.Search(c)
  File "/home/colin/Desktop/DFP/twint/forSean/src/twint/twint/run.py", line 215, in Search
    run(config)
  File "/home/colin/Desktop/DFP/twint/forSean/src/twint/twint/run.py", line 167, in run
    get_event_loop().run_until_complete(Twint(config).main())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
    return future.result()
  File "/home/colin/Desktop/DFP/twint/forSean/src/twint/twint/run.py", line 154, in main
    await self.tweets()
  File "/home/colin/Desktop/DFP/twint/forSean/src/twint/twint/run.py", line 117, in tweets
    await output.Tweets(tweet, "", self.config, self.conn)
  File "/home/colin/Desktop/DFP/twint/forSean/src/twint/twint/output.py", line 118, in Tweets
    await checkData(tweets, location, config, conn)
  File "/home/colin/Desktop/DFP/twint/forSean/src/twint/twint/output.py", line 107, in checkData
    _output(tweet, output, config)
  File "/home/colin/Desktop/DFP/twint/forSean/src/twint/twint/output.py", line 64, in _output
    write.Json(obj, config)
  File "/home/colin/Desktop/DFP/twint/forSean/src/twint/twint/storage/write.py", line 66, in Json
    null, data = struct(obj, config.Custom[_obj_type], _obj_type)
  File "/home/colin/Desktop/DFP/twint/forSean/src/twint/twint/storage/write.py", line 38, in struct
    row[f] = meta.Data(obj, _type)[f]
KeyError: 'replies'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    twint.run.Search(c)
  File "/home/colin/Desktop/DFP/twint/forSean/src/twint/twint/run.py", line 215, in Search
    run(config)
  File "/home/colin/Desktop/DFP/twint/forSean/src/twint/twint/run.py", line 167, in run
    get_event_loop().run_until_complete(Twint(config).main())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
    return future.result()
  File "/home/colin/Desktop/DFP/twint/forSean/src/twint/twint/run.py", line 154, in main
    await self.tweets()
  File "/home/colin/Desktop/DFP/twint/forSean/src/twint/twint/run.py", line 117, in tweets
    await output.Tweets(tweet, "", self.config, self.conn)
  File "/home/colin/Desktop/DFP/twint/forSean/src/twint/twint/output.py", line 118, in Tweets
    await checkData(tweets, location, config, conn)
  File "/home/colin/Desktop/DFP/twint/forSean/src/twint/twint/output.py", line 107, in checkData
    _output(tweet, output, config)
  File "/home/colin/Desktop/DFP/twint/forSean/src/twint/twint/output.py", line 64, in _output
    write.Json(obj, config)
  File "/home/colin/Desktop/DFP/twint/forSean/src/twint/twint/storage/write.py", line 66, in Json
    null, data = struct(obj, config.Custom[_obj_type], _obj_type)
  File "/home/colin/Desktop/DFP/twint/forSean/src/twint/twint/storage/write.py", line 38, in struct
    row[f] = meta.Data(obj, _type)[f]
KeyError: 'replies'

**Comment by pielco11** [comment]
The correct fields are: `replies_count`, `likes_count` and `retweets_count`
