### ISSUE TITLE
Unable to fetch tweets after sometime

### ISSUE THREAD

**Issue by tiwaryshailesh** [twintproject/twint#324]
>Make sure you've checked the following:

- [YES] Python version is 3.6;
- [YES] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [YES] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
twint -s "bollywood" --verified --since 2018-01-01 --json -o bollywood2018.json

### Description of Issue
after getting tweets for the month of December, got this error

--Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/connector.py", line 843, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/connector.py", line 730, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/twint", line 11, in <module>
    load_entry_point('twint==1.2.1', 'console_scripts', 'twint')()
  File "/usr/local/lib/python3.6/dist-packages/twint-1.2.1-py3.6.egg/twint/cli.py", line 263, in run_as_command
  File "/usr/local/lib/python3.6/dist-packages/twint-1.2.1-py3.6.egg/twint/cli.py", line 255, in main
  File "/usr/local/lib/python3.6/dist-packages/twint-1.2.1-py3.6.egg/twint/run.py", line 215, in Search
  File "/usr/local/lib/python3.6/dist-packages/twint-1.2.1-py3.6.egg/twint/run.py", line 167, in run
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/twint-1.2.1-py3.6.egg/twint/run.py", line 154, in main
  File "/usr/local/lib/python3.6/dist-packages/twint-1.2.1-py3.6.egg/twint/run.py", line 111, in tweets
  File "/usr/local/lib/python3.6/dist-packages/twint-1.2.1-py3.6.egg/twint/run.py", line 41, in Feed
  File "/usr/local/lib/python3.6/dist-packages/twint-1.2.1-py3.6.egg/twint/get.py", line 66, in RequestUrl
  File "/usr/local/lib/python3.6/dist-packages/twint-1.2.1-py3.6.egg/twint/get.py", line 107, in Request
  File "/usr/local/lib/python3.6/dist-packages/twint-1.2.1-py3.6.egg/twint/get.py", line 112, in Response
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client.py", line 855, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client.py", line 370, in _request
    timeout=timeout
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/connector.py", line 445, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/connector.py", line 757, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/connector.py", line 847, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host twitter.com:443 ssl:False [Name or service not known]
--

### Environment Details
Using Debian 4.18.6 x64 machine (kali)

**Comment by pielco11** [comment]
Well, `socket.gaierror: [Errno -2] Name or service not known`. It seems that Twitter is blocking you, or that you are having connection issues
