### ISSUE TITLE
[BUG] Indian characters

### ISSUE THREAD

**Issue by RicardoAlexandreMartins** [twintproject/twint#329]
When I try to search tweets in indian characters, it occurs a problem. When I try to use as a module, it gives me an error:

I used this piece of code:

import twint

# Configure
c = twint.Config()
c.Search = "'राहुल गांधी'"
c.Format = "Tweet id: {id} | Tweet: {tweet}"

# Run
twint.run.Search(c)

Resulting in this error:

Traceback (most recent call last):
  File "/mnt/c/Temp/twint/test.py", line 9, in <module>
    twint.run.Search(c)
  File "/mnt/c/Temp/twint/twint/run.py", line 25, in Search
    run(search.Search(config).main())
  File "/mnt/c/Temp/twint/twint/run.py", line 5, in run
    get_event_loop().run_until_complete(x)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/mnt/c/Temp/twint/twint/search.py", line 130, in main
    await self.tweets()
  File "/mnt/c/Temp/twint/twint/search.py", line 57, in tweets
    await output.Tweets(tweet, "", self.config)
  File "/mnt/c/Temp/twint/twint/output.py", line 53, in Tweets
    output = format.Tweet(config, tweet)
  File "/mnt/c/Temp/twint/twint/format.py", line 11, in Tweet
    output = output.replace("{hashtags}", t.hashtags.encode('utf-8'))
AttributeError: 'list' object has no attribute 'encode'

I am using Python3 in Ubuntu subsystem in a Windows 10

**Comment by pielco11** [comment]
Hi @RicardoAlexandreMartins 

did you install Twint via pip or git? The git version is the most updated and I'm not getting errors with that version. We expected a couple of new errors that need to be fixed so I can't release a new pip version for now

![immagine](https://user-images.githubusercontent.com/17363750/50838784-2a0fa500-135f-11e9-8c9f-c8c060ed0b4b.png)
