### ISSUE TITLE
oserror errno22 invalid argument when using elastic search

### ISSUE THREAD

**Issue by socsprts7** [twintproject/twint#350]
Windows 10, python, everything is upgraded, and i can successully run kibana and elastic search

ran this command:

twint --elasticsearch localhost:9200 -u "username"

got back this:

[+] Indexing to Elasticsearch @ localhost:9200
Traceback (most recent call last):
  File "C:\Python\Scripts\twint-script.py", line 11, in <module>
    load_entry_point('twint', 'console_scripts', 'twint')()
  File "c:\users\steven\src\twint\twint\cli.py", line 263, in run_as_command
    main()
  File "c:\users\steven\src\twint\twint\cli.py", line 255, in main
    run.Search(c)
  File "c:\users\steven\src\twint\twint\run.py", line 239, in Search
    run(config)
  File "c:\users\steven\src\twint\twint\run.py", line 191, in run
    get_event_loop().run_until_complete(Twint(config).main())
  File "c:\python\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "c:\users\steven\src\twint\twint\run.py", line 176, in main
    await self.tweets()
  File "c:\users\steven\src\twint\twint\run.py", line 132, in tweets
    await output.Tweets(tweet, "", self.config, self.conn)
  File "c:\users\steven\src\twint\twint\output.py", line 147, in Tweets
    await checkData(tweets, location, config, conn)
  File "c:\users\steven\src\twint\twint\output.py", line 128, in checkData
    elasticsearch.Tweet(tweet, config)
  File "c:\users\steven\src\twint\twint\storage\elasticsearch.py", line 190, in Tweet
    day = weekdays[strftime("%A", localtime(Tweet.datetime))]
OSError: [Errno 22] Invalid argument

Not sure why this argument is occuring

**Comment by pielco11** [comment]
Does this happen with every user? Because I tried (on Ubuntu) different ones and everything is working right.

That error, ` OSError: [Errno 22] Invalid argument`, happens when you try to convert date formats, which involves system defined constants. [This](https://stackoverflow.com/questions/43099558/invalid-argument-when-converting-float-to-datetime#43152863) solution might help you.
To apply that solution you should clone twint locally in a directory, apply specific changes in `twnit/storage/elasticsearch.py`, run a simple script and see if the issue is solved.
The script could be just simply as this:
```python
import twint

c = twint.Config()
c.Username = "username"
c.Elasticsearch = "localhost:9200"

twint.run.Search(c)
```


I do not have a Windows machine, so unfortunately I can't try this for you
