### ISSUE TITLE
Error with installation

### ISSUE THREAD

**Issue by mbcrump** [twintproject/twint#377]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [X] Python version is 3.6;
```
mbcrump@crumplinux:~$ python3 --version
Python 3.6.8
```
- [X] Updated Twint with `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;

``
- [X] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.
```
twint
```
### Description of Issue
>Please use **as much detail as possible.**
I get the following error
```
Traceback (most recent call last):
  File "/home/mbcrump/.local/bin/twint", line 11, in <module>
    load_entry_point('twint', 'console_scripts', 'twint')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/mbcrump/src/twint/twint/__init__.py", line 13, in <module>
    from . import run
  File "/home/mbcrump/src/twint/twint/run.py", line 5, in <module>
    from . import datelock, feed, get, output, verbose, storage
  File "/home/mbcrump/src/twint/twint/get.py", line 14, in <module>
    from .output import Tweets, Users
  File "/home/mbcrump/src/twint/twint/output.py", line 6, in <module>
    from .storage import db, elasticsearch, write, panda
  File "/home/mbcrump/src/twint/twint/storage/panda.py", line 2, in <module>
    import pandas as pd
  File "/home/mbcrump/.local/lib/python3.6/site-packages/pandas/__init__.py", line 19, in <module>
    "Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']
```

I have tried uninstalling/installing numpy as well as panda. I've even tried cloning the repo and setting up from there to no avail. 

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?
```
mbcrump@crumplinux:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```

**Comment by pielco11** [comment]
I guess that the issue is on your end. I'll try to replicate your issue to see what a solution could be

**Comment by DumbMachine** [comment]
I had  a similar error, the following helped me solve it:
```bash
conda uninstall numpy #pip uninstall numpy
sudo apt install python3-pip
sudo apt-get install libatlas-base-dev
```
Not sure why installing the third is required, but it surely helped me solve the error( maybe its a dependency).
