### ISSUE TITLE
run twint got an error 

### ISSUE THREAD

**Issue by puface** [twintproject/twint#418]
# Issue Template
i got an error when i run twint -s "name" . 
i set http proxy in config.py line 55 -57 : 
   Proxy_host = "127.0.0.1"
    Proxy_port = "41615"
    Proxy_type = "http"

twint -s "bourne2018" --verified
/home/dva/.local/lib/python3.6/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/home/dva/PycharmProjects/twint/src/twint/twint/get.py", line 135, in Response
    async with session.get(url, ssl=False, params=params, proxy=httpproxy) as response:
  File "/home/dva/.local/lib/python3.6/site-packages/aiohttp/client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "/home/dva/.local/lib/python3.6/site-packages/aiohttp/client.py", line 476, in _request
    timeout=real_timeout
  File "/home/dva/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/dva/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "/home/dva/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 974, in _create_direct_connection
    req=req, client_error=client_error)
  File "/home/dva/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 924, in _wrap_create_connection
    await self._loop.create_connection(*args, **kwargs))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 770, in create_connection
    yield from self.sock_connect(sock, address)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 450, in sock_connect
    return (yield from fut)
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dva/.local/bin/twint", line 11, in <module>
    load_entry_point('twint', 'console_scripts', 'twint')()
  File "/home/dva/PycharmProjects/twint/src/twint/twint/cli.py", line 267, in run_as_command
    main()
  File "/home/dva/PycharmProjects/twint/src/twint/twint/cli.py", line 259, in main
    run.Search(c)
  File "/home/dva/PycharmProjects/twint/src/twint/twint/run.py", line 271, in Search
    run(config, callback)
  File "/home/dva/PycharmProjects/twint/src/twint/twint/run.py", line 200, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
    return future.result()
  File "/home/dva/PycharmProjects/twint/src/twint/twint/run.py", line 141, in main
    await task
  File "/home/dva/PycharmProjects/twint/src/twint/twint/run.py", line 185, in run
    await self.tweets()
  File "/home/dva/PycharmProjects/twint/src/twint/twint/run.py", line 124, in tweets
    await self.Feed()
  File "/home/dva/PycharmProjects/twint/src/twint/twint/run.py", line 50, in Feed
    response = await get.RequestUrl(self.config, self.init, headers=[("User-Agent", self.user_agent)])
  File "/home/dva/PycharmProjects/twint/src/twint/twint/get.py", line 80, in RequestUrl
    response = await Request(_url, params=params, connector=_connector, headers=headers)
  File "/home/dva/PycharmProjects/twint/src/twint/twint/get.py", line 130, in Request
    return await Response(session, url, params)
  File "/home/dva/PycharmProjects/twint/src/twint/twint/get.py", line 136, in Response
    return await response.text()
  File "/home/dva/.local/lib/python3.6/site-packages/async_timeout/__init__.py", line 45, in __exit__
    self._do_exit(exc_type)
  File "/home/dva/.local/lib/python3.6/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError

### Environment Details
os :ubuntu 18.04 64bit  python3.6

**Comment by pielco11** [comment]
You should not edit the installed package. Instead you should run Twint as module with a simple .py script

Twitter [reported](https://twitter.com/TwitterSupport/status/1127640741872840706) some issues with the search, but I can still get tweets. Please be sure to have everything OK with your proxy. `config.Proxy_port` needs to be an integer, not a string

https://github.com/twintproject/twint/blob/d8ad621dc9fb2ba3ff8408feddc8c459bb4147c2/twint/get.py#L21-L59

**Comment by Wu-J** [comment]
@pielco11 
I met this problem as well, but I cannot fully understand your comment. So it is grateful if you can explain it one more time, thank you so much!

**Comment by pielco11** [comment]
You don't need to edit `config.py` or other core files

Please read the Wiki to see how to use a proxy
