### ISSUE TITLE
Running twint after download

### ISSUE THREAD

**Issue by Artook10** [twintproject/twint#420]
trying to use twint but getting same error time after time. I am using Linux mint 18 with python 3.6.8.. Here in the error I get:

Traceback (most recent call last):
  File "/usr/local/bin/twint", line 6, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2985, in <module>
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2971, in _call_aside
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2998, in _initialize_master_working_set
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 660, in _build_master
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 968, in require
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 854, in resolve
pkg_resources.DistributionNotFound: The 'aiohttp_socks' distribution was not found and is required by twint
I have done pip3 install aiohttp_socks yet still get this error.

**Comment by pielco11** [comment]
It seems that you can't find the package. I guess this error resides out of twint

**Comment by Artook10** [comment]
Thanks for the reply I will try to find the issue with Mint and let you know the results.
