### ISSUE TITLE
 [QUESTION] got a error when run twint

### ISSUE THREAD

**Issue by yuuiki** [twintproject/twint#425]
# Issue Template
Please use this template!

### Description of Issue
Hello, sorry to disturb

I got an error run Twint as module with a test .py script, the log shows can not connect to twitter.com:80, but I have set  proxy host in my test.py.
and the status of proxy is ok, I can access twitter.com with chrome broswer

could you pls tell me where shoule I add or fix? thanks a lot
![image](https://user-images.githubusercontent.com/29880212/57759041-9e9e8a00-772b-11e9-9995-0e302ee1338d.png)

#this is my proxy
![image](https://user-images.githubusercontent.com/29880212/57759180-f806b900-772b-11e9-95c5-a0cfc27bfd8b.png)

#this is the error log
CRITICAL:root:twint.get:User:Cannot connect to host twitter.com:80 ssl:False [Connect call failed ('31.13.65.17', 80)]
Traceback (most recent call last):
  File "D:\Program Files\Python37\lib\site-packages\aiohttp\connector.py", line 924, in _wrap_create_connection
    await self._loop.create_connection(*args, **kwargs))
  File "D:\Program Files\Python37\Lib\asyncio\base_events.py", line 943, in create_connection
    raise exceptions[0]
  File "D:\Program Files\Python37\Lib\asyncio\base_events.py", line 930, in create_connection
    await self.sock_connect(sock, address)
  File "D:\Program Files\Python37\Lib\asyncio\selector_events.py", line 475, in sock_connect
    return await fut
  File "D:\Program Files\Python37\Lib\asyncio\selector_events.py", line 505, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 10060] Connect call failed ('31.13.65.17', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/Program Files/PycharmProjects/Python_Project/twint-master/test_2.py", line 12, in <module>
    twint.run.Search(c)
  File "D:\Program Files\PycharmProjects\Python_Project\twint-master\twint\run.py", line 271, in Search
    run(config, callback)
  File "D:\Program Files\PycharmProjects\Python_Project\twint-master\twint\run.py", line 200, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "D:\Program Files\Python37\Lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "D:\Program Files\PycharmProjects\Python_Project\twint-master\twint\run.py", line 141, in main
    await task
  File "D:\Program Files\PycharmProjects\Python_Project\twint-master\twint\run.py", line 185, in run
    await self.tweets()
  File "D:\Program Files\PycharmProjects\Python_Project\twint-master\twint\run.py", line 124, in tweets
    await self.Feed()
  File "D:\Program Files\PycharmProjects\Python_Project\twint-master\twint\run.py", line 50, in Feed
    response = await get.RequestUrl(self.config, self.init, headers=[("User-Agent", self.user_agent)])
  File "D:\Program Files\PycharmProjects\Python_Project\twint-master\twint\get.py", line 80, in RequestUrl
    response = await Request(_url, params=params, connector=_connector, headers=headers)
  File "D:\Program Files\PycharmProjects\Python_Project\twint-master\twint\get.py", line 130, in Request
    return await Response(session, url, params)
  File "D:\Program Files\PycharmProjects\Python_Project\twint-master\twint\get.py", line 135, in Response
    async with session.get(url, ssl=False, params=params, proxy=httpproxy) as response:
  File "D:\Program Files\Python37\lib\site-packages\aiohttp\client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "D:\Program Files\Python37\lib\site-packages\aiohttp\client.py", line 476, in _request
    timeout=real_timeout
  File "D:\Program Files\Python37\lib\site-packages\aiohttp\connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\Program Files\Python37\lib\site-packages\aiohttp\connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "D:\Program Files\Python37\lib\site-packages\aiohttp\connector.py", line 992, in _create_direct_connection
    raise last_exc
  File "D:\Program Files\Python37\lib\site-packages\aiohttp\connector.py", line 974, in _create_direct_connection
    req=req, client_error=client_error)
  File "D:\Program Files\Python37\lib\site-packages\aiohttp\connector.py", line 931, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host twitter.com:80 ssl:False [Connect call failed ('31.13.65.17', 80)]
### Environment Details
>Windows 7 and Python 3.7

**Comment by gpf951101** [comment]
Hi, Can you tell me how to solve the problem?

**Comment by pielco11** [comment]
It's a network issue, please be sure that your connection is working as wanted

**Comment by gpf951101** [comment]
> It's a network issue, please be sure that your connection is working as wanted

Thank you. I will check it.
