### ISSUE TITLE
[ERROR]aiohttp.client_exceptions.ServerDisconnectedError: None/concurrent.futures._base.CancelledError

### ISSUE THREAD

**Issue by yuuiki** [twintproject/twint#438]
# Issue Template
Please use this template!

### Description of Issue
>Sorry to disturb. I try to fetch all tweets from specific users. But it got an error after I fetch hundreds of twitter. Can you give the some suggestion? Thanks a lot 

c = twint.Config()
c.Username = "XHJapanese"
c.Proxy_host = "127.0.0.1"
c.Proxy_port = 7777
c.Proxy_type = "http"
c.Store_object = True
c.Profile_full = True
c.Retweets = True

# Start search
twint.run.Profile(c)

![image](https://user-images.githubusercontent.com/29880212/58406617-92f08300-809c-11e9-917c-d78ebcf52c18.png)

![image](https://user-images.githubusercontent.com/29880212/58410865-a5bb8580-80a5-11e9-9718-8379cefc5ab3.png)

##error
CRITICAL:root:twint.get:Multi:'NoneType' object is not callable
Traceback (most recent call last):
  File "D:/Program Files/PycharmProjects/Python_Project/twint-master/twitter_content.py", line 26, in <module>
    twint.run.Profile(c)
  File "D:\Program Files\PycharmProjects\Python_Project\twint-master\twint\run.py", line 261, in Profile
    run(config)
  File "D:\Program Files\PycharmProjects\Python_Project\twint-master\twint\run.py", line 200, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "D:\Program Files\Python37\Lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "D:\Program Files\PycharmProjects\Python_Project\twint-master\twint\run.py", line 141, in main
    await task
  File "D:\Program Files\PycharmProjects\Python_Project\twint-master\twint\run.py", line 182, in run
    await self.profile()
  File "D:\Program Files\PycharmProjects\Python_Project\twint-master\twint\run.py", line 113, in profile
    await self.Feed()
  File "D:\Program Files\PycharmProjects\Python_Project\twint-master\twint\run.py", line 50, in Feed
    response = await get.RequestUrl(self.config, self.init, headers=[("User-Agent", self.user_agent)])
  File "D:\Program Files\PycharmProjects\Python_Project\twint-master\twint\get.py", line 98, in RequestUrl
    response = await MobileRequest(_url, connector=_connector)
  File "D:\Program Files\PycharmProjects\Python_Project\twint-master\twint\get.py", line 134, in MobileRequest
    return await Response(session, url)
  File "D:\Program Files\PycharmProjects\Python_Project\twint-master\twint\get.py", line 162, in Response
    async with session.get(url, ssl=False, params=params, proxy=httpproxy) as response:
  File "D:\Program Files\Python37\lib\site-packages\aiohttp\client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "D:\Program Files\Python37\lib\site-packages\aiohttp\client.py", line 476, in _request
    timeout=real_timeout
  File "D:\Program Files\Python37\lib\site-packages\aiohttp\connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\Program Files\Python37\lib\site-packages\aiohttp\connector.py", line 851, in _create_connection
    req, traces, timeout)
  File "D:\Program Files\Python37\lib\site-packages\aiohttp\connector.py", line 1053, in _create_proxy_connection
    resp = await proxy_resp.start(conn)
  File "D:\Program Files\Python37\lib\site-packages\aiohttp\client_reqrep.py", line 844, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "D:\Program Files\Python37\lib\site-packages\aiohttp\streams.py", line 588, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: None

##error

CRITICAL:root:twint.get:Multi:'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\Program Files\PycharmProjects\Python_Project\twint-master\twint\get.py", line 162, in Response
    async with session.get(url, ssl=False, params=params, proxy=httpproxy) as response:
  File "D:\Program Files\Python37\lib\site-packages\aiohttp\client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "D:\Program Files\Python37\lib\site-packages\aiohttp\client.py", line 497, in _request
    await resp.start(conn)
  File "D:\Program Files\Python37\lib\site-packages\aiohttp\client_reqrep.py", line 844, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "D:\Program Files\Python37\lib\site-packages\aiohttp\streams.py", line 588, in read
    await self._waiter
concurrent.futures._base.CancelledError

### Environment Details
>Using Windows Pycharm

**Comment by pielco11** [comment]
I guess there was a connection issue
