### ISSUE TITLE
No location attribute when inserting into SQLite

### ISSUE THREAD

**Issue by sanrio503** [twintproject/twint#468]
### Initial Check
- [x] Python version is 3.6;
- [x] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

Possibly related to #454

### Command Ran
```
$ twint -u nike --database db/tweets3.db
[+] Inserting into Database: db/tweets3.db
Traceback (most recent call last):
  File "/usr/local/bin/twint", line 11, in <module>
    load_entry_point('twint', 'console_scripts', 'twint')()
  File "***tweets/src/twint/twint/cli.py", line 272, in run_as_command
    main()
  File "***tweets/src/twint/twint/cli.py", line 264, in main
    run.Search(c)
  File "***tweets/src/twint/twint/run.py", line 292, in Search
    run(config, callback)
  File "***tweets/src/twint/twint/run.py", line 213, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "***tweets/src/twint/twint/run.py", line 154, in main
    await task
  File "***tweets/src/twint/twint/run.py", line 198, in run
    await self.tweets()
  File "***tweets/src/twint/twint/run.py", line 145, in tweets
    await output.Tweets(tweet, self.config, self.conn)
  File "***tweets/src/twint/twint/output.py", line 154, in Tweets
    await checkData(tweets, config, conn)
  File "***tweets/src/twint/twint/output.py", line 120, in checkData
    db.tweets(conn, tweet, config)
  File "***tweets/src/twint/twint/storage/db.py", line 232, in tweets
    Tweet.location,
AttributeError: 'tweet' object has no attribute 'location'
```

### Description of Issue
> When saving tweets to a SQLite database, an error occurs `AttributeError: 'tweet' object has no attribute 'location'`
> 
>  Works fine inserting users into SQLite with `--user-full` and also works if changing output to JSON/CSV/CLI

### Environment Details
> Amazon Linux AMI 2018.03

**Comment by pielco11** [comment]
Currently the SQLite integration is broken

**Comment by pielco11** [comment]
Sorry for the late, I updated the structure. Feel free to give it a spin
