### ISSUE TITLE
elasticsearch.exceptions.RequestError: RequestError(400, 'action_request_validation_exception', 'Validation Failed: 1: type is missing;')

### ISSUE THREAD

**Issue by r-tateshina** [twintproject/twint#469]
### Initial Check
- [x] Python version is 3.6;
- [x] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
```
twint -u YozakuraTama -es localhost:9200
[+] Indexing to Elasticsearch @ localhost:9200
WARNING:elasticsearch:POST http://localhost:9200/_bulk [status:400 request:0.001s]
Traceback (most recent call last):
  File "/usr/local/bin/twint", line 11, in <module>
    load_entry_point('twint==1.2.3', 'console_scripts', 'twint')()
  File "/home/rtateshina/.local/lib/python3.6/site-packages/twint-1.2.3-py3.6.egg/twint/cli.py", line 272, in run_as_command
  File "/home/rtateshina/.local/lib/python3.6/site-packages/twint-1.2.3-py3.6.egg/twint/cli.py", line 264, in main
  File "/home/rtateshina/.local/lib/python3.6/site-packages/twint-1.2.3-py3.6.egg/twint/run.py", line 292, in Search
  File "/home/rtateshina/.local/lib/python3.6/site-packages/twint-1.2.3-py3.6.egg/twint/run.py", line 213, in run
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/rtateshina/.local/lib/python3.6/site-packages/twint-1.2.3-py3.6.egg/twint/run.py", line 154, in main
  File "/home/rtateshina/.local/lib/python3.6/site-packages/twint-1.2.3-py3.6.egg/twint/run.py", line 198, in run
  File "/home/rtateshina/.local/lib/python3.6/site-packages/twint-1.2.3-py3.6.egg/twint/run.py", line 145, in tweets
  File "/home/rtateshina/.local/lib/python3.6/site-packages/twint-1.2.3-py3.6.egg/twint/output.py", line 154, in Tweets
  File "/home/rtateshina/.local/lib/python3.6/site-packages/twint-1.2.3-py3.6.egg/twint/output.py", line 135, in checkData
  File "/home/rtateshina/.local/lib/python3.6/site-packages/twint-1.2.3-py3.6.egg/twint/storage/elasticsearch.py", line 256, in Tweet
  File "/home/rtateshina/.local/lib/python3.6/site-packages/elasticsearch/helpers/actions.py", line 300, in bulk
    for ok, item in streaming_bulk(client, actions, *args, **kwargs):
  File "/home/rtateshina/.local/lib/python3.6/site-packages/elasticsearch/helpers/actions.py", line 230, in streaming_bulk
    **kwargs
  File "/home/rtateshina/.local/lib/python3.6/site-packages/elasticsearch/helpers/actions.py", line 116, in _process_bulk_chunk
    raise e
  File "/home/rtateshina/.local/lib/python3.6/site-packages/elasticsearch/helpers/actions.py", line 112, in _process_bulk_chunk
    resp = client.bulk("\n".join(bulk_actions) + "\n", *args, **kwargs)
  File "/home/rtateshina/.local/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/rtateshina/.local/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 1499, in bulk
    headers={"content-type": "application/x-ndjson"},
  File "/home/rtateshina/.local/lib/python3.6/site-packages/elasticsearch/transport.py", line 353, in perform_request
    timeout=timeout,
  File "/home/rtateshina/.local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 251, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/rtateshina/.local/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 178, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'action_request_validation_exception', 'Validation Failed: 1: type is missing;')
```

### Description of Issue
When attempt to store tweets in Elasticsearch, an error `elasticsearch.exceptions.RequestError: RequestError(400, 'action_request_validation_exception', 'Validation Failed: 1: type is missing;')` occurs.
I googled the error message and then found the article:
https://discuss.elastic.co/t/validation-failed-because-of-missing-type-with-bulk-api/118465
However I was not able to identify where twint "forms payload properly".
How should I handle it?

### Environment Details
Ubuntu 18.04.2 LTS, Python 3.6.8

**Comment by pielco11** [comment]
Hi @r-tateshina, #400 might help you

**Comment by r-tateshina** [comment]
Thank you, I stupidly overlooked #400 
I apologize for bothering you.
