### ISSUE TITLE
SyntaxError: invalid syntax when importing

### ISSUE THREAD

**Issue by miguelwon** [twintproject/twint#495]
Just installed a fresh version of twint with:

```
git clone https://github.com/twintproject/twint.git
pip3 install -r requirements.txt
pip3 install twint
```

but having this error when importing:

```
>>> import twint
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mwon/twitter_bussola/env/lib/python3.5/site-packages/twint/__init__.py", line 11, in <module>
    from . import run
  File "/home/mwon/twitter_bussola/env/lib/python3.5/site-packages/twint/run.py", line 12
    self.init = f"TWEET-{config.Resume}-0"
                                         ^
SyntaxError: invalid syntax
```

**Environment Details**:
Python version is 3.5.2;
Ubuntu 16.04.4 LTS

**Comment by pielco11** [comment]
Python 3.6 or more is required
