### ISSUE TITLE
 twint --since error ValueError: unconverted data remains: 

### ISSUE THREAD

**Issue by fabionoth** [twintproject/twint#550]
# twint --since "2019-10-18 09:05:42" error
Using terminal CLI 
executing this command 
`twint -u <username> --since "2019-10-18 09:05:42" --limit 10 --stats --hashtags --csv -o file.csv`

I got this msg error: 
`Traceback (most recent call last):
  File ".local/bin/twint", line 11, in <module>
    sys.exit(run_as_command())
  File ".local/lib/python3.6/site-packages/twint/cli.py", line 295, in run_as_command
    main()
  File ".local/lib/python3.6/site-packages/twint/cli.py", line 287, in main
    run.Search(c)
  File ".local/lib/python3.6/site-packages/twint/run.py", line 292, in Search
    run(config, callback)
  File ".local/lib/python3.6/site-packages/twint/run.py", line 213, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File ".local/lib/python3.6/site-packages/twint/run.py", line 27, in __init__
    self.d = datelock.Set(self.config.Until, self.config.Since)
  File ".local/lib/python3.6/site-packages/twint/datelock.py", line 20, in Set
    d._since = datetime.datetime.strptime(Since, "%Y-%m-%d").date()
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 365, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains:  09:05:42`

**Comment by pielco11** [comment]
It seems that the pip package is still 2.1.2, while that functionality is available for twint 2.1.3

the latest build passed, don't know why package not published. I'm checking it right now

**Comment by pielco11** [comment]
Twint 2.1.3 for py3.6 and 3.7 is available now, please update and retry!

Twint 2.1.3 for py3.8-dev and pynightly is being pushed now

**Comment by pielco11** [comment]
Here's what I get 
![immagine](https://user-images.githubusercontent.com/17363750/67098961-9f40be00-f1ac-11e9-8208-31374786225c.png)

**Comment by fabionoth** [comment]
Awesome. o/ 
Thanks :-)
