### ISSUE TITLE
Proxy question

### ISSUE THREAD

**Issue by wangyun1996** [twintproject/twint#570]
# Proxy question
Hello,

I'm sorry for asking this question.

How can I set the proxy server?

I got a host, a port, a password.The encryption method is aes-256-cfb.I don't know how to use those things....

In twint, therr are Proxy_host, Proxy_port, Proxy_type. But I can't find one to fill with password.

Thank u very much.

**Comment by wangyun1996** [comment]
I tried to change a new VPN, but still give a warnning "aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host twitter.com:443 ssl:False [Connect call failed ('31.13.64.33', 443)]"

This VPN is a private VPN, so I think it works well. I don't know how to do next.

**Comment by pielco11** [comment]
You can place auth in `Proxy_host`, something like `user:pass@localhost`

I don't know why you are using both the VPN and the proxy settings. If you use a VPN you don't need specify a proxy or something else, just use Twint as usual

Proxy's settings are for proxies, not VPN

**Comment by wangyun1996** [comment]
I tried to change a new VPN, but still give a warnning "aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host twitter.com:443 ssl:False [Connect call failed ('31.13.64.33', 443)]"

This VPN is a private VPN, so I think it works well. I don't know how to do next.

> You can place auth in `Proxy_host`, something like `user:pass@localhost`
> 
> I don't know why you are using both the VPN and the proxy settings. If you use a VPN you don't need specify a proxy or something else, just use Twint as usual
> 
> Proxy's settings are for proxies, not VPN

Thank u for answer me.

If I use the VPN, and I can connect to the twitter.com by using my browser. Why can't I connect to it by using twint. Was my operation wrong?

Thank u!

**Comment by wangyun1996** [comment]
### My code
import twint
c = twint.Config()
c.User_id = "realDonaldTrump"
c.Search = "economy"
c.Since = "2009-01-01"
c.Until = "2019-06-30"
c.Limit = 10


### Run
runfile('D:/PycharmProjects/Twitter/ScapyTwitter.py', wdir='D:/PycharmProjects/Twitter')
Traceback (most recent call last):
  File "D:\Program Files\Python\Python37\lib\site-packages\aiohttp\connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "D:\Program Files\Python\Python37\lib\asyncio\base_events.py", line 954, in create_connection
    raise exceptions[0]
  File "D:\Program Files\Python\Python37\lib\asyncio\base_events.py", line 941, in create_connection
    await self.sock_connect(sock, address)
  File "D:\Program Files\Python\Python37\lib\asyncio\selector_events.py", line 464, in sock_connect
    return await fut
  File "D:\Program Files\Python\Python37\lib\asyncio\selector_events.py", line 494, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 10060] Connect call failed ('104.244.42.129', 443)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\Program Files\JetBrains\PyCharm 2019.2.2\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm 2019.2.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/PycharmProjects/Twitter/ScapyTwitter.py", line 19, in <module>
    twint.run.Search(c)
  File "D:\Program Files\Python\Python37\lib\site-packages\twint\run.py", line 292, in Search
    run(config, callback)
  File "D:\Program Files\Python\Python37\lib\site-packages\twint\run.py", line 213, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "D:\Program Files\Python\Python37\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "D:\Program Files\Python\Python37\lib\site-packages\twint\run.py", line 154, in main
    await task
  File "D:\Program Files\Python\Python37\lib\site-packages\twint\run.py", line 160, in run
    self.config.Username = await get.Username(self.config.User_id)
  File "D:\Program Files\Python\Python37\lib\site-packages\twint\get.py", line 176, in Username
    r = await Request(url)
  File "D:\Program Files\Python\Python37\lib\site-packages\twint\get.py", line 157, in Request
    return await Response(session, url, params)
  File "D:\Program Files\Python\Python37\lib\site-packages\twint\get.py", line 162, in Response
    async with session.get(url, ssl=False, params=params, proxy=httpproxy) as response:
  File "D:\Program Files\Python\Python37\lib\site-packages\aiohttp\client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "D:\Program Files\Python\Python37\lib\site-packages\aiohttp\client.py", line 483, in _request
    timeout=real_timeout
  File "D:\Program Files\Python\Python37\lib\site-packages\aiohttp\connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\Program Files\Python\Python37\lib\site-packages\aiohttp\connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "D:\Program Files\Python\Python37\lib\site-packages\aiohttp\connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "D:\Program Files\Python\Python37\lib\site-packages\aiohttp\connector.py", line 986, in _create_direct_connection
    req=req, client_error=client_error)
  File "D:\Program Files\Python\Python37\lib\site-packages\aiohttp\connector.py", line 943, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host twitter.com:443 ssl:False [Connect call failed ('104.244.42.129', 443)]

### I have used a VPN
I have used a VPN, and I can connect to twitter successfully.

**Comment by pielco11** [comment]
`realDonaldTrump` is not an user ID, you have to use `c.Username = "realDonaldTrump"` instead

I don't know why it does not work on your end

May you try updating Twint? A couple of things changed (the endpoints)

**Comment by wangyun1996** [comment]
> `realDonaldTrump` is not an user ID, you have to use `c.Username = "realDonaldTrump"` instead
> 
> I don't know why it does not work on your end
> 
> May you try updating Twint? A couple of things changed (the endpoints)

Thank u for ur reply.

I updated Twint just now, and I tried again. The problem has changed.

runfile('D:/PycharmProjects/Twitter/ScapyTwitter.py', wdir='D:/PycharmProjects/Twitter')
CRITICAL:root:twint.get:User:Cannot connect to host twitter.com:80 ssl:False [Connect call failed ('104.244.42.65', 80)]
Traceback (most recent call last):
  File "D:\Program Files\Python\Python37\lib\site-packages\twint\url.py", line 15, in _formatDate
    return datetime.datetime.strptime(date, "%Y-%m-%d %H:%M:%S").strftime('%s')
ValueError: Invalid format string
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\Program Files\JetBrains\PyCharm 2019.2.2\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm 2019.2.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/PycharmProjects/Twitter/ScapyTwitter.py", line 19, in <module>
    twint.run.Search(c)
  File "D:\Program Files\Python\Python37\lib\site-packages\twint\run.py", line 292, in Search
    run(config, callback)
  File "D:\Program Files\Python\Python37\lib\site-packages\twint\run.py", line 213, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "D:\Program Files\Python\Python37\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "D:\Program Files\Python\Python37\lib\site-packages\twint\run.py", line 154, in main
    await task
  File "D:\Program Files\Python\Python37\lib\site-packages\twint\run.py", line 174, in run
    await self.tweets()
  File "D:\Program Files\Python\Python37\lib\site-packages\twint\run.py", line 137, in tweets
    await self.Feed()
  File "D:\Program Files\Python\Python37\lib\site-packages\twint\run.py", line 57, in Feed
    response = await get.RequestUrl(self.config, self.init, headers=[("User-Agent", self.user_agent)])
  File "D:\Program Files\Python\Python37\lib\site-packages\twint\get.py", line 106, in RequestUrl
    _url, params, _serialQuery = await url.Search(config, init)
  File "D:\Program Files\Python\Python37\lib\site-packages\twint\url.py", line 95, in Search
    q += f" since:{_formatDate(config.Since)}"
  File "D:\Program Files\Python\Python37\lib\site-packages\twint\url.py", line 17, in _formatDate
    return datetime.datetime.strptime(date, "%Y-%m-%d").strftime('%s')
  File "D:\Program Files\Python\Python37\lib\_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "D:\Program Files\Python\Python37\lib\_strptime.py", line 362, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains:  00:00:00

I don't know the reason.

**Comment by wangyun1996** [comment]
If I comment out c.Since and c.Until, the error becomes the following:

runfile('D:/PycharmProjects/Twitter/ScapyTwitter.py', wdir='D:/PycharmProjects/Twitter')
CRITICAL:root:twint.get:User:Cannot connect to host twitter.com:80 ssl:False [Connect call failed ('104.244.42.65', 80)]
Traceback (most recent call last):
  File "D:\Program Files\Python\Python37\lib\site-packages\aiohttp\connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "D:\Program Files\Python\Python37\lib\asyncio\base_events.py", line 954, in create_connection
    raise exceptions[0]
  File "D:\Program Files\Python\Python37\lib\asyncio\base_events.py", line 941, in create_connection
    await self.sock_connect(sock, address)
  File "D:\Program Files\Python\Python37\lib\asyncio\selector_events.py", line 464, in sock_connect
    return await fut
  File "D:\Program Files\Python\Python37\lib\asyncio\selector_events.py", line 494, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 10060] Connect call failed ('104.244.42.65', 80)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\Program Files\JetBrains\PyCharm 2019.2.2\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm 2019.2.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/PycharmProjects/Twitter/ScapyTwitter.py", line 19, in <module>
    twint.run.Search(c)
  File "D:\Program Files\Python\Python37\lib\site-packages\twint\run.py", line 292, in Search
    run(config, callback)
  File "D:\Program Files\Python\Python37\lib\site-packages\twint\run.py", line 213, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "D:\Program Files\Python\Python37\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "D:\Program Files\Python\Python37\lib\site-packages\twint\run.py", line 154, in main
    await task
  File "D:\Program Files\Python\Python37\lib\site-packages\twint\run.py", line 198, in run
    await self.tweets()
  File "D:\Program Files\Python\Python37\lib\site-packages\twint\run.py", line 137, in tweets
    await self.Feed()
  File "D:\Program Files\Python\Python37\lib\site-packages\twint\run.py", line 57, in Feed
    response = await get.RequestUrl(self.config, self.init, headers=[("User-Agent", self.user_agent)])
  File "D:\Program Files\Python\Python37\lib\site-packages\twint\get.py", line 107, in RequestUrl
    response = await Request(_url, params=params, connector=_connector, headers=headers)
  File "D:\Program Files\Python\Python37\lib\site-packages\twint\get.py", line 157, in Request
    return await Response(session, url, params)
  File "D:\Program Files\Python\Python37\lib\site-packages\twint\get.py", line 162, in Response
    async with session.get(url, ssl=False, params=params, proxy=httpproxy) as response:
  File "D:\Program Files\Python\Python37\lib\site-packages\aiohttp\client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "D:\Program Files\Python\Python37\lib\site-packages\aiohttp\client.py", line 483, in _request
    timeout=real_timeout
  File "D:\Program Files\Python\Python37\lib\site-packages\aiohttp\connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\Program Files\Python\Python37\lib\site-packages\aiohttp\connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "D:\Program Files\Python\Python37\lib\site-packages\aiohttp\connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "D:\Program Files\Python\Python37\lib\site-packages\aiohttp\connector.py", line 986, in _create_direct_connection
    req=req, client_error=client_error)
  File "D:\Program Files\Python\Python37\lib\site-packages\aiohttp\connector.py", line 943, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host twitter.com:80 ssl:False [Connect call failed ('104.244.42.65', 80)]

Is my VPN does not work? But I can connect to twitter successfully.

**Comment by R6Six** [comment]
> If I comment out c.Since and c.Until, the error becomes the following:
> 
> runfile('D:/PycharmProjects/Twitter/ScapyTwitter.py', wdir='D:/PycharmProjects/Twitter')
> CRITICAL:root:twint.get:User:Cannot connect to host twitter.com:80 ssl:False [Connect call failed ('104.244.42.65', 80)]
> Traceback (most recent call last):
> File "D:\Program Files\Python\Python37\lib\site-packages\aiohttp\connector.py", line 936, in _wrap_create_connection
> return await self._loop.create_connection(*args, **kwargs) # type: ignore # noqa
> File "D:\Program Files\Python\Python37\lib\asyncio\base_events.py", line 954, in create_connection
> raise exceptions[0]
> File "D:\Program Files\Python\Python37\lib\asyncio\base_events.py", line 941, in create_connection
> await self.sock_connect(sock, address)
> File "D:\Program Files\Python\Python37\lib\asyncio\selector_events.py", line 464, in sock_connect
> return await fut
> File "D:\Program Files\Python\Python37\lib\asyncio\selector_events.py", line 494, in _sock_connect_cb
> raise OSError(err, f'Connect call failed {address}')
> TimeoutError: [Errno 10060] Connect call failed ('104.244.42.65', 80)
> The above exception was the direct cause of the following exception:
> Traceback (most recent call last):
> File "", line 1, in
> File "D:\Program Files\JetBrains\PyCharm 2019.2.2\helpers\pydev_pydev_bundle\pydev_umd.py", line 197, in runfile
> pydev_imports.execfile(filename, global_vars, local_vars) # execute the script
> File "D:\Program Files\JetBrains\PyCharm 2019.2.2\helpers\pydev_pydev_imps_pydev_execfile.py", line 18, in execfile
> exec(compile(contents+"\n", file, 'exec'), glob, loc)
> File "D:/PycharmProjects/Twitter/ScapyTwitter.py", line 19, in
> twint.run.Search(c)
> File "D:\Program Files\Python\Python37\lib\site-packages\twint\run.py", line 292, in Search
> run(config, callback)
> File "D:\Program Files\Python\Python37\lib\site-packages\twint\run.py", line 213, in run
> get_event_loop().run_until_complete(Twint(config).main(callback))
> File "D:\Program Files\Python\Python37\lib\asyncio\base_events.py", line 579, in run_until_complete
> return future.result()
> File "D:\Program Files\Python\Python37\lib\site-packages\twint\run.py", line 154, in main
> await task
> File "D:\Program Files\Python\Python37\lib\site-packages\twint\run.py", line 198, in run
> await self.tweets()
> File "D:\Program Files\Python\Python37\lib\site-packages\twint\run.py", line 137, in tweets
> await self.Feed()
> File "D:\Program Files\Python\Python37\lib\site-packages\twint\run.py", line 57, in Feed
> response = await get.RequestUrl(self.config, self.init, headers=[("User-Agent", self.user_agent)])
> File "D:\Program Files\Python\Python37\lib\site-packages\twint\get.py", line 107, in RequestUrl
> response = await Request(_url, params=params, connector=_connector, headers=headers)
> File "D:\Program Files\Python\Python37\lib\site-packages\twint\get.py", line 157, in Request
> return await Response(session, url, params)
> File "D:\Program Files\Python\Python37\lib\site-packages\twint\get.py", line 162, in Response
> async with session.get(url, ssl=False, params=params, proxy=httpproxy) as response:
> File "D:\Program Files\Python\Python37\lib\site-packages\aiohttp\client.py", line 1012, in **aenter**
> self._resp = await self._coro
> File "D:\Program Files\Python\Python37\lib\site-packages\aiohttp\client.py", line 483, in _request
> timeout=real_timeout
> File "D:\Program Files\Python\Python37\lib\site-packages\aiohttp\connector.py", line 523, in connect
> proto = await self._create_connection(req, traces, timeout)
> File "D:\Program Files\Python\Python37\lib\site-packages\aiohttp\connector.py", line 859, in _create_connection
> req, traces, timeout)
> File "D:\Program Files\Python\Python37\lib\site-packages\aiohttp\connector.py", line 1004, in _create_direct_connection
> raise last_exc
> File "D:\Program Files\Python\Python37\lib\site-packages\aiohttp\connector.py", line 986, in _create_direct_connection
> req=req, client_error=client_error)
> File "D:\Program Files\Python\Python37\lib\site-packages\aiohttp\connector.py", line 943, in _wrap_create_connection
> raise client_error(req.connection_key, exc) from exc
> aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host twitter.com:80 ssl:False [Connect call failed ('104.244.42.65', 80)]
> 
> Is my VPN does not work? But I can connect to twitter successfully.

Hi，have you solved it?
I have the same problem with you. I can reach to the Twitter' s website by using the VPN. But just Twint can't work. I've trapped in this for days, I don't know to how to solve it.
