### ISSUE TITLE
invalid syntax / async def Feed(self)

### ISSUE THREAD

**Issue by x0rzkov** [twintproject/twint#616]
Hi,

Hope you are doing all well !

I have the following error while executing a script:

```python
import twint

tweets = []

c = twint.Config()

c.Username = 'noneprivacy'
c.Limit = 20
c.Store_object = True
c.Store_object_tweets_list = tweets

twint.run.Search(c)
```

```bash
Traceback (most recent call last):
  File "simple.py", line 1, in <module>
    import twint
  File "/Users/xxxxxxxx/src/go/src/github.com/x0rzkov/twint/twint/__init__.py", line 14, in <module>
    from . import run
  File "/Users/xxxxxxxx/src/go/src/github.com/x0rzkov/twint/twint/run.py", line 45
    async def Feed(self):
            ^
SyntaxError: invalid syntax
```

Any idea what it could be ?

Cheers,
X

**Comment by pielco11** [comment]
Python version?

**Comment by x0rzkov** [comment]
my bad, I use python2 :-(
