### ISSUE TITLE
Between 12/18 and 12/19 2019 I'm getting a missing columns error when saving tweets to db

### ISSUE THREAD

**Issue by chadfay** [twintproject/twint#617]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
The command i run every day:
twint -u realDonaldTrump --since 2019-12-17 --database tweets.db

NEW command
twint -u realDonaldTrump --since 2019-12-17 --database new_tweets.db

### Description of Issue
I have a tweets.db that i have been collecting into for about a year. Today I just started getting an error:

`twint -u realDonaldTrump --since 2019-12-17 --database tweets.db
[+] Inserting into Database: tweets.db
Traceback (most recent call last):
  File "/home/XXXX/.local/bin/twint", line 11, in <module>
    sys.exit(run_as_command())
  File "/home/XXXX/.local/lib/python3.6/site-packages/twint/cli.py", line 298, in run_as_command
    main()
  File "/home/XXXX/.local/lib/python3.6/site-packages/twint/cli.py", line 290, in main
    run.Search(c)
  File "/home/XXXX/.local/lib/python3.6/site-packages/twint/run.py", line 288, in Search
    run(config, callback)
  File "/home/XXXX/.local/lib/python3.6/site-packages/twint/run.py", line 209, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/XXXX/.local/lib/python3.6/site-packages/twint/run.py", line 150, in main
    await task
  File "/home/XXXX/.local/lib/python3.6/site-packages/twint/run.py", line 194, in run
    await self.tweets()
  File "/home/XXXX/.local/lib/python3.6/site-packages/twint/run.py", line 141, in tweets
    await output.Tweets(tweet, self.config, self.conn)
  File "/home/XXXX/.local/lib/python3.6/site-packages/twint/output.py", line 142, in Tweets
    await checkData(tweets, config, conn)
  File "/home/XXXX/.local/lib/python3.6/site-packages/twint/output.py", line 112, in checkData
    db.tweets(conn, tweet, config)
  File "/home/XXXX/.local/lib/python3.6/site-packages/twint/storage/db.py", line 275, in tweets
    cursor.execute('INSERT INTO tweets VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)', entry)
`

I reviewed my tweets.db and sure enough there are missing columns. I ran the same command to create a new db.

Two columns were removed and 7 added to tweets.

remove location
remove profile_image_url

After hashtags insert:
cashtags - text

After video insert:
geo - text
near - text
source - text

After time_update insert:
translate - text DEFAULT
trans_src - text DEFAULT
trans_dest - text DEFAULT

I added them manually and it seems to be working now.

I'll send screenshots of New and ORIG.
![tweets_new](https://user-images.githubusercontent.com/26547989/71218448-67222e00-2276-11ea-98f1-974d46966df9.png)
![tweets_ORIG](https://user-images.githubusercontent.com/26547989/71218449-67222e00-2276-11ea-878e-c66f3ba99759.png)

### Environment Details
>Linux mint 19.3
 latest twint installed via pip3
Python 3.6

**Comment by pielco11** [comment]
You sure to be running the latest version of twint?
