### ISSUE TITLE
Problem with emoji in anaconda prompt(miniconda)

### ISSUE THREAD

**Issue by oosuan** [twintproject/twint#680]
So i run a twint in anaconda prompt(miniconda) to save out csv file and process in python and if i encounter tweet with emoji it will stop saving tweet.
This is a error message
`1235038564930293762 2020-03-04 10:05:14 SE Asia Standard Time <castby9arm> ไฟนอล 7 รีเมค 😭😭😭😭😭�Traceback (most recent call last):
  File "c:\users\user\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\Miniconda3\Scripts\twint.exe\__main__.py", line 7, in <module>
  File "c:\users\user\miniconda3\lib\site-packages\twint\cli.py", line 298, in run_as_command
    main()
  File "c:\users\user\miniconda3\lib\site-packages\twint\cli.py", line 290, in main
    run.Search(c)
  File "c:\users\user\miniconda3\lib\site-packages\twint\run.py", line 288, in Search
    run(config, callback)
  File "c:\users\user\miniconda3\lib\site-packages\twint\run.py", line 211, in run
    loop.run_until_complete(Twint(config).main(callback))
  File "c:\users\user\miniconda3\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "c:\users\user\miniconda3\lib\site-packages\twint\run.py", line 149, in main
    await task
  File "c:\users\user\miniconda3\lib\site-packages\twint\run.py", line 194, in run
    await self.tweets()
  File "c:\users\user\miniconda3\lib\site-packages\twint\run.py", line 140, in tweets
    await output.Tweets(tweet, self.config, self.conn)
  File "c:\users\user\miniconda3\lib\site-packages\twint\output.py", line 149, in Tweets
    await checkData(tweets, config, conn)
  File "c:\users\user\miniconda3\lib\site-packages\twint\output.py", line 136, in checkData
    _output(tweet, output, config)
  File "c:\users\user\miniconda3\lib\site-packages\twint\output.py", line 98, in _output
    print(output.replace('\n', ' '))
OSError: [WinError 87] The parameter is incorrect
1235038564930293762 2020-03-04 10:05:14 SE Asia Standard Time <castby9arm> ไฟนอล 7 รีเมค 😭😭😭😭😭�Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
OSError: [WinError 87] The parameter is incorrect
1235038564930293762 2020-03-04 10:05:14 SE Asia Standard Time <castby9arm> ไฟนอล 7 รีเมค 😭😭😭😭😭�1235038564930293762 2020-03-04 10:05:14 SE Asia Standard Time <castby9arm> ไฟนอล 7 รีเมค 😭😭😭😭😭😭😭`

i'm using Windows 10 pro 64-bit

**Comment by pielco11** [comment]
> OSError: [WinError 87]

Seems to be a compatibility issue with Windows rather than Twint itself

**Comment by alexandreteles** [comment]
Do you mind sharing the Python version you're using? This problem was supposedly fixed in a patch on Python itself from the past year.

**Comment by pielco11** [comment]
I'm currently using `3.7.5`

**Comment by Puncia** [comment]
It has to do with a tweet ending with emojis, as far as I'm aware. I don't really use python but I what I found is that the issue occurs only when outputting the tweets to console (as mentioned in https://github.com/twintproject/twint/issues/532#issuecomment-542697140 here).

So either using `-ho/--hide-output`, commenting from line 103 to line 107 in output.py or modifying line 104 to `print(output.replace('\n', ' ').encode('utf-8'))` fixes the issue if you want to output to a json or a csv file, though I'm not sure if it's the best solution.
