### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by Cyame** [twintproject/twint#724]
#264 # Initial Check
> I'm in Python 3.7 so I don't know whether it causes some troubles.

### Command Ran
I tried to get some tweets from a user,
```
>>> import twint
>>> conf = twint.Config()
>>> conf.Store_json = True
>>> conf.Output = "a.json"
>>> conf.Username = "shirakamifubuki"
>>> conf.Since = "2020-04-20 15:00:00"
>>> conf.Retweets = True
>>> twint.run.Search(conf)
```

### Description of Issue
> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\xuwenrui\AppData\Local\Programs\Python\Python37-32\lib\site-packages\twint\run.py", line 322, in Search
    run(config, callback)
  File "C:\Users\xuwenrui\AppData\Local\Programs\Python\Python37-32\lib\site-packages\twint\run.py", line 221, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "C:\Users\xuwenrui\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "C:\Users\xuwenrui\AppData\Local\Programs\Python\Python37-32\lib\site-packages\twint\run.py", line 149, in main
    await task
  File "C:\Users\xuwenrui\AppData\Local\Programs\Python\Python37-32\lib\site-packages\twint\run.py", line 194, in run
    await self.tweets()
  File "C:\Users\xuwenrui\AppData\Local\Programs\Python\Python37-32\lib\site-packages\twint\run.py", line 140, in tweets
    await output.Tweets(tweet, self.config, self.conn)
  File "C:\Users\xuwenrui\AppData\Local\Programs\Python\Python37-32\lib\site-packages\twint\output.py", line 155, in Tweets
    await checkData(tweets, config, conn)
  File "C:\Users\xuwenrui\AppData\Local\Programs\Python\Python37-32\lib\site-packages\twint\output.py", line 142, in checkData
    _output(tweet, output, config)
  File "C:\Users\xuwenrui\AppData\Local\Programs\Python\Python37-32\lib\site-packages\twint\output.py", line 104, in _output
    print(output.replace('\n', ' '))

then it always come to an OSError with traceback of this.
> OSError: [WinError 87]

I found it always stop at a specific tweet 
> Until (https://twitter.com/shirakamifubuki/status/1252345452424388609)
> Without (https://twitter.com/shirakamifubuki/status/1252345303119753216)

So I'm wondering if one of the tweet above includes some invalid characters that causes the trouble.
I'll be graceful if you could help me with this. Thx!
### Environment Details
>Using Windows, in ConEmu... and nothing special, I just run it in python env.

**Comment by Puncia** [comment]
https://github.com/twintproject/twint/issues/680 ?
