### ISSUE TITLE
Issues running from Anaconda3

### ISSUE THREAD

**Issue by angiemp** [twintproject/twint#748]
Python version 3.7.6
Run from Anaconda3
Win10

I'm tying to get tweets since march 14 to may 4 near Spain containing the word "balcon" with
`twint -s balcon --near spain --since "2020-03-14 00:00:00" --until "2020-05-05 00:00:00`
All I've got are 70 tweets from may 4th... then stops
Some ideas why this is happening??

Also when I try to get some tweets from early years like `twint -s balcon --near spain --since "2019-03-14 00:00:00"` all I get is the tweets from the last 10 days, then stop. 

I've tried with `twint -s balcon` and then I get the last 156 tweets and then...

Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\twint.exe\__main__.py", line 7, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\twint\cli.py", line 305, in run_as_command
    main()
  File "c:\programdata\anaconda3\lib\site-packages\twint\cli.py", line 297, in main
    run.Search(c)
  File "c:\programdata\anaconda3\lib\site-packages\twint\run.py", line 327, in Search
    run(config, callback)
  File "c:\programdata\anaconda3\lib\site-packages\twint\run.py", line 226, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "c:\programdata\anaconda3\lib\asyncio\base_events.py", line 583, in run_until_complete
    return future.result()
  File "c:\programdata\anaconda3\lib\site-packages\twint\run.py", line 154, in main
    await task
  File "c:\programdata\anaconda3\lib\site-packages\twint\run.py", line 199, in run
    await self.tweets()
  File "c:\programdata\anaconda3\lib\site-packages\twint\run.py", line 145, in tweets
    await output.Tweets(tweet, self.config, self.conn)
  File "c:\programdata\anaconda3\lib\site-packages\twint\output.py", line 155, in Tweets
    await checkData(tweets, config, conn)
  File "c:\programdata\anaconda3\lib\site-packages\twint\output.py", line 142, in checkData
    _output(tweet, output, config)
  File "c:\programdata\anaconda3\lib\site-packages\twint\output.py", line 104, in _output
    print(output.replace('\n', ' '))
OSError: [WinError 87] El parámetro no es correcto

Then, two more tweets and stop...

Please I hope someone can help me, this is important for an academy research... Thanks!

**Comment by axyk-xi** [comment]
I have the same problem。
