### ISSUE TITLE
[QUESTION] c.User_id doesn't work

### ISSUE THREAD

**Issue by Cheryl520** [twintproject/twint#798]
### Initial Check

>Make sure you've checked the following:

- [] Python version is 3.7;
- [] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
twint-2.1.20
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran

I want to search for profile information using 'user_id', this is my code tried:

`u = twint.Config()
u.User_id = '2304166112'
u.User_full=True
user_filename = 'left_profile.csv'
u.Output = user_filename
u.Store_csv = True

twint.run.Lookup(u)`

### Description of Issue
I have the updated twint : twint-2.1.20

However I got this error messgae:
`ERROR:root:twint.run:Lookup:Unexpected exception occured.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\twint\run.py", line 292, in Lookup
    config.Username = get_event_loop().run_until_complete(get.Username(config.User_id))
  File "C:\ProgramData\Anaconda3\lib\site-packages\nest_asyncio.py", line 59, in run_until_complete
    return f.result()
  File "C:\ProgramData\Anaconda3\lib\asyncio\futures.py", line 181, in result
    raise self._exception
  File "C:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 249, in __step
    result = coro.send(None)
  File "C:\ProgramData\Anaconda3\lib\site-packages\twint\get.py", line 166, in Username
    return soup.find("a", "fn url alternate-context")["href"].replace("/", "")
TypeError: 'NoneType' object is not subscriptable`

Referring to  #629 , i searched for the twitter page : 
https://twitter.com/intent/user?user_id=2304166112
it indeed returned the profile of the user with this user_id, which means this user_id is valid.

What's the problem here? 

### Environment Details
>Using Windows + Jupyter Notebook

**Comment by pumpkinbox** [comment]
I have the same issue. On twint 2.1.20 and python 3.8.2. Using Windows + PyCharm.

**Comment by marcdumon** [comment]
The URL https://twitter.com/intent/user?user_id=2304166112 is valid indeed. I guess the "popup" asking to follow causes the problem. (See screenshot).
Unfortunately I don't know how to solve that.
![image](https://user-images.githubusercontent.com/7793950/84716395-3d229d80-af73-11ea-842c-1295de3d5fda.png)

**Comment by digitalPlayer1125** [comment]
Yeah, I found a temparory way around. Have a look at https://github.com/digitalPlayer1125/twitterUsernamefromUserID

**Comment by ozanbayram** [comment]
> The URL https://twitter.com/intent/user?user_id=2304166112 is valid indeed.
> But it shows a "popup" asking to follow and that's causing the problem I guess. (See screenshot).
> Unfortunately I don't know how to solve that.
> ![image](https://user-images.githubusercontent.com/7793950/84716395-3d229d80-af73-11ea-842c-1295de3d5fda.png)

https://twitter.com/i/user/2304166112 the url doesn't need valid

**Comment by Cheryl520** [comment]
> Yeah, I found a way around using selenium. Have a look at https://github.com/digitalPlayer1125/twitterUsernamefromUserID

Thanks for the solution! I'm currently using this to scrape username and it works well.

**Comment by romulocordova** [comment]
I'm getting this error. Using Python 3.9. Last version of Twint:

twint.run.Search(c)
  File "C:\Python39\lib\site-packages\twint\run.py", line 327, in Search
    run(config, callback)
  File "C:\Python39\lib\site-packages\twint\run.py", line 226, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "C:\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Python39\lib\site-packages\twint\run.py", line 154, in main
    await task
  File "C:\Python39\lib\site-packages\twint\run.py", line 164, in run
    self.config.Username = await get.Username(self.config.User_id)
  File "C:\Python39\lib\site-packages\twint\get.py", line 166, in Username
    return soup.find("a", "fn url alternate-context")["href"].replace("/", "")
TypeError: 'NoneType' object is not subscriptable

This is the code I'm running.

Has anybody solved this?

```
import twint

c = twint.Config()
c.User_id = 'xxxxxxx'
twint.run.Search(c)
```
