### ISSUE TITLE
Error time data

### ISSUE THREAD

**Issue by ShantiPrames** [twintproject/twint#812]
I have problem with value time data, can help me?

# Command Ran
import twint 
config = twint.Config()
config.Search = "Corona"
config.Lang = "id"
config.Limit = 100
config.Since = "2020-03–05 06:00:00"
config.Store_csv = True
config.Output = "custom_datasetcorona.csv"

twint.run.Search(config)

# Description of Issue
Traceback (most recent call last):
  File "D:/SKRIPSI/Dataset/DatasetCovid.py", line 13, in <module>
    twint.run.Search(config)
  File "C:\Users\Shanti\AppData\Roaming\Python\Python37\site-packages\twint\run.py", line 327, in Search
    run(config, callback)
  File "C:\Users\Shanti\AppData\Roaming\Python\Python37\site-packages\twint\run.py", line 226, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "C:\Users\Shanti\AppData\Roaming\Python\Python37\site-packages\twint\run.py", line 23, in __init__
    self.d = datelock.Set(self.config.Until, self.config.Since)
  File "C:\Users\Shanti\AppData\Roaming\Python\Python37\site-packages\twint\datelock.py", line 33, in Set
    d._since = datetime.datetime.strptime(convertToDateTime(Since), "%Y-%m-%d %H:%M:%S")
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\_strptime.py", line 359, in _strptime
    (data_string, format))
**ValueError: time data '2020-03–05 06:00:00' does not match format '%Y-%m-%d %H:%M:%S'**

Environment Details
Using Windows, python 3.7.5

**Comment by C00kie-** [comment]
Try put 1 instead of 0 in time.

Le jeu. 2 juil. 2020 à 07:18, ShantiPrames <notifications@github.com> a
écrit :

**Comment by C00kie-** [comment]
Also, try to run commands in the terminal and see if you have the same
issue.

Le jeu. 2 juil. 2020 à 07:18, ShantiPrames <notifications@github.com> a
écrit :
