### ISSUE TITLE
aiohttp_socks update breaks functions

### ISSUE THREAD

**Issue by june1994** [twintproject/twint#831]
The latest release of `aiohttp_socks` breaks the `twint` usage entirely. It is temporarilty fixed by using `aiohttp_socks<=0.4.1`, unless the code is reworked. The favorites grabbing function still is unusable. Cant get a wrap around how to fix that though

**Comment by TianshuangQiu** [comment]
Experiencing the same problem, how did you fix it using `aiohttp_socks<=0.4.1` ?

**Comment by alexgmm** [comment]
@TianshuangQiu clone the repository, change the version in the requirements file and proceed to install. Worked for me

**Comment by MiltonCalamaro** [comment]
Yes, clone the repository and change the file requirements.txt  , instead of aiohttp_socks to aiohttp_socks<=0.4.1

**Comment by Theo1996** [comment]
aiohttp_socks<=0.4.1 seems to fix it

**Comment by Theo1996** [comment]
twint -u foxopen32 --following --user-full <- works for some reason
E:\Desktop\twint\twint>twint -u foxopen32 < doesnt work

E:\Desktop\twint\twint>twint -u foxopen32 --following <-doesnt work
Traceback (most recent call last):
  File "e:\python\python38\lib\site-packages\twint\get.py", line 149, in Response
    return await response.text()
  File "e:\python\python38\lib\site-packages\aiohttp\client_reqrep.py", line 1009, in text
    await self.read()
  File "e:\python\python38\lib\site-packages\aiohttp\client_reqrep.py", line 973, in read
    self._body = await self.content.read()
  File "e:\python\python38\lib\site-packages\aiohttp\streams.py", line 358, in read
    block = await self.readany()
  File "e:\python\python38\lib\site-packages\aiohttp\streams.py", line 380, in readany
    await self._wait('readany')
  File "e:\python\python38\lib\site-packages\aiohttp\streams.py", line 296, in _wait
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python\Python38\Scripts\twint-script.py", line 11, in <module>
    load_entry_point('twint==2.1.20', 'console_scripts', 'twint')()
  File "e:\python\python38\lib\site-packages\twint\cli.py", line 311, in run_as_command
    main()
  File "e:\python\python38\lib\site-packages\twint\cli.py", line 274, in main
    run.Following(c)
  File "e:\python\python38\lib\site-packages\twint\run.py", line 322, in Following
    run(config)
  File "e:\python\python38\lib\site-packages\twint\run.py", line 283, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "e:\python\python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "e:\python\python38\lib\site-packages\twint\run.py", line 209, in main
    await task
  File "e:\python\python38\lib\site-packages\twint\run.py", line 247, in run
    await self.follow()
  File "e:\python\python38\lib\site-packages\twint\run.py", line 120, in follow
    await self.Feed()
  File "e:\python\python38\lib\site-packages\twint\run.py", line 45, in Feed
    response = await get.RequestUrl(self.config, self.init, headers=[("User-Agent", self.user_agent)])
  File "e:\python\python38\lib\site-packages\twint\get.py", line 119, in RequestUrl
    response = await Request(_url, params=params, connector=_connector, headers=headers)
  File "e:\python\python38\lib\site-packages\twint\get.py", line 143, in Request
    return await Response(session, url, params)
  File "e:\python\python38\lib\site-packages\twint\get.py", line 149, in Response
    return await response.text()
  File "e:\python\python38\lib\site-packages\async_timeout\__init__.py", line 45, in __exit__
    self._do_exit(exc_type)
  File "e:\python\python38\lib\site-packages\async_timeout\__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

**Comment by pielco11** [comment]
Thank you @june1994 for reporting this; I edited `requirements.txt` accordingly to the suggestions

**Comment by june1994** [comment]
Thanks @pielco11. Please see if the favorite functionality works. That issue seems open still and I am not able by any means
