### ISSUE TITLE
Error installing Twint via Pipenv

### ISSUE THREAD

**Issue by Jacksole** [twintproject/twint#845]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [x] Python version is 3.6;
- [x] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

### Description of Issue
>I received this message when I attempted to install twint:
Installing git+https://github.com/twintproject/twint.git#egg=twint…
Error:  An error occurred while installing git+https://github.com/twintproject/twint.git#egg=twint!
Error text: Collecting twint
  Cloning https://github.com/twintproject/twint.git to /tmp/pip-install-asznf3an/twint

WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
  Running command git clone -q https://github.com/twintproject/twint.git /tmp/pip-install-asznf3an/twint
    ERROR: Command errored out with exit status 1:
     command: /home/leaundre/.local/share/virtualenvs/Twint-AEKrNveo/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-asznf3an/twint/setup.py'"'"'; __file__='"'"'/tmp/pip-install-asznf3an/twint/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-hku68ijx
         cwd: /tmp/pip-install-asznf3an/twint/
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/leaundre/.local/share/virtualenvs/Twint-AEKrNveo/lib/python3.8/site-packages/setuptools/__init__.py", line 23, in <module>
        from setuptools.dist import Distribution
      File "/home/leaundre/.local/share/virtualenvs/Twint-AEKrNveo/lib/python3.8/site-packages/_virtualenv.py", line 89, in exec_module
        old(module)
      File "/home/leaundre/.local/share/virtualenvs/Twint-AEKrNveo/lib/python3.8/site-packages/setuptools/dist.py", line 34, in <module>
        from setuptools import windows_support
      File "/home/leaundre/.local/share/virtualenvs/Twint-AEKrNveo/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/usr/local/lib/python3.8/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ModuleNotFoundError: No module named '_ctypes'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

This is likely caused by a bug in twint. Report this to its maintainers.
✘ Installation Failed

When I ran pipenv install twint

Installing twint…
Error:  An error occurred while installing twint!
Error text: Could not fetch URL https://pypi.org/simple/twint/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/twint/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/twint/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/twint/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/twint/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/twint/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/twint/
ERROR: Could not find a version that satisfies the requirement twint (from -r /tmp/pipenv-6qwl0o3l-requirements/pipenv-zsxiucr1-requirement.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for twint (from -r /tmp/pipenv-6qwl0o3l-requirements/pipenv-zsxiucr1-requirement.txt (line 1))

✘ Installation Failed
### Environment Details
>WSL 1 Ubuntu 18..04

**Comment by Diksha02** [comment]
I am getting the same issue. I am trying to install on Windows 10.

```
Installing git+https://github.com/twintproject/twint.git#egg=twint...
Error:  An error occurred while installing git+https://github.com/twintproject/twint.git#egg=twint!
Error text: Collecting twint
  Cloning https://github.com/twintproject/twint.git to c:\users\diksha nigam\appdata\local\temp\pip-install-frretec9\twint_e52add0647d9479ba591c88da8129417
Collecting aiohttp
  Using cached aiohttp-3.7.3-cp39-cp39-win_amd64.whl (633 kB)
Collecting aiodns
  Using cached aiodns-2.0.0-py2.py3-none-any.whl (4.8 kB)
Collecting beautifulsoup4
  Using cached beautifulsoup4-4.9.3-py3-none-any.whl (115 kB)
Collecting cchardet
  Using cached cchardet-2.1.7-cp39-cp39-win_amd64.whl (115 kB)
Collecting dataclasses
  Using cached dataclasses-0.6-py3-none-any.whl (14 kB)
Collecting elasticsearch
  Using cached elasticsearch-7.10.1-py2.py3-none-any.whl (322 kB)
Collecting pysocks
  Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
Collecting pandas
  Using cached pandas-1.2.1-cp39-cp39-win_amd64.whl (9.3 MB)
Collecting aiohttp_socks
  Using cached aiohttp_socks-0.5.5-py3-none-any.whl (9.1 kB)
Collecting schedule
  Using cached schedule-1.0.0-py2.py3-none-any.whl (9.0 kB)
Collecting geopy
  Using cached geopy-2.1.0-py3-none-any.whl (112 kB)
Collecting fake-useragent
  Using cached fake_useragent-0.1.11-py3-none-any.whl
Collecting googletransx
  Using cached googletransx-2.4.2-py3-none-any.whl
Collecting pycares>=3.0.0
  Using cached pycares-3.1.1.tar.gz (233 kB)
Requirement already satisfied: cffi>=1.5.0 in c:\users\diksha nigam\.virtualenvs\twint-1urpsopn\lib\site-packages (from pycares>=3.0.0->aiodns->twint->-r c:\users\diksha nigam\appdata\local\temp\pipenv-j0u836zm-requirements\pipenv-b07n3r6o-requirement.txt (line 1)) (1.14.4)
Requirement already satisfied: pycparser in c:\users\diksha nigam\.virtualenvs\twint-1urpsopn\lib\site-packages (from cffi>=1.5.0->pycares>=3.0.0->aiodns->twint->-r c:\users\diksha nigam\appdata\local\temp\pipenv-j0u836zm-requirements\pipenv-b07n3r6o-requirement.txt (line 1)) (2.20)
Requirement already satisfied: attrs>=17.3.0 in c:\users\diksha nigam\.virtualenvs\twint-1urpsopn\lib\site-packages (from aiohttp->twint->-r c:\users\diksha nigam\appdata\local\temp\pipenv-j0u836zm-requirements\pipenv-b07n3r6o-requirement.txt (line 1)) (20.3.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\diksha nigam\.virtualenvs\twint-1urpsopn\lib\site-packages (from aiohttp->twint->-r c:\users\diksha nigam\appdata\local\temp\pipenv-j0u836zm-requirements\pipenv-b07n3r6o-requirement.txt (line 1)) (5.1.0)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\diksha nigam\.virtualenvs\twint-1urpsopn\lib\site-packages (from aiohttp->twint->-r c:\users\diksha nigam\appdata\local\temp\pipenv-j0u836zm-requirements\pipenv-b07n3r6o-requirement.txt (line 1)) (1.6.3)
Requirement already satisfied: typing-extensions>=3.6.5 in c:\users\diksha nigam\.virtualenvs\twint-1urpsopn\lib\site-packages (from aiohttp->twint->-r c:\users\diksha nigam\appdata\local\temp\pipenv-j0u836zm-requirements\pipenv-b07n3r6o-requirement.txt (line 1)) (3.7.4.3)
Requirement already satisfied: async-timeout<4.0,>=3.0 in c:\users\diksha nigam\.virtualenvs\twint-1urpsopn\lib\site-packages (from aiohttp->twint->-r c:\users\diksha nigam\appdata\local\temp\pipenv-j0u836zm-requirements\pipenv-b07n3r6o-requirement.txt (line 1)) (3.0.1)
Requirement already satisfied: chardet<4.0,>=2.0 in c:\users\diksha nigam\.virtualenvs\twint-1urpsopn\lib\site-packages (from aiohttp->twint->-r c:\users\diksha nigam\appdata\local\temp\pipenv-j0u836zm-requirements\pipenv-b07n3r6o-requirement.txt (line 1)) (3.0.4)
Requirement already satisfied: idna>=2.0 in c:\users\diksha nigam\.virtualenvs\twint-1urpsopn\lib\site-packages (from yarl<2.0,>=1.0->aiohttp->twint->-r c:\users\diksha nigam\appdata\local\temp\pipenv-j0u836zm-requirements\pipenv-b07n3r6o-requirement.txt (line 1)) (2.10)
Requirement already satisfied: python-socks[asyncio]>=1.0.1 in c:\users\diksha nigam\.virtualenvs\twint-1urpsopn\lib\site-packages (from aiohttp_socks->twint->-r c:\users\diksha nigam\appdata\local\temp\pipenv-j0u836zm-requirements\pipenv-b07n3r6o-requirement.txt (line 1)) (1.2.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\diksha nigam\.virtualenvs\twint-1urpsopn\lib\site-packages (from beautifulsoup4->twint->-r c:\users\diksha nigam\appdata\local\temp\pipenv-j0u836zm-requirements\pipenv-b07n3r6o-requirement.txt (line 1)) (2.1)
Requirement already satisfied: certifi in c:\users\diksha nigam\.virtualenvs\twint-1urpsopn\lib\site-packages (from elasticsearch->twint->-r c:\users\diksha nigam\appdata\local\temp\pipenv-j0u836zm-requirements\pipenv-b07n3r6o-requirement.txt (line 1)) (2020.12.5)
Requirement already satisfied: urllib3<2,>=1.21.1 in c:\users\diksha nigam\.virtualenvs\twint-1urpsopn\lib\site-packages (from elasticsearch->twint->-r c:\users\diksha nigam\appdata\local\temp\pipenv-j0u836zm-requirements\pipenv-b07n3r6o-requirement.txt (line 1)) (1.26.3)
Collecting geographiclib<2,>=1.49
  Using cached geographiclib-1.50-py3-none-any.whl (38 kB)
Requirement already satisfied: requests in c:\users\diksha nigam\.virtualenvs\twint-1urpsopn\lib\site-packages (from googletransx->twint->-r c:\users\diksha nigam\appdata\local\temp\pipenv-j0u836zm-requirements\pipenv-b07n3r6o-requirement.txt (line 1)) (2.25.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\diksha nigam\.virtualenvs\twint-1urpsopn\lib\site-packages (from pandas->twint->-r c:\users\diksha nigam\appdata\local\temp\pipenv-j0u836zm-requirements\pipenv-b07n3r6o-requirement.txt (line 1)) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in c:\users\diksha nigam\.virtualenvs\twint-1urpsopn\lib\site-packages (from pandas->twint->-r c:\users\diksha nigam\appdata\local\temp\pipenv-j0u836zm-requirements\pipenv-b07n3r6o-requirement.txt (line 1)) (2021.1)
Collecting numpy>=1.16.5
  Using cached numpy-1.20.0-cp39-cp39-win_amd64.whl (13.7 MB)
Requirement already satisfied: six>=1.5 in c:\users\diksha nigam\.virtualenvs\twint-1urpsopn\lib\site-packages (from python-dateutil>=2.7.3->pandas->twint->-r c:\users\diksha nigam\appdata\local\temp\pipenv-j0u836zm-requirements\pipenv-b07n3r6o-requirement.txt (line 1)) (1.15.0)
Building wheels for collected packages: twint, pycares
  Building wheel for twint (setup.py): started
  Building wheel for twint (setup.py): finished with status 'done'
  Created wheel for twint: filename=twint-2.1.21-py3-none-any.whl size=39032 sha256=94a44a54693f2c30514ed62d9a9f8da03b7f4d84b7057769ebda7aa5bc43696c
  Stored in directory: C:\Users\Diksha Nigam\AppData\Local\Temp\pip-ephem-wheel-cache-ah38_qg0\wheels\0a\0f\af\9446ff4dfa9536d5e4f5a8b1e77fd9ef4f34694d3e30b7da57
  Building wheel for pycares (setup.py): started
  Building wheel for pycares (setup.py): finished with status 'error'
  Running setup.py clean for pycares
Successfully built twint
Failed to build pycares
Installing collected packages: pycares, numpy, geographiclib, aiohttp, schedule, pysocks, pandas, googletransx, geopy, fake-useragent, elasticsearch, dataclasses, cchardet, beautifulsoup4, aiohttp-socks, aiodns, twint
    Running setup.py install for pycares: started
    Running setup.py install for pycares: finished with status 'error'

  Running command git clone -q https://github.com/twintproject/twint.git 'C:\Users\Diksha Nigam\AppData\Local\Temp\pip-install-frretec9\twint_e52add0647d9479ba591c88da8129417'
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Diksha Nigam\.virtualenvs\twint-1UrpSOpN\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Diksha Nigam\\AppData\\Local\\Temp\\pip-install-frretec9\\pycares_285e10b8de3249a2a9b8539978e4b7ab\\setup.py'"'"'; __file__='"'"'C:\\Users\\Diksha Nigam\\AppData\\Local\\Temp\\pip-install-frretec9\\pycares_285e10b8de3249a2a9b8539978e4b7ab\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Diksha Nigam\AppData\Local\Temp\pip-wheel-hsglj_em'
       cwd: C:\Users\Diksha Nigam\AppData\Local\Temp\pip-install-frretec9\pycares_285e10b8de3249a2a9b8539978e4b7ab\
  Complete output (19 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\pycares
  copying src\pycares\errno.py -> build\lib.win-amd64-3.9\pycares
  copying src\pycares\utils.py -> build\lib.win-amd64-3.9\pycares
  copying src\pycares\_version.py -> build\lib.win-amd64-3.9\pycares
  copying src\pycares\__init__.py -> build\lib.win-amd64-3.9\pycares
  copying src\pycares\__main__.py -> build\lib.win-amd64-3.9\pycares
  warning: build_py: byte-compiling is disabled, skipping.

  running build_ext
  generating cffi module 'build\\temp.win-amd64-3.9\\Release\\_cares.c'
  creating build\temp.win-amd64-3.9
  creating build\temp.win-amd64-3.9\Release
  building '_cares' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for pycares
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Diksha Nigam\.virtualenvs\twint-1UrpSOpN\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Diksha Nigam\\AppData\\Local\\Temp\\pip-install-frretec9\\pycares_285e10b8de3249a2a9b8539978e4b7ab\\setup.py'"'"'; __file__='"'"'C:\\Users\\Diksha Nigam\\AppData\\Local\\Temp\\pip-install-frretec9\\pycares_285e10b8de3249a2a9b8539978e4b7ab\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Diksha Nigam\AppData\Local\Temp\pip-record-h50xau0e\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Diksha Nigam\.virtualenvs\twint-1UrpSOpN\include\site\python3.9\pycares'
         cwd: C:\Users\Diksha Nigam\AppData\Local\Temp\pip-install-frretec9\pycares_285e10b8de3249a2a9b8539978e4b7ab\
    Complete output (19 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\pycares
    copying src\pycares\errno.py -> build\lib.win-amd64-3.9\pycares
    copying src\pycares\utils.py -> build\lib.win-amd64-3.9\pycares
    copying src\pycares\_version.py -> build\lib.win-amd64-3.9\pycares
    copying src\pycares\__init__.py -> build\lib.win-amd64-3.9\pycares
    copying src\pycares\__main__.py -> build\lib.win-amd64-3.9\pycares
    warning: build_py: byte-compiling is disabled, skipping.

    running build_ext
    generating cffi module 'build\\temp.win-amd64-3.9\\Release\\_cares.c'
    creating build\temp.win-amd64-3.9
    creating build\temp.win-amd64-3.9\Release
    building '_cares' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Diksha Nigam\.virtualenvs\twint-1UrpSOpN\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Diksha Nigam\\AppData\\Local\\Temp\\pip-install-frretec9\\pycares_285e10b8de3249a2a9b8539978e4b7ab\\setup.py'"'"'; __file__='"'"'C:\\Users\\Diksha Nigam\\AppData\\Local\\Temp\\pip-install-frretec9\\pycares_285e10b8de3249a2a9b8539978e4b7ab\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Diksha Nigam\AppData\Local\Temp\pip-record-h50xau0e\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Diksha Nigam\.virtualenvs\twint-1UrpSOpN\include\site\python3.9\pycares' Check the logs for full command output.

Installation Failed
```

**Comment by plufz** [comment]
Did you manage to solve this? I have the same issue.

**Comment by 0xSimbo** [comment]
I'm having the same issue, did anyone find a workaround or different library?
