### ISSUE TITLE
Error when use SOCKS5 proxy

### ISSUE THREAD

**Issue by markowanga** [twintproject/twint#847]
In latest version I have this error:

```
marcinwatroba@MacBook-Pro-Marcin ~ % twint -u realDonaldTrump --user-full --proxy-type Socks5 --proxy-port 9050 --proxy-host localhost
ERROR:root:twint.run:Lookup:Unexpected exception occured.
Traceback (most recent call last):
  File "/Users/marcinwatroba/anaconda3/lib/python3.7/site-packages/twint/run.py", line 352, in Lookup
    get_event_loop().run_until_complete(get.User(url, config, db.Conn(config.Database)))
  File "/Users/marcinwatroba/anaconda3/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/Users/marcinwatroba/anaconda3/lib/python3.7/site-packages/twint/get.py", line 180, in User
    _connector = get_connector(config)
  File "/Users/marcinwatroba/anaconda3/lib/python3.7/site-packages/twint/get.py", line 75, in get_connector
    rdns=True)
  File "/Users/marcinwatroba/anaconda3/lib/python3.7/site-packages/aiohttp_socks/connector.py", line 80, in __init__
    super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'socks_ver'
Traceback (most recent call last):
  File "/Users/marcinwatroba/anaconda3/bin/twint", line 8, in <module>
    sys.exit(run_as_command())
  File "/Users/marcinwatroba/anaconda3/lib/python3.7/site-packages/twint/cli.py", line 311, in run_as_command
    main()
  File "/Users/marcinwatroba/anaconda3/lib/python3.7/site-packages/twint/cli.py", line 301, in main
    run.Lookup(c)
  File "/Users/marcinwatroba/anaconda3/lib/python3.7/site-packages/twint/run.py", line 352, in Lookup
    get_event_loop().run_until_complete(get.User(url, config, db.Conn(config.Database)))
  File "/Users/marcinwatroba/anaconda3/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/Users/marcinwatroba/anaconda3/lib/python3.7/site-packages/twint/get.py", line 180, in User
    _connector = get_connector(config)
  File "/Users/marcinwatroba/anaconda3/lib/python3.7/site-packages/twint/get.py", line 75, in get_connector
    rdns=True)
  File "/Users/marcinwatroba/anaconda3/lib/python3.7/site-packages/aiohttp_socks/connector.py", line 80, in __init__
    super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'socks_ver'
```

Checked in Python and Command line on Linux and MacOS.

**Comment by pielco11** [comment]
MAy you update with the following command? `pip3 install --user --upgrade git+https://github.com/twintproject/twint.git@origin/master#egg=twint` , recently an issue about that library has been reported and a pull request merged

**Comment by markowanga** [comment]
I have version 2.1.21

**Comment by pielco11** [comment]
Hmm cool; `pip3 show aiohttp_socks` ? Expect to see `Version: 0.4.1 `

**Comment by markowanga** [comment]
```
(base) marcinwatroba@DataScienceServer:~$ docker run -it --rm python:3.7 bash
root@732c2476065c:/# pip install -q git+https://github.com/twintproject/twint.git@origin/master#egg=twint
  WARNING: Did not find branch or tag 'origin/master', assuming revision or ref.
WARNING: You are using pip version 20.2; however, version 20.2.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
root@732c2476065c:/# pip show aiohttp_socks
Name: aiohttp-socks
Version: 0.5.3
Summary: Proxy connector for aiohttp
Home-page: https://github.com/romis2012/aiohttp-socks
Author: Roman Snegirev
Author-email: snegiryev@gmail.com
License: Apache 2
Location: /usr/local/lib/python3.7/site-packages
Requires: attrs, aiohttp
Required-by: twint
root@732c2476065c:/# 
```

**Comment by pielco11** [comment]
As you see, you have `0.5.3`. You have just to install the specific version and you are ready to go

**Comment by markowanga** [comment]
I have still problem

code:
```
import twint
import aiohttp_socks

print('twint version: ' + twint.__version__)
print('aiohttp_socks version: ' + aiohttp_socks.__version__)

twint_config = twint.Config()
twint_config.Store_object = False
twint_config.Hide_output = True
twint_config.Proxy_host = '127.0.0.1'
twint_config.Proxy_port = 9050
twint_config.Proxy_type = 'socks5'
twint_config.Database = 'db_file_path.db'
twint_config.Username = 'realDonaldTrump'
twint.run.Lookup(twint_config)
```

output:
```
twint version: 2.1.21
aiohttp_socks version: 0.4.1
[+] Inserting into Database: db_file_path.db
ERROR:root:twint.run:Lookup:Unexpected exception occured.
Traceback (most recent call last):
  File "/Users/marcinwatroba/.local/lib/python3.7/site-packages/twint/run.py", line 352, in Lookup
    get_event_loop().run_until_complete(get.User(url, config, db.Conn(config.Database)))
  File "/Users/marcinwatroba/anaconda3/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/Users/marcinwatroba/.local/lib/python3.7/site-packages/twint/get.py", line 180, in User
    _connector = get_connector(config)
  File "/Users/marcinwatroba/.local/lib/python3.7/site-packages/twint/get.py", line 75, in get_connector
    rdns=True)
  File "/Users/marcinwatroba/anaconda3/lib/python3.7/site-packages/aiohttp_socks/connector.py", line 85, in __init__
    super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'socks_ver'
Traceback (most recent call last):
  File "/Users/marcinwatroba/Desktop/Samorozwój/playground/main.py", line 15, in <module>
    twint.run.Lookup(twint_config)
  File "/Users/marcinwatroba/.local/lib/python3.7/site-packages/twint/run.py", line 352, in Lookup
    get_event_loop().run_until_complete(get.User(url, config, db.Conn(config.Database)))
  File "/Users/marcinwatroba/anaconda3/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/Users/marcinwatroba/.local/lib/python3.7/site-packages/twint/get.py", line 180, in User
    _connector = get_connector(config)
  File "/Users/marcinwatroba/.local/lib/python3.7/site-packages/twint/get.py", line 75, in get_connector
    rdns=True)
  File "/Users/marcinwatroba/anaconda3/lib/python3.7/site-packages/aiohttp_socks/connector.py", line 85, in __init__
    super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'socks_ver'

Process finished with exit code 1
```

**Comment by pielco11** [comment]
well it seems that you still have the issue, maybe you are importing the wrong package? I have the same setup and works

**Comment by Tyoukakutei-0126** [comment]
Hello, I have the same problem as yours. Now I have solved it as follow:
If you use the SSR or VPN, you should add these codings:
c.Proxy_host = " " # find it in your SSR or VPN
c.Proxy_port =      # find it in your SSR or VPN, the type is int
c.Proxy_type = " " # find it in your SSR or VPN
One thing you should pay attention to is that the proxy_host and proxy_port is consistent with the procy_type. If I use "http" as proxy_type, the proxy_port and proxy_host must belong to "http".
I hope it can help you!

**Comment by pielco11** [comment]
If you use a VPN, there's no need to configure proxy options

**Comment by alirezaafzalaghaei** [comment]
I faced the same problem today. since twint 2.1.20 didn't work, I upgraded to 2.1.21. After upgrade, it throws

```TypeError: __init__() got an unexpected keyword argument 'socks_ver'```

I tested "aiohttp-socks-0.3.9", "aiohttp-socks-0.4.1" and "aiohttp-socks-0.5.3". None of them worked :((

+ additional info: I use tor proxy as follows:

```
c.Proxy_host = 'tor'
c.Tor_control_port = 9051
c.Tor_control_password = "password"
```

**Comment by lmeyerov** [comment]
Fixed in https://github.com/twintproject/twint/pull/914 . Until merged, you can do `pip install git+https://github.com/lmeyerov/twint.git@patch-1#egg=twint`
