### ISSUE TITLE
Cannot find twitter account with name = jack

### ISSUE THREAD

**Issue by elamje** [twintproject/twint#862]
I've tried upgrading, etc, but just getting this issue over and over with every account I try. 

### Command Ran
twint -u jack --since 2013-05-01 -o jack_20130501_tweets.csv --csv

### Description of Issue
```twint -u jack --since 2013-05-01 -o jack_20130501_tweets.csv --csv
CRITICAL:root:twint.get:User:'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/local/bin/twint", line 11, in <module>
    load_entry_point('twint==2.1.20', 'console_scripts', 'twint')()
  File "/Library/Python/3.7/site-packages/twint/cli.py", line 305, in run_as_command
    main()
  File "/Library/Python/3.7/site-packages/twint/cli.py", line 297, in main
    run.Search(c)
  File "/Library/Python/3.7/site-packages/twint/run.py", line 329, in Search
    run(config, callback)
  File "/Library/Python/3.7/site-packages/twint/run.py", line 228, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/Library/Python/3.7/site-packages/twint/run.py", line 154, in main
    await task
  File "/Library/Python/3.7/site-packages/twint/run.py", line 171, in run
    raise ValueError("Cannot find twitter account with name = " + self.config.Username)
ValueError: Cannot find twitter account with name = jack```

### Environment Details

Mac OS 10.13.5, Terminal

**Comment by THEDARKK** [comment]
Hello, Same problem what is the solution?
thank you

**Comment by Lxhnnn** [comment]
I also had this problem today

**Comment by hcanalesmx** [comment]
Having the same problem

**Comment by pielco11** [comment]
Twint does a check to extract the user ID, and this seems to be broken.

Just compose your query in a different way as follows `twint -s "from:jack" --since 2013-05-01 -o jack_20130501_tweets.csv --csv`
