### ISSUE TITLE
[BUG] Current version of twint cannot get tweets from a user

### ISSUE THREAD

**Issue by adulau** [twintproject/twint#866]
# Issue Template

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [X] Python version is 3.6;
- [X] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [X] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran

adulau@dobbertin:~$ .local/bin/twint -u CookieDeca
CRITICAL:root:twint.get:User:'NoneType' object is not subscriptable
Traceback (most recent call last):
  File ".local/bin/twint", line 8, in <module>
    sys.exit(run_as_command())
  File "/home/adulau/.local/lib/python3.6/site-packages/twint/cli.py", line 311, in run_as_command
    main()
  File "/home/adulau/.local/lib/python3.6/site-packages/twint/cli.py", line 303, in main
    run.Search(c)
  File "/home/adulau/.local/lib/python3.6/site-packages/twint/run.py", line 384, in Search
    run(config, callback)
  File "/home/adulau/.local/lib/python3.6/site-packages/twint/run.py", line 283, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/adulau/.local/lib/python3.6/site-packages/twint/run.py", line 209, in main
    await task
  File "/home/adulau/.local/lib/python3.6/site-packages/twint/run.py", line 226, in run
    raise ValueError("Cannot find twitter account with name = " + self.config.Username)
ValueError: Cannot find twitter account with name = CookieDeca

### Description of Issue

Library or twint cannot get anymore the tweets from a specify user. This worked the 13th August 2020 and starting from Today, it seems Twitter changed something.

### Environment Details

~~~
adulau@dobbertin:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
~~~

**Comment by adulau** [comment]
FYI, this is not affecting searches.

**Comment by adulau** [comment]
Related to #863 863

**Comment by pielco11** [comment]
Solution is 863, closing
