### ISSUE TITLE
AttributeError: module 'pandas' has no attribute 'plotting'

### ISSUE THREAD

**Issue by aoighost** [twintproject/twint#910]
- [x] Python version is 3.7;
- [x] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.
twint -u aoighost

### Description of Issue

Traceback (most recent call last):
  File "/usr/local/bin/twint", line 5, in <module>
    from twint.cli import run_as_command
  File "/usr/local/lib/python3.7/site-packages/twint/__init__.py", line 14, in <module>
    from . import run
  File "/usr/local/lib/python3.7/site-packages/twint/run.py", line 4, in <module>
    from . import datelock, feed, get, output, verbose, storage
  File "/usr/local/lib/python3.7/site-packages/twint/get.py", line 15, in <module>
    from .output import Tweets, Users
  File "/usr/local/lib/python3.7/site-packages/twint/output.py", line 6, in <module>
    from .storage import db, elasticsearch, write, panda
  File "/usr/local/lib/python3.7/site-packages/twint/storage/panda.py", line 2, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.7/site-packages/pandas/__init__.py", line 52, in <module>
    from pandas.core.api import (
  File "/usr/local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.groupby import Grouper, NamedAgg
  File "/usr/local/lib/python3.7/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import DataFrameGroupBy, NamedAgg, SeriesGroupBy
  File "/usr/local/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 57, in <module>
    from pandas.core.aggregation import (
  File "/usr/local/lib/python3.7/site-packages/pandas/core/aggregation.py", line 27, in <module>
    from pandas.core.series import FrameOrSeriesUnion, Series
  File "/usr/local/lib/python3.7/site-packages/pandas/core/series.py", line 139, in <module>
    class Series(base.IndexOpsMixin, generic.NDFrame):
  File "/usr/local/lib/python3.7/site-packages/pandas/core/series.py", line 4974, in Series
    plot = CachedAccessor("plot", pandas.plotting.PlotAccessor)
AttributeError: module 'pandas' has no attribute 'plotting'

### Environment Details
linux alpine docker
https://github.com/aoighost/public_shuffleapps for https://github.com/frikky/Shuffle

to get the debug output that's showing the error follow these instructions

1. Check logs of orborus -> click execute workflow -> find the worker that's being executed -> docker logs -f <id>
2. Check logs of worker -> find the app you're looking for being executed -> docker logs -f <id>

Container names always looks like that, not e.g. worker-<uuid>. May be different on other platforms tho, not sure

**Comment by webcoderz** [comment]
sounds like need to upgrade pandas to a version that has pandas plotting
