### ISSUE TITLE
ModuleNotFoundError: No module named 'dataclasses'

### ISSUE THREAD

**Issue by DavidPerea** [twintproject/twint#916]
I already had Twin installed on my computer (windows) and it worked without problems, but I wanted to update using `pip3 install --user --upgrade git + https: //github.com/twintproject/twint.git@origin/master#egg=twint` but when doing any extraction of tweets it returns this:

`Traceback (most recent call last):
  File "c:\programdata\anaconda3\si\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\si\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\si\Scripts\twint.exe\__main__.py", line 5, in <module>
  File "C:\Users\david\AppData\Roaming\Python\Python36\site-packages\twint\__init__.py", line 12, in <module>
    from .config import Config
  File "C:\Users\david\AppData\Roaming\Python\Python36\site-packages\twint\config.py", line 1, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'`

Can you help me?

**Comment by LinqLover** [comment]
Related to #887.

**Comment by LinqLover** [comment]
Could you give a complete console example please?

**Comment by DavidPerea** [comment]
I don't know how to fix it. This is my console:

![image](https://user-images.githubusercontent.com/33260230/93594165-9c021380-f9b5-11ea-9e39-e88e701da34c.png)

What should I run, please?

**Comment by LinqLover** [comment]
Welcome to GitHub, please don't share screenshots but copy the text from your console, thanks :)

How did you install twint? Which version do you use?

**Comment by DavidPerea** [comment]
Excuse me, I didn't know. I will not share the screen again.

Twint install it using the following command:` pip3 install --user --upgrade git + https: //github.com/twintproject/twint.git@origin/master#egg=twint`

**Comment by yunusemrecatalcam** [comment]
Did you try to install it? If not, let's do it!

**Comment by LinqLover** [comment]
@DavidPerea Can you resolve the problem by removing the `--upgrade` flag from your command?

```bash
pip3 install --user git+https://github.com/twintproject/twint.git@origin/master#egg=twint
```

If this does not help, you could manually install the dependency like this, which however I would classify as a workaround:

```bash
pip3 install --user dataclasses
```

**Comment by DavidPerea** [comment]
I have installed again as @LinqLover indicate me. It returns the following:
```
Requirement already satisfied: twint from git+https://github.com/twintproject/twint.git@origin/master#egg=twint in c:\programdata\anaconda3\si\lib\site-packages (2.1.19)
Requirement already satisfied: elasticsearch in c:\programdata\anaconda3\si\lib\site-packages (from twint) (6.2.0)
Requirement already satisfied: googletransx in c:\programdata\anaconda3\si\lib\site-packages (from twint) (2.4.2)
Requirement already satisfied: aiohttp-socks in c:\programdata\anaconda3\si\lib\site-packages (from twint) (0.1.9)
Requirement already satisfied: aiohttp in c:\programdata\anaconda3\si\lib\site-packages (from twint) (3.1.3)
Requirement already satisfied: aiodns in c:\programdata\anaconda3\si\lib\site-packages (from twint) (1.1.1)
Requirement already satisfied: beautifulsoup4 in c:\programdata\anaconda3\si\lib\site-packages (from twint) (4.6.0)
Requirement already satisfied: pysocks in c:\programdata\anaconda3\si\lib\site-packages (from twint) (1.6.7)
Requirement already satisfied: geopy in c:\programdata\anaconda3\si\lib\site-packages (from twint) (1.17.0)
Requirement already satisfied: fake-useragent in c:\users\david\appdata\roaming\python\python36\site-packages (from twint) (0.1.10)
Requirement already satisfied: schedule in c:\programdata\anaconda3\si\lib\site-packages (from twint) (0.5.0)
Requirement already satisfied: pandas in c:\programdata\anaconda3\si\lib\site-packages (from twint) (0.20.3)
Requirement already satisfied: cchardet in c:\programdata\anaconda3\si\lib\site-packages (from twint) (2.1.1)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\programdata\anaconda3\si\lib\site-packages (from elasticsearch->twint) (1.22)
Requirement already satisfied: requests in c:\programdata\anaconda3\si\lib\site-packages (from googletransx->twint) (2.18.4)
Requirement already satisfied: attrs>=17.3.0 in c:\programdata\anaconda3\si\lib\site-packages (from aiohttp->twint) (17.4.0)
Requirement already satisfied: multidict<5.0,>=4.0 in c:\programdata\anaconda3\si\lib\site-packages (from aiohttp->twint) (4.2.0)
Requirement already satisfied: chardet<4.0,>=2.0 in c:\programdata\anaconda3\si\lib\site-packages (from aiohttp->twint) (3.0.4)
Requirement already satisfied: idna-ssl>=1.0 in c:\programdata\anaconda3\si\lib\site-packages (from aiohttp->twint) (1.0.1)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\programdata\anaconda3\si\lib\site-packages (from aiohttp->twint) (1.1.1)
Requirement already satisfied: async-timeout<3.0,>=1.2 in c:\programdata\anaconda3\si\lib\site-packages (from aiohttp->twint) (2.0.1)
Requirement already satisfied: pycares>=1.0.0 in c:\programdata\anaconda3\si\lib\site-packages (from aiodns->twint) (2.3.0)
Requirement already satisfied: geographiclib<2,>=1.49 in c:\programdata\anaconda3\si\lib\site-packages (from geopy->twint) (1.49)
Requirement already satisfied: python-dateutil>=2 in c:\programdata\anaconda3\si\lib\site-packages (from pandas->twint) (2.6.1)
Requirement already satisfied: pytz>=2011k in c:\programdata\anaconda3\si\lib\site-packages (from pandas->twint) (2017.2)
Requirement already satisfied: numpy>=1.7.0 in c:\programdata\anaconda3\si\lib\site-packages (from pandas->twint) (1.13.1)
Requirement already satisfied: idna<2.7,>=2.5 in c:\programdata\anaconda3\si\lib\site-packages (from requests->googletransx->twint) (2.6)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\si\lib\site-packages (from requests->googletransx->twint) (2018.1.18)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\si\lib\site-packages (from python-dateutil>=2->pandas->twint) (1.10.0)
Building wheels for collected packages: twint
Exception:
Traceback (most recent call last):
  File "c:\programdata\anaconda3\si\lib\site-packages\pip\_internal\basecommand.py", line 228, in main
    status = self.run(options, args)
  File "c:\programdata\anaconda3\si\lib\site-packages\pip\_internal\commands\install.py", line 305, in run
    session=session, autobuilding=True
  File "c:\programdata\anaconda3\si\lib\site-packages\pip\_internal\wheel.py", line 773, in build
    python_tag=python_tag,
  File "c:\programdata\anaconda3\si\lib\site-packages\pip\_internal\wheel.py", line 633, in _build_one
    python_tag=python_tag)
  File "c:\programdata\anaconda3\si\lib\site-packages\pip\_internal\wheel.py", line 637, in _build_one_inside_env
    if self.__build_one(req, temp_dir.path, python_tag=python_tag):
  File "c:\programdata\anaconda3\si\lib\site-packages\pip\_internal\wheel.py", line 663, in __build_one
    base_args = self._base_setup_args(req)
  File "c:\programdata\anaconda3\si\lib\site-packages\pip\_internal\wheel.py", line 659, in _base_setup_args
    SETUPTOOLS_SHIM % req.setup_py
  File "c:\programdata\anaconda3\si\lib\site-packages\pip\_internal\req\req_install.py", line 415, in setup_py
    assert self.source_dir, "No source dir for %s" % self
AssertionError: No source dir for twint from git+https://github.com/twintproject/twint.git@origin/master#egg=twint in c:\programdata\anaconda3\si\lib\site-packages
```
From "Expection" the text is red. 
Now when I put a Twint command like this: `twint -u malaga` ,  and with another any command it returns this:
`CRITICAL:root:twint.get:User:'NoneType' object is not subscriptable
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
CRITICAL:root:twint.run:Twint:Feed:Tweets_known_error:Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0) [x] run.Feed
[!] if get this error but you know for sure that more tweets exist, please open an issue and we will investigate it!`

What does it mean?

**Comment by LinqLover** [comment]
Hm, I would rather say this sounds like a pip error. Possibly something like pypa/pip#5251?
Which pip version are you using? Can you clean up your package caches for anaconda and try again?

**Comment by DavidPerea** [comment]
I am using version 10 of pi. The problem is that I want to update it but I have no way. I have tried both `python -m pip install --upgrade pip` and `-m pip install pip == 20.2.3` and it returns the following:

```
Collecting pip == 20.2.3
   Using cached https://files.pythonhosted.org/packages/4e/5f/528232275f6509b1fff703c9280e58951a81abe24640905de621c9f81839/pip-20.2.3-py2.py3-none-any.whl
Installing collected packages: pip
   Found existing installation: pip 10.0.0
     Uninstalling pip-10.0.0:
```

You are using pip version 10.0.0, however version 20.2.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

It seems that the problem is using the pip version 10, right?

**Comment by LinqLover** [comment]
> It seems that the problem is using the pip version 10, right?

I cannot promise you that it will resolve your problem, but this would probably be a good idea.

**Comment by DavidPerea** [comment]
Do you know how I can solve the problem of updating pip version 10? @LinqLover  Sorry for the inconvenience, this is being difficult for me.

**Comment by LinqLover** [comment]
Just do what the warning says:

> You should consider upgrading via the `python -m pip install --upgrade pip` command.

**Comment by DavidPerea** [comment]
I do that but it doesn't update, it returns the following:

```
Collecting pip
  Using cached https://files.pythonhosted.org/packages/4e/5f/528232275f6509b1fff703c9280e58951a81abe24640905de621c9f81839/pip-20.2.3-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 10.0.0
    Uninstalling pip-10.0.0:

You are using pip version 10.0.0, however version 20.2.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

**Comment by LinqLover** [comment]
Could you please share a complete console output, including your input? Does the execution really stop right after the uninstalling message? Please also try to set the `--user` flag.

**Comment by DavidPerea** [comment]
I am desperate, because I only get mistakes. Once solved the version of the pip. I have uninstalled pyhton and reinstalled it. I already have the pip updated.

But now I have installed twint and I get the following warning on download: `WARNING: Did not find branch or tag 'origin/master', assuming revision or ref.` . Here I indicate everything that seems to me:

```
Collecting twint
  Cloning https://github.com/twintproject/twint.git (to revision origin/master) to c:\users\david\appdata\local\temp\pip-install-v1rj0_b9\twint
  Running command git clone -q https://github.com/twintproject/twint.git 'C:\Users\david\AppData\Local\Temp\pip-install-v1rj0_b9\twint'
  WARNING: Did not find branch or tag 'origin/master', assuming revision or ref.
  Running command git checkout -q origin/master
Requirement already satisfied, skipping upgrade: aiohttp in c:\users\david\appdata\roaming\python\python38\site-packages (from twint) (3.6.2)
Requirement already satisfied, skipping upgrade: aiodns in c:\users\david\appdata\roaming\python\python38\site-packages (from twint) (2.0.0)
Requirement already satisfied, skipping upgrade: beautifulsoup4 in c:\users\david\anaconda3\lib\site-packages (from twint) (4.9.1)
Requirement already satisfied, skipping upgrade: cchardet in c:\users\david\appdata\roaming\python\python38\site-packages (from twint) (2.1.6)
Requirement already satisfied, skipping upgrade: elasticsearch in c:\users\david\appdata\roaming\python\python38\site-packages (from twint) (7.9.1)
Requirement already satisfied, skipping upgrade: pysocks in c:\users\david\anaconda3\lib\site-packages (from twint) (1.7.1)
Requirement already satisfied, skipping upgrade: pandas in c:\users\david\anaconda3\lib\site-packages (from twint) (1.0.5)
Requirement already satisfied, skipping upgrade: aiohttp_socks in c:\users\david\appdata\roaming\python\python38\site-packages (from twint) (0.5.4)
Requirement already satisfied, skipping upgrade: schedule in c:\users\david\appdata\roaming\python\python38\site-packages (from twint) (0.6.0)
Requirement already satisfied, skipping upgrade: geopy in c:\users\david\appdata\roaming\python\python38\site-packages (from twint) (2.0.0)
Requirement already satisfied, skipping upgrade: fake-useragent in c:\users\david\appdata\roaming\python\python38\site-packages (from twint) (0.1.11)
Requirement already satisfied, skipping upgrade: googletransx in c:\users\david\appdata\roaming\python\python38\site-packages (from twint) (2.4.2)
Requirement already satisfied, skipping upgrade: async-timeout<4.0,>=3.0 in c:\users\david\appdata\roaming\python\python38\site-packages (from aiohttp->twint) (3.0.1)
Requirement already satisfied, skipping upgrade: chardet<4.0,>=2.0 in c:\users\david\anaconda3\lib\site-packages (from aiohttp->twint) (3.0.4)
Requirement already satisfied, skipping upgrade: multidict<5.0,>=4.5 in c:\users\david\appdata\roaming\python\python38\site-packages (from aiohttp->twint) (4.7.6)
Requirement already satisfied, skipping upgrade: yarl<2.0,>=1.0 in c:\users\david\appdata\roaming\python\python38\site-packages (from aiohttp->twint) (1.5.1)
Requirement already satisfied, skipping upgrade: attrs>=17.3.0 in c:\users\david\anaconda3\lib\site-packages (from aiohttp->twint) (19.3.0)
Requirement already satisfied, skipping upgrade: pycares>=3.0.0 in c:\users\david\appdata\roaming\python\python38\site-packages (from aiodns->twint) (3.1.1)
Requirement already satisfied, skipping upgrade: soupsieve>1.2 in c:\users\david\anaconda3\lib\site-packages (from beautifulsoup4->twint) (2.0.1)
Requirement already satisfied, skipping upgrade: certifi in c:\users\david\anaconda3\lib\site-packages (from elasticsearch->twint) (2020.6.20)
Requirement already satisfied, skipping upgrade: urllib3>=1.21.1 in c:\users\david\anaconda3\lib\site-packages (from elasticsearch->twint) (1.25.9)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.6.1 in c:\users\david\anaconda3\lib\site-packages (from pandas->twint) (2.8.1)
Requirement already satisfied, skipping upgrade: numpy>=1.13.3 in c:\users\david\anaconda3\lib\site-packages (from pandas->twint) (1.18.5)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in c:\users\david\anaconda3\lib\site-packages (from pandas->twint) (2020.1)
Requirement already satisfied, skipping upgrade: python-socks[asyncio]>=1.0.1 in c:\users\david\appdata\roaming\python\python38\site-packages (from aiohttp_socks->twint) (1.0.1)
Requirement already satisfied, skipping upgrade: geographiclib<2,>=1.49 in c:\users\david\appdata\roaming\python\python38\site-packages (from geopy->twint) (1.50)
Requirement already satisfied, skipping upgrade: requests in c:\users\david\anaconda3\lib\site-packages (from googletransx->twint) (2.24.0)
Requirement already satisfied, skipping upgrade: idna>=2.0 in c:\users\david\anaconda3\lib\site-packages (from yarl<2.0,>=1.0->aiohttp->twint) (2.10)
Requirement already satisfied, skipping upgrade: cffi>=1.5.0 in c:\users\david\anaconda3\lib\site-packages (from pycares>=3.0.0->aiodns->twint) (1.14.0)
Requirement already satisfied, skipping upgrade: six>=1.5 in c:\users\david\anaconda3\lib\site-packages (from python-dateutil>=2.6.1->pandas->twint) (1.15.0)
Requirement already satisfied, skipping upgrade: pycparser in c:\users\david\anaconda3\lib\site-packages (from cffi>=1.5.0->pycares>=3.0.0->aiodns->twint) (2.20)
Building wheels for collected packages: twint
  Building wheel for twint (setup.py) ... done
  Created wheel for twint: filename=twint-2.1.21-py3-none-any.whl size=35755 sha256=0cc94e851213488b7b0dc60a0763c542e7e0b0bec1a7c5ea7ba7903ef8d7ce45
  Stored in directory: C:\Users\david\AppData\Local\Temp\pip-ephem-wheel-cache-o1b3m4so\wheels\82\67\14\5495652787d3c55288164de4234c0712a1f785a64f61f1ea70
Successfully built twint
Installing collected packages: twint
  Attempting uninstall: twint
    Found existing installation: twint 2.1.21
    Uninstalling twint-2.1.21:
      Successfully uninstalled twint-2.1.21
Successfully installed twint-2.1.21
```

I think it is already solved but now I look for a user, for example @pacodelatorrep with the command `twint -u pacodelatorrep` (You can check that this user exists, the same thing happens with any other user)and it returns the following:

```
CRITICAL:root:twint.get:User:
Traceback (most recent call last):
  File "c:\users\david\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\david\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\david\AppData\Roaming\Python\Python38\Scripts\twint.exe\__main__.py", line 7, in <module>
  File "C:\Users\david\AppData\Roaming\Python\Python38\site-packages\twint\cli.py", line 311, in run_as_command
    main()
  File "C:\Users\david\AppData\Roaming\Python\Python38\site-packages\twint\cli.py", line 303, in main
    run.Search(c)
  File "C:\Users\david\AppData\Roaming\Python\Python38\site-packages\twint\run.py", line 386, in Search
    run(config, callback)
  File "C:\Users\david\AppData\Roaming\Python\Python38\site-packages\twint\run.py", line 285, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "c:\users\david\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\david\AppData\Roaming\Python\Python38\site-packages\twint\run.py", line 211, in main
    await task
  File "C:\Users\david\AppData\Roaming\Python\Python38\site-packages\twint\run.py", line 228, in run
    raise ValueError("Cannot find twitter account with name = " + self.config.Username)
ValueError: Cannot find twitter account with name = pacodelatorrep
```

Why is this happening? how can I solve it?

**Comment by estebanpdl** [comment]
Hi, @DavidPerea 
Recommendation: You should follow this thread https://github.com/twintproject/twint/pull/917, or this one https://github.com/twintproject/twint/issues/915.

Twitter made some changes to its platform, including endpoints. This is affecting how Twint works.
In your case, there are some recommendations. Instead of using `twint -u username`, you should try `twint -s "from:username"`. However, these options are not conclusive. I tried the second one, and the script froze (did not return any data). I think right now the `cli` option is not working as expected.
