### ISSUE TITLE
CRITICAL:root:twint.get:User:'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by bea-em** [twintproject/twint#925]
Python version is 3.7.6
I installed Twint with: pip3 install twint
I have updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`

### Command Ran
twint -u WirVsVirus --following --user-full

### Description of Issue
I have yet to see if the installation is working and tried some mock searches.
I get the following error and message:

CRITICAL:root:twint.get:User:'NoneType' object has no attribute 'find'
Traceback (most recent call last):
  File "/Users/bahar/opt/anaconda3/bin/twint", line 11, in <module>
    load_entry_point('twint', 'console_scripts', 'twint')()
  File "/Users/bahar/src/twint/twint/cli.py", line 311, in run_as_command
    main()
  File "/Users/bahar/src/twint/twint/cli.py", line 274, in main
    run.Following(c)
  File "/Users/bahar/src/twint/twint/run.py", line 324, in Following
    run(config)
  File "/Users/bahar/src/twint/twint/run.py", line 285, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "/Users/bahar/opt/anaconda3/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/Users/bahar/src/twint/twint/run.py", line 211, in main
    await task
  File "/Users/bahar/src/twint/twint/run.py", line 228, in run
    raise ValueError("Cannot find twitter account with name = " + self.config.Username)
ValueError: Cannot find twitter account with name = WirVsVirus

### Environment Details
I tried it with Jupyter Notebook as well as Terminal. MacOS Catalina 10.15.6.

**Comment by mjh-sakh** [comment]
Same here with clean Python 3.6 environment. Actually, any search by user would result in "ValueError: Cannot find twitter account with name = ".
