### ISSUE TITLE
[QUESTION] Installation instructions do not provide a successful installation

### ISSUE THREAD

**Issue by rredford6** [twintproject/twint#927]
### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [x] Python version is 3.6;
- [x] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [x] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.
I tried installing twint via pip and it seems to have installed correctly but isn't available to run:
```
me@hostname:~$ mkdir ~/twint
me@hostname:~$ cd ~/twint/
me@hostname:~/twint$ pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint
Obtaining twint from git+https://github.com/twintproject/twint.git@origin/master#egg=twint
  Cloning https://github.com/twintproject/twint.git (to origin/master) to ./src/twint
Collecting aiodns (from twint)
  Using cached https://files.pythonhosted.org/packages/da/01/8f2d49b441573fd2478833bdba91cf0b853b4c750a1fbb9e98de1b94bb22/aiodns-2.0.0-py2.py3-none-any.whl
Collecting aiohttp (from twint)
  Using cached https://files.pythonhosted.org/packages/7c/39/7eb5f98d24904e0f6d3edb505d4aa60e3ef83c0a58d6fe18244a51757247/aiohttp-3.6.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting aiohttp_socks (from twint)
  Using cached https://files.pythonhosted.org/packages/14/11/67750d2d6ba48eae602392b55513441058a2a004e5271276df03d3ed6393/aiohttp_socks-0.5.5-py3-none-any.whl
Collecting beautifulsoup4 (from twint)
  Using cached https://files.pythonhosted.org/packages/66/25/ff030e2437265616a1e9b25ccc864e0371a0bc3adb7c5a404fd661c6f4f6/beautifulsoup4-4.9.1-py3-none-any.whl
Collecting cchardet (from twint)
  Using cached https://files.pythonhosted.org/packages/d3/b9/c82e376881f3894869541fea2d5b79ec8e89517aebad0750d0e800ac5b4b/cchardet-2.1.6-cp36-cp36m-manylinux1_x86_64.whl
Collecting elasticsearch (from twint)
  Using cached https://files.pythonhosted.org/packages/e4/b7/f8f03019089671486e2910282c1b6fce26ccc8a513322df72ac8994ab2de/elasticsearch-7.9.1-py2.py3-none-any.whl
Collecting fake-useragent (from twint)
Collecting geopy (from twint)
  Using cached https://files.pythonhosted.org/packages/07/e1/9c72de674d5c2b8fcb0738a5ceeb5424941fefa080bfe4e240d0bacb5a38/geopy-2.0.0-py3-none-any.whl
Collecting googletransx (from twint)
Collecting pandas (from twint)
  Using cached https://files.pythonhosted.org/packages/1c/11/e1f53db0614f2721027aab297c8afd2eaf58d33d566441a97ea454541c5e/pandas-1.1.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting pysocks (from twint)
  Using cached https://files.pythonhosted.org/packages/8d/59/b4572118e098ac8e46e399a1dd0f2d85403ce8bbaad9ec79373ed6badaf9/PySocks-1.7.1-py3-none-any.whl
Collecting schedule (from twint)
  Using cached https://files.pythonhosted.org/packages/57/22/3a709462eb02412bd1145f6e53604f36bba191e3e4e397bea4a718fec38c/schedule-0.6.0-py2.py3-none-any.whl
Collecting pycares>=3.0.0 (from aiodns->twint)
  Using cached https://files.pythonhosted.org/packages/96/bc/1de12c0ea1de6c5454ca8e49479b5af162163b6c274f5302ba93e979d5b6/pycares-3.1.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting typing; python_version < "3.7" (from aiodns->twint)
Collecting typing-extensions>=3.6.5; python_version < "3.7" (from aiohttp->twint)
  Using cached https://files.pythonhosted.org/packages/60/7a/e881b5abb54db0e6e671ab088d079c57ce54e8a01a3ca443f561ccadb37e/typing_extensions-3.7.4.3-py3-none-any.whl
Collecting multidict<5.0,>=4.5 (from aiohttp->twint)
  Using cached https://files.pythonhosted.org/packages/1a/95/f50352b5366e7d579e8b99631680a9e32e1b22adfa1629a8f23b1d22d5e2/multidict-4.7.6-cp36-cp36m-manylinux1_x86_64.whl
Collecting chardet<4.0,>=2.0 (from aiohttp->twint)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting yarl<2.0,>=1.0 (from aiohttp->twint)
  Downloading https://files.pythonhosted.org/packages/01/c9/379b807a9c298b9694d0af8ee4260be7d40ab1a11fb9d4ae9e70b1e69d96/yarl-1.6.0-cp36-cp36m-manylinux1_x86_64.whl (257kB)
    100% |████████████████████████████████| 266kB 1.1MB/s
Collecting attrs>=17.3.0 (from aiohttp->twint)
  Using cached https://files.pythonhosted.org/packages/14/df/479736ae1ef59842f512548bacefad1abed705e400212acba43f9b0fa556/attrs-20.2.0-py2.py3-none-any.whl
Collecting async-timeout<4.0,>=3.0 (from aiohttp->twint)
  Using cached https://files.pythonhosted.org/packages/e1/1e/5a4441be21b0726c4464f3f23c8b19628372f606755a9d2e46c187e65ec4/async_timeout-3.0.1-py3-none-any.whl
Collecting idna-ssl>=1.0; python_version < "3.7" (from aiohttp->twint)
Collecting python-socks[asyncio]>=1.0.1 (from aiohttp_socks->twint)
  Using cached https://files.pythonhosted.org/packages/ac/7e/d16155d2662ee91bf3b2d548ba72e41c50a2a5870e090abe99fbe77797a2/python_socks-1.1.0-py3-none-any.whl
Collecting soupsieve>1.2 (from beautifulsoup4->twint)
  Using cached https://files.pythonhosted.org/packages/6f/8f/457f4a5390eeae1cc3aeab89deb7724c965be841ffca6cfca9197482e470/soupsieve-2.0.1-py3-none-any.whl
Collecting urllib3>=1.21.1 (from elasticsearch->twint)
  Using cached https://files.pythonhosted.org/packages/9f/f0/a391d1463ebb1b233795cabfc0ef38d3db4442339de68f847026199e69d7/urllib3-1.25.10-py2.py3-none-any.whl
Collecting certifi (from elasticsearch->twint)
  Using cached https://files.pythonhosted.org/packages/5e/c4/6c4fe722df5343c33226f0b4e0bb042e4dc13483228b4718baf286f86d87/certifi-2020.6.20-py2.py3-none-any.whl
Collecting geographiclib<2,>=1.49 (from geopy->twint)
  Using cached https://files.pythonhosted.org/packages/8b/62/26ec95a98ba64299163199e95ad1b0e34ad3f4e176e221c40245f211e425/geographiclib-1.50-py3-none-any.whl
Collecting requests (from googletransx->twint)
  Using cached https://files.pythonhosted.org/packages/45/1e/0c169c6a5381e241ba7404532c16a21d86ab872c9bed8bdcd4c423954103/requests-2.24.0-py2.py3-none-any.whl
Collecting python-dateutil>=2.7.3 (from pandas->twint)
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting numpy>=1.15.4 (from pandas->twint)
  Using cached https://files.pythonhosted.org/packages/b8/e5/a64ef44a85397ba3c377f6be9c02f3cb3e18023f8c89850dd319e7945521/numpy-1.19.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting pytz>=2017.2 (from pandas->twint)
  Using cached https://files.pythonhosted.org/packages/4f/a4/879454d49688e2fad93e59d7d4efda580b783c745fd2ec2a3adf87b0808d/pytz-2020.1-py2.py3-none-any.whl
Collecting cffi>=1.5.0 (from pycares>=3.0.0->aiodns->twint)
  Using cached https://files.pythonhosted.org/packages/50/ca/bbca0fd95b24a1d4f0d2e016f09f35ae68d4fe72bf34cc538d0a0d2d3e10/cffi-1.14.3-cp36-cp36m-manylinux1_x86_64.whl
Collecting idna>=2.0 (from yarl<2.0,>=1.0->aiohttp->twint)
  Using cached https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil>=2.7.3->pandas->twint)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.5.0->pycares>=3.0.0->aiodns->twint)
  Using cached https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl
Installing collected packages: pycparser, cffi, pycares, typing, aiodns, typing-extensions, multidict, chardet, idna, yarl, attrs, async-timeout, idna-ssl, aiohttp, python-socks, aiohttp-socks, soupsieve, beautifulsoup4, cchardet, urllib3, certifi, elasticsearch, fake-useragent, geographiclib, geopy, requests, googletransx, six, python-dateutil, numpy, pytz, pandas, pysocks, schedule, twint
  Found existing installation: twint 2.1.20
    Uninstalling twint-2.1.20:
      Successfully uninstalled twint-2.1.20
  Running setup.py develop for twint
Successfully installed aiodns-2.0.0 aiohttp-3.6.2 aiohttp-socks-0.5.5 async-timeout-3.0.1 attrs-20.2.0 beautifulsoup4-4.9.1 cchardet-2.1.6 certifi-2020.6.20 cffi-1.14.3 chardet-3.0.4 elasticsearch-7.9.1 fake-useragent-0.1.11 geographiclib-1.50 geopy-2.0.0 googletransx-2.4.2 idna-2.10 idna-ssl-1.1.0 multidict-4.7.6 numpy-1.19.2 pandas-1.1.2 pycares-3.1.1 pycparser-2.20 pysocks-1.7.1 python-dateutil-2.8.1 python-socks-1.1.0 pytz-2020.1 requests-2.24.0 schedule-0.6.0 six-1.15.0 soupsieve-2.0.1 twint typing-3.7.4.3 typing-extensions-3.7.4.3 urllib3-1.25.10 yarl-1.6.0
me@hostname:~/twint$
me@hostname:~/twint$ twint

Command 'twint' not found, did you mean:

  command 'tint' from deb tint
  command 'twine' from deb twine
  command 'twist' from deb python-twisted-core

Try: sudo apt install <deb name>
```

Python 3.6 is required and I have that:
```none
me@hostname:~$ pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
me@hostname:~$ python3 --version
Python 3.6.9
```
Note that I have to have python 2 installed on the same box for other system dependencies
```none
me@hostname:~$ python --version
Python 2.7.17
```

So I tried installing from source:
```none
me@hostname:~$ cd ~
me@hostname:~$ git clone https://github.com/twintproject/twint.git
Cloning into 'twint'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4376 (delta 0), reused 3 (delta 0), pack-reused 4372
Receiving objects: 100% (4376/4376), 4.43 MiB | 5.40 MiB/s, done.
Resolving deltas: 100% (2573/2573), done.
me@hostname:~$ cd twint
me@hostname:~/twint$ pip3 install . -r requirements.txt
Processing /home/me/twint
Collecting aiohttp (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/7c/39/7eb5f98d24904e0f6d3edb505d4aa60e3ef83c0a58d6fe18244a51757247/aiohttp-3.6.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting aiodns (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/da/01/8f2d49b441573fd2478833bdba91cf0b853b4c750a1fbb9e98de1b94bb22/aiodns-2.0.0-py2.py3-none-any.whl
Collecting beautifulsoup4 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/66/25/ff030e2437265616a1e9b25ccc864e0371a0bc3adb7c5a404fd661c6f4f6/beautifulsoup4-4.9.1-py3-none-any.whl
Collecting cchardet (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/d3/b9/c82e376881f3894869541fea2d5b79ec8e89517aebad0750d0e800ac5b4b/cchardet-2.1.6-cp36-cp36m-manylinux1_x86_64.whl
Collecting dataclasses (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/e1/d2/6f02df2616fd4016075f60157c7a0452b38d8f7938ae94343911e0fb0b09/dataclasses-0.7-py3-none-any.whl
Collecting elasticsearch (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/e4/b7/f8f03019089671486e2910282c1b6fce26ccc8a513322df72ac8994ab2de/elasticsearch-7.9.1-py2.py3-none-any.whl
Collecting pysocks (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/8d/59/b4572118e098ac8e46e399a1dd0f2d85403ce8bbaad9ec79373ed6badaf9/PySocks-1.7.1-py3-none-any.whl
Collecting pandas>=0.23.0 (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/1c/11/e1f53db0614f2721027aab297c8afd2eaf58d33d566441a97ea454541c5e/pandas-1.1.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting aiohttp_socks<=0.4.1 (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/72/55/c00bf359a54c1438ac0fe36f9bba9538c912138f033897d4e95ddd8cc772/aiohttp_socks-0.4.1-py3-none-any.whl
Collecting schedule (from -r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/57/22/3a709462eb02412bd1145f6e53604f36bba191e3e4e397bea4a718fec38c/schedule-0.6.0-py2.py3-none-any.whl
Collecting geopy (from -r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/07/e1/9c72de674d5c2b8fcb0738a5ceeb5424941fefa080bfe4e240d0bacb5a38/geopy-2.0.0-py3-none-any.whl
Collecting fake-useragent (from -r requirements.txt (line 12))
Collecting googletransx (from -r requirements.txt (line 13))
Collecting attrs>=17.3.0 (from aiohttp->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/14/df/479736ae1ef59842f512548bacefad1abed705e400212acba43f9b0fa556/attrs-20.2.0-py2.py3-none-any.whl
Collecting chardet<4.0,>=2.0 (from aiohttp->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting yarl<2.0,>=1.0 (from aiohttp->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/01/c9/379b807a9c298b9694d0af8ee4260be7d40ab1a11fb9d4ae9e70b1e69d96/yarl-1.6.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting multidict<5.0,>=4.5 (from aiohttp->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/1a/95/f50352b5366e7d579e8b99631680a9e32e1b22adfa1629a8f23b1d22d5e2/multidict-4.7.6-cp36-cp36m-manylinux1_x86_64.whl
Collecting idna-ssl>=1.0; python_version < "3.7" (from aiohttp->-r requirements.txt (line 1))
Collecting async-timeout<4.0,>=3.0 (from aiohttp->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/e1/1e/5a4441be21b0726c4464f3f23c8b19628372f606755a9d2e46c187e65ec4/async_timeout-3.0.1-py3-none-any.whl
Collecting typing-extensions>=3.6.5; python_version < "3.7" (from aiohttp->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/60/7a/e881b5abb54db0e6e671ab088d079c57ce54e8a01a3ca443f561ccadb37e/typing_extensions-3.7.4.3-py3-none-any.whl
Collecting pycares>=3.0.0 (from aiodns->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/96/bc/1de12c0ea1de6c5454ca8e49479b5af162163b6c274f5302ba93e979d5b6/pycares-3.1.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting typing; python_version < "3.7" (from aiodns->-r requirements.txt (line 2))
Collecting soupsieve>1.2 (from beautifulsoup4->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/6f/8f/457f4a5390eeae1cc3aeab89deb7724c965be841ffca6cfca9197482e470/soupsieve-2.0.1-py3-none-any.whl
Collecting certifi (from elasticsearch->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/5e/c4/6c4fe722df5343c33226f0b4e0bb042e4dc13483228b4718baf286f86d87/certifi-2020.6.20-py2.py3-none-any.whl
Collecting urllib3>=1.21.1 (from elasticsearch->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/9f/f0/a391d1463ebb1b233795cabfc0ef38d3db4442339de68f847026199e69d7/urllib3-1.25.10-py2.py3-none-any.whl
Collecting numpy>=1.15.4 (from pandas>=0.23.0->-r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/b8/e5/a64ef44a85397ba3c377f6be9c02f3cb3e18023f8c89850dd319e7945521/numpy-1.19.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting pytz>=2017.2 (from pandas>=0.23.0->-r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/4f/a4/879454d49688e2fad93e59d7d4efda580b783c745fd2ec2a3adf87b0808d/pytz-2020.1-py2.py3-none-any.whl
Collecting python-dateutil>=2.7.3 (from pandas>=0.23.0->-r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting geographiclib<2,>=1.49 (from geopy->-r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/8b/62/26ec95a98ba64299163199e95ad1b0e34ad3f4e176e221c40245f211e425/geographiclib-1.50-py3-none-any.whl
Collecting requests (from googletransx->-r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/45/1e/0c169c6a5381e241ba7404532c16a21d86ab872c9bed8bdcd4c423954103/requests-2.24.0-py2.py3-none-any.whl
Collecting idna>=2.0 (from yarl<2.0,>=1.0->aiohttp->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl
Collecting cffi>=1.5.0 (from pycares>=3.0.0->aiodns->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/50/ca/bbca0fd95b24a1d4f0d2e016f09f35ae68d4fe72bf34cc538d0a0d2d3e10/cffi-1.14.3-cp36-cp36m-manylinux1_x86_64.whl
Collecting six>=1.5 (from python-dateutil>=2.7.3->pandas>=0.23.0->-r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.5.0->pycares>=3.0.0->aiodns->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl
Installing collected packages: attrs, chardet, multidict, idna, typing-extensions, yarl, idna-ssl, async-timeout, aiohttp, pycparser, cffi, pycares, typing, aiodns, soupsieve, beautifulsoup4, cchardet, dataclasses, certifi, urllib3, elasticsearch, pysocks, numpy, pytz, six, python-dateutil, pandas, aiohttp-socks, schedule, geographiclib, geopy, fake-useragent, requests, googletransx, twint
  Running setup.py install for twint ... done
Successfully installed aiodns-2.0.0 aiohttp-3.6.2 aiohttp-socks-0.5.5 async-timeout-3.0.1 attrs-20.2.0 beautifulsoup4-4.9.1 cchardet-2.1.6 certifi-2020.6.20 cffi-1.14.3 chardet-3.0.4 dataclasses-0.7 elasticsearch-7.9.1 fake-useragent-0.1.11 geographiclib-1.50 geopy-2.0.0 googletransx-2.4.2 idna-2.10 idna-ssl-1.1.0 multidict-4.7.6 numpy-1.19.2 pandas-1.1.2 pycares-3.1.1 pycparser-2.20 pysocks-1.7.1 python-dateutil-2.8.1 pytz-2020.1 requests-2.24.0 schedule-0.6.0 six-1.15.0 soupsieve-2.0.1 twint-2.1.21 typing-3.7.4.3 typing-extensions-3.7.4.3 urllib3-1.25.10 yarl-1.6.0
me@hostname:~/twint$ twint

Command 'twint' not found, did you mean:

  command 'twine' from deb twine
  command 'twist' from deb python-twisted-core
  command 'tint' from deb tint

Try: sudo apt install <deb name>
```

Makse sense because there's no executable file with that same name:
```plain
me@hostname:~/twint$ ll
total 65,536
drwxrwxr-x  6 me me 4,096 Sep 24 18:19 ./
drwxr-xr-x 88 me me 4,096 Sep 24 18:19 ../
drwxrwxr-x  2 me me 4,096 Sep 24 18:19 elasticsearch/
drwxrwxr-x  8 me me 4,096 Sep 24 18:19 .git/
drwxrwxr-x  3 me me 4,096 Sep 24 18:19 .github/
drwxrwxr-x  3 me me 4,096 Sep 24 18:19 twint/
-rw-rw-r--  1 me me 2,066 Sep 24 18:19 automate.py
-rw-rw-r--  1 me me 1,296 Sep 24 18:19 .gitignore
-rw-rw-r--  1 me me 1,071 Sep 24 18:19 LICENSE
-rw-rw-r--  1 me me    26 Sep 24 18:19 MANIFEST.in
-rw-rw-r--  1 me me 8,176 Sep 24 18:19 README.md
-rw-rw-r--  1 me me   152 Sep 24 18:19 requirements.txt
-rw-rw-r--  1 me me 1,720 Sep 24 18:19 setup.py
-rw-rw-r--  1 me me 1,946 Sep 24 18:19 test.py
-rw-rw-r--  1 me me 1,017 Sep 24 18:19 .travis.yml
```

So how about invoking it manually?
```plain
me@hostname:~/twint$ python3 twint/cli.py
Traceback (most recent call last):
  File "twint/cli.py", line 15, in <module>
    from . import run
ImportError: cannot import name 'run'
```

### Description of Issue
>Please use **as much detail as possible.**
```plain
me@hostname:~/twint$ twint

Command 'twint' not found, did you mean:

  command 'twine' from deb twine
  command 'twist' from deb python-twisted-core
  command 'tint' from deb tint

Try: sudo apt install <deb name>
```
### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?
```plain
me@hostname:~/twint$ cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
me@hostname:~$ pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
me@hostname:~$ python3 --version
Python 3.6.9
```
Note that I have to have python 2 installed on the same box for other system dependencies
```none
me@hostname:~$ python --version
Python 2.7.17
```
I am *not* using any sort of venv

**Comment by duduScu** [comment]
twint is a python package, and you should import this package in python enviroment.
![image](https://user-images.githubusercontent.com/39080311/94396515-a8942200-0194-11eb-8d3c-069bd1a4bc25.png)

**Comment by rredford6** [comment]
I ran it from the directory where I showed `ll` above and get this:
```plain
me@hostname:~/twint$ python3
Python 3.6.9 (default, Jul 17 2020, 12:50:27)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import twint
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'twint'
```

**Comment by rredford6** [comment]
@duduScu any ideas?

**Comment by pielco11** [comment]
Strange, seems you are installing Twint in the right directory of the Python version you run

Instead of installing Twint as package, may you just clone the repo and `import` it? This should work, and has the same effect

**Comment by rredford6** [comment]
@pielco11 That's what I did, see "So I tried installing from source" above

**Comment by pielco11** [comment]
@rredford6 cloning locally the repo is not installing. Cloning is like downloading.
Once you cloned the repo, try the following command `python3 -c "import twint"`

To install from source, you should download first and then installing using the `setup.py` script and possible arguments
