### ISSUE TITLE
how can i run the python scraping?

### ISSUE THREAD

**Issue by tulipsliu** [twintproject/twint#936]
# Issue Template
Please use this template!

### Initial Check
> If the issue is a request please specify that it is a request in the title (Example: [REQUEST] more features). If this is a question regarding 'twint' please specify that it's a question in the title (Example: [QUESTION] What is x?). Please **only** submit issues related to 'twint'. Thanks.

>Make sure you've checked the following:

- [] Python version is 3.6;
- [] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>Please provide the _exact_ command ran including the username/search/code so I may reproduce the issue.

### Description of Issue
>Please use **as much detail as possible.**

### Environment Details
>Using Windows, Linux? What OS version? Running this in Anaconda? Jupyter Notebook? Terminal?

### my name is Daniel tulips liu ,a chinese man.
I have installed windows subsystem ubunt 18.04 . and my computer has already  install pytho3-pip,
when use git to clonte the code to my computer ,and run  pip3 install -r requesments.txt .
then ,tpye the code : twint --help ,every thing is right .

but ,when i use scraping ,my computer get the wrong result.

###  like this 
tulipsliu@DanielComputer:/mnt/c/Users/tulipsliu$ twint -u tulipsliu --search "matlab"
CRITICAL:root:twint.get:User:Cannot connect to host twitter.com:443 ssl:True [Connect call failed ('2001::4a75:b6b7', 443, 0, 0)]
Traceback (most recent call last):
  File "/home/tulipsliu/.local/bin/twint", line 11, in <module>
    load_entry_point('twint==2.1.21', 'console_scripts', 'twint')()
  File "/home/tulipsliu/.local/lib/python3.6/site-packages/twint/cli.py", line 311, in run_as_command
    main()
  File "/home/tulipsliu/.local/lib/python3.6/site-packages/twint/cli.py", line 303, in main
    run.Search(c)
  File "/home/tulipsliu/.local/lib/python3.6/site-packages/twint/run.py", line 386, in Search
    run(config, callback)
  File "/home/tulipsliu/.local/lib/python3.6/site-packages/twint/run.py", line 285, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/tulipsliu/.local/lib/python3.6/site-packages/twint/run.py", line 211, in main
    await task
  File "/home/tulipsliu/.local/lib/python3.6/site-packages/twint/run.py", line 228, in run
    raise ValueError("Cannot find twitter account with name = " + self.config.Username)
ValueError: Cannot find twitter account with name = tulipsliu

**Comment by tulipsliu** [comment]
dear all ,

thanks very much for your reply.
yours : Daniel tulips liu
