### ISSUE TITLE
Canot Find twitter account with name = ""

### ISSUE THREAD

**Issue by rex106** [twintproject/twint#945]
root@kali:~/Documents/tools/twint# twint -u Swamy39
CRITICAL:root:twint.get:User:'NoneType' object has no attribute 'find'
Traceback (most recent call last):
  File "/usr/local/bin/twint", line 8, in <module>
    sys.exit(run_as_command())
  File "/usr/local/lib/python3.8/dist-packages/twint/cli.py", line 311, in run_as_command
    main()
  File "/usr/local/lib/python3.8/dist-packages/twint/cli.py", line 303, in main
    run.Search(c)
  File "/usr/local/lib/python3.8/dist-packages/twint/run.py", line 386, in Search
    run(config, callback)
  File "/usr/local/lib/python3.8/dist-packages/twint/run.py", line 285, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/twint/run.py", line 211, in main
    await task
  File "/usr/local/lib/python3.8/dist-packages/twint/run.py", line 228, in run
    raise ValueError("Cannot find twitter account with name = " + self.config.Username)
ValueError: Cannot find twitter account with name = Swamy39

this is the error code
I'm running it on linux

**Comment by himanshudabas** [comment]
Refer to #915.
Twitter closed old API endpoints. Current version of _**twint**_ is not working anymore.

Temporarily you can use #944.
