### ISSUE TITLE
please don't use token.py as a file name 

### ISSUE THREAD

**Issue by TimsXH** [twintproject/twint#950]
(tw_new_version) E:\202010\tw_new_version>python twint/run.py -u up_mmyu03
Traceback (most recent call last):
  File "C:\Miniconda3\envs\tw_new_version\lib\queue.py", line 4, in <module>
    import threading
  File "C:\Miniconda3\envs\tw_new_version\lib\threading.py", line 7, in <module>
    from traceback import format_exc as _format_exc
ImportError: cannot import name 'format_exc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "twint/run.py", line 4, in <module>
    from asyncio import get_event_loop, TimeoutError, ensure_future, new_event_loop, set_event_loop
  File "C:\Miniconda3\envs\tw_new_version\lib\asyncio\__init__.py", line 21, in <module>
    from .base_events import *
  File "C:\Miniconda3\envs\tw_new_version\lib\asyncio\base_events.py", line 17, in <module>
    import concurrent.futures
  File "C:\Miniconda3\envs\tw_new_version\lib\concurrent\futures\__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "C:\Miniconda3\envs\tw_new_version\lib\concurrent\futures\_base.py", line 7, in <module>
    import logging
  File "C:\Miniconda3\envs\tw_new_version\lib\logging\__init__.py", line 26, in <module>
    import sys, os, time, io, traceback, warnings, weakref, collections
  File "C:\Miniconda3\envs\tw_new_version\lib\traceback.py", line 5, in <module>
    import linecache
  File "C:\Miniconda3\envs\tw_new_version\lib\linecache.py", line 11, in <module>
    import tokenize
  File "C:\Miniconda3\envs\tw_new_version\lib\tokenize.py", line 35, in <module>
    from token import *
  File "E:\202010\tw_new_version\twint\token.py", line 4, in <module>
    import requests
  File "C:\Miniconda3\envs\tw_new_version\lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Miniconda3\envs\tw_new_version\lib\site-packages\urllib3\__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "C:\Miniconda3\envs\tw_new_version\lib\site-packages\urllib3\connectionpool.py", line 28, in <module>
    from .packages.six.moves import queue
  File "C:\Miniconda3\envs\tw_new_version\lib\site-packages\urllib3\packages\six.py", line 91, in __get__
    result = self._resolve()
  File "C:\Miniconda3\envs\tw_new_version\lib\site-packages\urllib3\packages\six.py", line 113, in _resolve
    return _import_module(self.mod)
  File "C:\Miniconda3\envs\tw_new_version\lib\site-packages\urllib3\packages\six.py", line 82, in _import_modu
le
    __import__(name)
  File "C:\Miniconda3\envs\tw_new_version\lib\queue.py", line 6, in <module>
    import dummy_threading as threading
  File "C:\Miniconda3\envs\tw_new_version\lib\dummy_threading.py", line 45, in <module>
    import threading
  File "C:\Miniconda3\envs\tw_new_version\lib\threading.py", line 7, in <module>
    from traceback import format_exc as _format_exc
ImportError: cannot import name 'format_exc'

https://stackoverflow.com/questions/58241380/importerror-cannot-import-name-format-exc-error

**Comment by IBermudes** [comment]
I am currently working on a fix for this. Will try to push by tonight.
