### ISSUE TITLE
[QUESTION] Connection timeout cause

### ISSUE THREAD

**Issue by lmeyerov** [twintproject/twint#956]
Our tor-proxied Search calls are occasionally getting throwing `ConnectionAbortedError: SSL handshake is taking longer than 60.0 seconds: aborting the connection`

Curious if any intuitions on why and workarounds -- wait and retry, restart tor, ... ?

```
data-stream_1  | 2020-10-12T05:48:22.348219354Z     twint.run.Search(self.config)
data-stream_1  | 2020-10-12T05:48:22.348223841Z   File "/usr/local/lib/python3.7/site-packages/twint/run.py", line 427, in Search
data-stream_1  | 2020-10-12T05:48:22.348233679Z     run(config, callback)
data-stream_1  | 2020-10-12T05:48:22.348237942Z   File "/usr/local/lib/python3.7/site-packages/twint/run.py", line 319, in run
data-stream_1  | 2020-10-12T05:48:22.348243272Z     get_event_loop().run_until_complete(Twint(config).main(callback))
data-stream_1  | 2020-10-12T05:48:22.348247542Z   File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
data-stream_1  | 2020-10-12T05:48:22.348251974Z     return future.result()
data-stream_1  | 2020-10-12T05:48:22.348256572Z   File "/usr/local/lib/python3.7/site-packages/twint/run.py", line 239, in main
data-stream_1  | 2020-10-12T05:48:22.348261396Z     await task
data-stream_1  | 2020-10-12T05:48:22.348266352Z   File "/usr/local/lib/python3.7/site-packages/twint/run.py", line 268, in run
data-stream_1  | 2020-10-12T05:48:22.348271034Z     await self.tweets()
data-stream_1  | 2020-10-12T05:48:22.348275839Z   File "/usr/local/lib/python3.7/site-packages/twint/run.py", line 221, in tweets
data-stream_1  | 2020-10-12T05:48:22.348280269Z     await self.Feed()
data-stream_1  | 2020-10-12T05:48:22.348291503Z   File "/usr/local/lib/python3.7/site-packages/twint/run.py", line 61, in Feed
data-stream_1  | 2020-10-12T05:48:22.348296508Z     response = await get.RequestUrl(self.config, self.init, headers=[("User-Agent", self.user_agent)])
data-stream_1  | 2020-10-12T05:48:22.348301342Z   File "/usr/local/lib/python3.7/site-packages/twint/get.py", line 141, in RequestUrl
data-stream_1  | 2020-10-12T05:48:22.348312434Z     response = await Request(_url, params=params, connector=_connector, headers=_headers)
data-stream_1  | 2020-10-12T05:48:22.348317559Z   File "/usr/local/lib/python3.7/site-packages/twint/get.py", line 167, in Request
data-stream_1  | 2020-10-12T05:48:22.348322123Z     return await Response(session, _url, params)
data-stream_1  | 2020-10-12T05:48:22.348326553Z   File "/usr/local/lib/python3.7/site-packages/twint/get.py", line 173, in Response
data-stream_1  | 2020-10-12T05:48:22.348331042Z     async with session.get(_url, ssl=True, params=params, proxy=httpproxy) as response:
data-stream_1  | 2020-10-12T05:48:22.348335445Z   File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
data-stream_1  | 2020-10-12T05:48:22.348339797Z     self._resp = await self._coro
data-stream_1  | 2020-10-12T05:48:22.348344057Z   File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 483, in _request
data-stream_1  | 2020-10-12T05:48:22.348348679Z     timeout=real_timeout
data-stream_1  | 2020-10-12T05:48:22.348352710Z   File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 523, in connect
data-stream_1  | 2020-10-12T05:48:22.348357398Z     proto = await self._create_connection(req, traces, timeout)
data-stream_1  | 2020-10-12T05:48:22.348361681Z   File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 859, in _create_connection
data-stream_1  | 2020-10-12T05:48:22.348366262Z     req, traces, timeout)
data-stream_1  | 2020-10-12T05:48:22.348376214Z   File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
data-stream_1  | 2020-10-12T05:48:22.348380804Z     raise last_exc
data-stream_1  | 2020-10-12T05:48:22.348384872Z   File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 986, in _create_direct_connection
data-stream_1  | 2020-10-12T05:48:22.348389631Z     req=req, client_error=client_error)
data-stream_1  | 2020-10-12T05:48:22.348503003Z   File "/usr/local/lib/python3.7/site-packages/aiohttp_socks/connector.py", line 65, in _wrap_create_connection
data-stream_1  | 2020-10-12T05:48:22.348513971Z     **kwargs
data-stream_1  | 2020-10-12T05:48:22.348518599Z   File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 943, in _wrap_create_connection
data-stream_1  | 2020-10-12T05:48:22.348523432Z     raise client_error(req.connection_key, exc) from exc
data-stream_1  | 2020-10-12T05:48:22.348528265Z aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.twitter.com:443 ssl:True [None]
data-stream_1  | 2020-10-12T05:48:22.348533192Z ERROR:prefect.TaskRunner:Unexpected error: ClientConnectorError(ConnectionKey(host='api.twitter.com', port=443, is_ssl=True, ssl=True, proxy=None, proxy_auth=None, proxy_headers_hash=3789541556008087455), ConnectionAbortedError('SSL handshake is taking longer than 60.0 seconds: aborting the connection'))
data-stream_1  | 2020-10-12T05:48:22.348538821Z Traceback (most recent call last):
data-stream_1  | 2020-10-12T05:48:22.348543221Z   File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
data-stream_1  | 2020-10-12T05:48:22.348557506Z     return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
data-stream_1  | 2020-10-12T05:48:22.348561876Z   File "/usr/local/lib/python3.7/asyncio/base_events.py", line 989, in create_connection
data-stream_1  | 2020-10-12T05:48:22.348566432Z     ssl_handshake_timeout=ssl_handshake_timeout)
data-stream_1  | 2020-10-12T05:48:22.348570587Z   File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1017, in _create_connection_transport
data-stream_1  | 2020-10-12T05:48:22.348575520Z     await waiter
data-stream_1  | 2020-10-12T05:48:22.348580833Z ConnectionAbortedError: SSL handshake is taking longer than 60.0 seconds: aborting the connection
```

**Comment by himanshudabas** [comment]
can you try to replicate this on Python 3.6 ?

I suspect this can be related to `aiohttp` but not entirely sure.

**Comment by lmeyerov** [comment]
Will downgrade to 3.6 and try, it takes awhile to get to it. 

Just got another aiohttp somewhere else:

```
data-stream_1  | 2020-10-13T06:55:56.479267871Z ERROR:root:job exception
data-stream_1  | 2020-10-13T06:55:56.479313522Z Traceback (most recent call last):
data-stream_1  | 2020-10-13T06:55:56.479374859Z     twint.run.Search(self.config)
data-stream_1  | 2020-10-13T06:55:56.479379711Z   File "/usr/local/lib/python3.7/site-packages/twint/run.py", line 427, in Search
data-stream_1  | 2020-10-13T06:55:56.479384531Z     run(config, callback)
data-stream_1  | 2020-10-13T06:55:56.479389066Z   File "/usr/local/lib/python3.7/site-packages/twint/run.py", line 319, in run
data-stream_1  | 2020-10-13T06:55:56.479393752Z     get_event_loop().run_until_complete(Twint(config).main(callback))
data-stream_1  | 2020-10-13T06:55:56.479398256Z   File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
data-stream_1  | 2020-10-13T06:55:56.479402925Z     return future.result()
data-stream_1  | 2020-10-13T06:55:56.479407111Z   File "/usr/local/lib/python3.7/site-packages/twint/run.py", line 239, in main
data-stream_1  | 2020-10-13T06:55:56.479411522Z     await task
data-stream_1  | 2020-10-13T06:55:56.479415775Z   File "/usr/local/lib/python3.7/site-packages/twint/run.py", line 268, in run
data-stream_1  | 2020-10-13T06:55:56.479420368Z     await self.tweets()
data-stream_1  | 2020-10-13T06:55:56.479424596Z   File "/usr/local/lib/python3.7/site-packages/twint/run.py", line 221, in tweets
data-stream_1  | 2020-10-13T06:55:56.479429499Z     await self.Feed()
data-stream_1  | 2020-10-13T06:55:56.479433633Z   File "/usr/local/lib/python3.7/site-packages/twint/run.py", line 61, in Feed
data-stream_1  | 2020-10-13T06:55:56.479444151Z     response = await get.RequestUrl(self.config, self.init, headers=[("User-Agent", self.user_agent)])
data-stream_1  | 2020-10-13T06:55:56.479448948Z   File "/usr/local/lib/python3.7/site-packages/twint/get.py", line 141, in RequestUrl
data-stream_1  | 2020-10-13T06:55:56.479454173Z     response = await Request(_url, params=params, connector=_connector, headers=_headers)
data-stream_1  | 2020-10-13T06:55:56.479459227Z   File "/usr/local/lib/python3.7/site-packages/twint/get.py", line 167, in Request
data-stream_1  | 2020-10-13T06:55:56.479464084Z     return await Response(session, _url, params)
data-stream_1  | 2020-10-13T06:55:56.479468703Z   File "/usr/local/lib/python3.7/site-packages/twint/get.py", line 174, in Response
data-stream_1  | 2020-10-13T06:55:56.479473851Z     resp = await response.text()
data-stream_1  | 2020-10-13T06:55:56.479479642Z   File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1009, in text
data-stream_1  | 2020-10-13T06:55:56.479484519Z     await self.read()
data-stream_1  | 2020-10-13T06:55:56.479489015Z   File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 973, in read
data-stream_1  | 2020-10-13T06:55:56.479493862Z     self._body = await self.content.read()
data-stream_1  | 2020-10-13T06:55:56.479498636Z   File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 358, in read
data-stream_1  | 2020-10-13T06:55:56.479503513Z     block = await self.readany()
data-stream_1  | 2020-10-13T06:55:56.479513197Z   File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 380, in readany
data-stream_1  | 2020-10-13T06:55:56.479517888Z     await self._wait('readany')
data-stream_1  | 2020-10-13T06:55:56.479522027Z   File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 296, in _wait
data-stream_1  | 2020-10-13T06:55:56.479526555Z     await waiter
data-stream_1  | 2020-10-13T06:55:56.479531023Z aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
```

**Comment by lmeyerov** [comment]
Getting issues in 3.6 + 3.8, so seems like 3.7 as in the original report is the sweet spot...

**Comment by himanshudabas** [comment]
@lmeyerov seems to me an issue of aiohttp.
would be really difficult to debug until we have the exact `request, payload` of the _get request_ for which these errors occur.
Perhaps surround the erroneous block with _try: except_ and log the `url and params` to the log file if the script encounters this error. so you have a bit more data to analyze.
