### ISSUE TITLE
Get tweets in CMD

### ISSUE THREAD

**Issue by DavidPerea** [twintproject/twint#975]
I am trying to get tweets using Twint in the Command Prompt with the command `twint -u username`

It returns the following error: 

`Traceback (most recent call last):
  File "c:\users\davidperea\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\davidperea\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\DavidPerea\AppData\Local\Programs\Python\Python37-32\Scripts\twint.exe\__main__.py", line 4, in <module>
  File "C:\Users\DavidPerea\AppData\Roaming\Python\Python37\site-packages\twint\__init__.py", line 14, in <module>
    from . import run
  File "C:\Users\DavidPerea\AppData\Roaming\Python\Python37\site-packages\twint\run.py", line 4, in <module>
    from . import datelock, feed, get, output, verbose, storage
  File "C:\Users\DavidPerea\AppData\Roaming\Python\Python37\site-packages\twint\get.py", line 12, in <module>
    from aiohttp_socks import ProxyConnector, ProxyType
ImportError: cannot import name 'ProxyConnector' from 'aiohttp_socks' (c:\users\davidperea\appdata\local\programs\python\python37-32\lib\site-packages\aiohttp_socks\__init__.py)`

What I can do? I need urgent help please.

**Comment by arpanadlakhiya** [comment]
It seems it is unable to import the required name from `aiohttp_socks`. Make sure you have run `python -m pip install -r requirements.txt` to have the correct versions of all modules installed.
Or you may try updating the `aiohttp_socks` module using `python -m pip install --upgrade aiohttp_socks`
