### ISSUE TITLE
Cannot find user

### ISSUE THREAD

**Issue by jbowen383** [twintproject/twint#980]
twint -u inteltechniques
CRITICAL:root:twint.get:User:'NoneType' object has no attribute 'find'
Traceback (most recent call last):
  File "/usr/local/bin/twint", line 11, in <module>
    load_entry_point('twint==2.1.21', 'console_scripts', 'twint')()
  File "/usr/local/lib/python3.8/dist-packages/twint-2.1.21-py3.8.egg/twint/cli.py", line 311, in run_as_command
  File "/usr/local/lib/python3.8/dist-packages/twint-2.1.21-py3.8.egg/twint/cli.py", line 303, in main
  File "/usr/local/lib/python3.8/dist-packages/twint-2.1.21-py3.8.egg/twint/run.py", line 386, in Search
  File "/usr/local/lib/python3.8/dist-packages/twint-2.1.21-py3.8.egg/twint/run.py", line 285, in run
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/twint-2.1.21-py3.8.egg/twint/run.py", line 211, in main
  File "/usr/local/lib/python3.8/dist-packages/twint-2.1.21-py3.8.egg/twint/run.py", line 228, in run
ValueError: Cannot find twitter account with name = inteltechniques

**Comment by milahu** [comment]
same here, please re-open the issue

```
$ pip3 install --user --upgrade git+https://github.com/twintproject/twint.git@origin/master#egg=twint

$ twint -u inteltechniques
/usr/lib/python3.8/site-packages/aiohttp-4.0.0a1-py3.8-linux-x86_64.egg/aiohttp/client.py:977: RuntimeWarning: coroutine 'noop' was never awaited
  self._resp.release()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
CRITICAL:root:twint.get:User:'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/bin/twint", line 11, in <module>
    load_entry_point('twint==2.1.20', 'console_scripts', 'twint')()
  File "/usr/lib/python3.8/site-packages/twint-2.1.20-py3.8.egg/twint/cli.py", line 309, in run_as_command
  File "/usr/lib/python3.8/site-packages/twint-2.1.20-py3.8.egg/twint/cli.py", line 301, in main
  File "/usr/lib/python3.8/site-packages/twint-2.1.20-py3.8.egg/twint/run.py", line 329, in Search
  File "/usr/lib/python3.8/site-packages/twint-2.1.20-py3.8.egg/twint/run.py", line 228, in run
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/lib/python3.8/site-packages/twint-2.1.20-py3.8.egg/twint/run.py", line 154, in main
  File "/usr/lib/python3.8/site-packages/twint-2.1.20-py3.8.egg/twint/run.py", line 171, in run
ValueError: Cannot find twitter account with name = inteltechniques
```
but obviously, the account exists at https://twitter.com/inteltechniques

**Comment by milahu** [comment]
duplicate of #915
possible solution in #944
