### ISSUE TITLE
Can't do any research 

### ISSUE THREAD

**Issue by 1375AMG10** [twintproject/twint#988]

**Comment by 1375AMG10** [comment]
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
CRITICAL:root:twint.get:User:'NoneType' object has no attribute 'find'
Traceback (most recent call last):
  File "/usr/local/bin/twint", line 8, in <module>
    sys.exit(run_as_command())
  File "/usr/local/lib/python3.8/dist-packages/twint/cli.py", line 311, in run_as_command
    main()
  File "/usr/local/lib/python3.8/dist-packages/twint/cli.py", line 283, in main
    run.Followers(c)
  File "/usr/local/lib/python3.8/dist-packages/twint/run.py", line 307, in Followers
    run(config)
  File "/usr/local/lib/python3.8/dist-packages/twint/run.py", line 285, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/twint/run.py", line 211, in main
    await task
  File "/usr/local/lib/python3.8/dist-packages/twint/run.py", line 228, in run
    raise ValueError("Cannot find twitter account with name = " + self.config.Username)
